SELECT 
s.ID as spellid,  
school as fk_school,
category as category,
castUI as castUI,
NULLIF(dispelType,0) as fk_dispelType,
NULLIF(mechanic,0) as fk_mechanic,

-- Attributes

(attributes & b'1') as attrUnknown0,
(attributes >> 1 & b'1') as attrRanged,
(attributes >> 2 & b'1') as attrOnNextSwing,
(attributes >> 3 & b'1') as attrUnknown3,
(attributes >> 4 & b'1') as attrUnknown4,
(attributes >> 5 & b'1') as attrTrade,
(attributes >> 6 & b'1') as attrPassive,
(attributes >> 7 & b'1') as attrHide,
(attributes >> 8 & b'1') as attrUnknown8,
(attributes >> 9 & b'1') as attrUnknown9,
(attributes >> 10 & b'1') as attrOnNextSwing2,
(attributes >> 11 & b'1') as attrUnknown11,
(attributes >> 12 & b'1') as attrDayOnly,
(attributes >> 13 & b'1') as attrNightOnly,
(attributes >> 14 & b'1') as attrIndoorsOnly,
(attributes >> 15 & b'1') as attrOutdoorsOnly,
(attributes >> 16 & b'1') as attrNotShapeshift,
(attributes >> 17 & b'1') as attrOnlyStealthed,
(attributes >> 18 & b'1') as attrUnknown18,
(attributes >> 19 & b'1') as attrLevelDamageCalc,
(attributes >> 20 & b'1') as attrStopAttack,
(attributes >> 21 & b'1') as attrNotAvoidable,
(attributes >> 22 & b'1') as attrTrackTarget,
(attributes >> 23 & b'1') as attrUnknown23,
(attributes >> 24 & b'1') as attrCastOnMount,
(attributes >> 25 & b'1') as attrDisabledWhileActive,
(attributes >> 26 & b'1') as attrUnknown26,
(attributes >> 27 & b'1') as attrCastSit,
(attributes >> 28 & b'1') as attrNotInCombat,
(attributes >> 29 & b'1') as attrUnaffectedByInvuln,
(attributes >> 30 & b'1') as attrUnknown30,
(attributes >> 31 & b'1') as attrNotCancellable,

-- AttributesEx

(attributesEx & b'1') as attrExUnknown0,
(attributesEx >> 1 & b'1') as attrExDrainAllPower,
(attributesEx >> 2 & b'1') as attrExChanneled,
(attributesEx >> 3 & b'1') as attrExUnknown3,
(attributesEx >> 4 & b'1') as attrExUnknown4,
(attributesEx >> 5 & b'1') as attrExRemainStealth,
(attributesEx >> 6 & b'1') as attrExChanneled2,
(attributesEx >> 7 & b'1') as attrExNegative,
(attributesEx >> 8 & b'1') as attrExTargetNotInCombat,
(attributesEx >> 9 & b'1') as attrExUnknown9,
(attributesEx >> 10 & b'1') as attrExNoThreat,
(attributesEx >> 11 & b'1') as attrExUnknown11,
(attributesEx >> 12 & b'1') as attrExUnknown12,
(attributesEx >> 13 & b'1') as attrExFarSight,
(attributesEx >> 14 & b'1') as attrExUnknown14,
(attributesEx >> 15 & b'1') as attrExRemoveAurasOnImmune,
(attributesEx >> 16 & b'1') as attrExUnaffectedBySchoolImmune,
(attributesEx >> 17 & b'1') as attrExUnknown17,
(attributesEx >> 18 & b'1') as attrExUnknown18,
(attributesEx >> 19 & b'1') as attrExUnknown19,
(attributesEx >> 20 & b'1') as attrExTargetComboPoints,
(attributesEx >> 21 & b'1') as attrExUnknown21,
(attributesEx >> 22 & b'1') as attrExRequireComboPoints,
(attributesEx >> 23 & b'1') as attrExUnknown23,
(attributesEx >> 24 & b'1') as attrExUnknown24,
(attributesEx >> 25 & b'1') as attrExUnknown25,
(attributesEx >> 26 & b'1') as attrExUnknown26,
(attributesEx >> 27 & b'1') as attrExUnknown27,
(attributesEx >> 28 & b'1') as attrExUnknown28,
(attributesEx >> 29 & b'1') as attrExUnknown29,
(attributesEx >> 30 & b'1') as attrExUnknown30,
(attributesEx >> 31 & b'1') as attrExUnknown31,

-- AttributesEx2

(attributesEx2 & b'1') as attrEx2Unknown0,
(attributesEx2 >> 1 & b'1') as attrEx2Unknown1,
(attributesEx2 >> 2 & b'1') as attrEx2CantReflect,
(attributesEx2 >> 3 & b'1') as attrEx2Unknown3,
(attributesEx2 >> 4 & b'1') as attrEx2Unknown4,
(attributesEx2 >> 5 & b'1') as attrEx2AutoRepeat,
(attributesEx2 >> 6 & b'1') as attrEx2Unknown6,
(attributesEx2 >> 7 & b'1') as attrEx2Unknown7,
(attributesEx2 >> 8 & b'1') as attrEx2Unknown8,
(attributesEx2 >> 9 & b'1') as attrEx2Unknown9,
(attributesEx2 >> 10 & b'1') as attrEx2Unknown10,
(attributesEx2 >> 11 & b'1') as attrEx2HealthFunnel,
(attributesEx2 >> 12 & b'1') as attrEx2Unknown12,
(attributesEx2 >> 13 & b'1') as attrEx2Unknown13,
(attributesEx2 >> 14 & b'1') as attrEx2Unknown14,
(attributesEx2 >> 15 & b'1') as attrEx2Unknown15,
(attributesEx2 >> 16 & b'1') as attrEx2Unknown16,
(attributesEx2 >> 17 & b'1') as attrEx2Unknown17,
(attributesEx2 >> 18 & b'1') as attrEx2Unknown18,
(attributesEx2 >> 19 & b'1') as attrEx2NotRequireShapeshift,
(attributesEx2 >> 20 & b'1') as attrEx2Unknown20,
(attributesEx2 >> 21 & b'1') as attrEx2Shield,
(attributesEx2 >> 22 & b'1') as attrEx2Unknown22,
(attributesEx2 >> 23 & b'1') as attrEx2Unknown23,
(attributesEx2 >> 24 & b'1') as attrEx2Unknown24,
(attributesEx2 >> 25 & b'1') as attrEx2Unknown25,
(attributesEx2 >> 26 & b'1') as attrEx2Unknown26,
(attributesEx2 >> 27 & b'1') as attrEx2Unknown27,
(attributesEx2 >> 28 & b'1') as attrEx2Unknown28,
(attributesEx2 >> 29 & b'1') as attrEx2Unknown29,
(attributesEx2 >> 30 & b'1') as attrEx2Unknown30,
(attributesEx2 >> 31 & b'1') as attrEx2Unknown31,

-- Attributes Ex3

(attributesEx3 & b'1') as attrEx3Unknown0,
(attributesEx3 >> 1 & b'1') as attrEx3Unknown1,
(attributesEx3 >> 2 & b'1') as attrEx3Unknown2,
(attributesEx3 >> 3 & b'1') as attrEx3Unknown3,
(attributesEx3 >> 4 & b'1') as attrEx3Unknown4,
(attributesEx3 >> 5 & b'1') as attrEx3Unknown5,
(attributesEx3 >> 6 & b'1') as attrEx3Unknown6,
(attributesEx3 >> 7 & b'1') as attrEx3Unknown7,
(attributesEx3 >> 8 & b'1') as attrEx3TargetPlayer,
(attributesEx3 >> 9 & b'1') as attrEx3Unknown9,
(attributesEx3 >> 10 & b'1') as attrEx3RequireMainHand,
(attributesEx3 >> 11 & b'1') as attrEx3RequireBattleground,
(attributesEx3 >> 12 & b'1') as attrEx3RequireTargetDeadPlayer,
(attributesEx3 >> 13 & b'1') as attrEx3Unknown13,
(attributesEx3 >> 14 & b'1') as attrEx3Unknown14,
(attributesEx3 >> 15 & b'1') as attrEx3Unknown15,
(attributesEx3 >> 16 & b'1') as attrEx3Unknown16,
(attributesEx3 >> 17 & b'1') as attrEx3NoAggroOnSuccess,
(attributesEx3 >> 18 & b'1') as attrEx3UnMissable,
(attributesEx3 >> 19 & b'1') as attrEx3Unknown19,
(attributesEx3 >> 20 & b'1') as attrEx3PersistWhileDeath,
(attributesEx3 >> 21 & b'1') as attrEx3Unknown21,
(attributesEx3 >> 22 & b'1') as attrEx3RequireWand,
(attributesEx3 >> 23 & b'1') as attrEx3Unknown23,
(attributesEx3 >> 24 & b'1') as attrEx3RequireOffHand,
(attributesEx3 >> 25 & b'1') as attrEx3Unknown25,
(attributesEx3 >> 26 & b'1') as attrEx3Unknown26,
(attributesEx3 >> 27 & b'1') as attrEx3Unknown27,
(attributesEx3 >> 28 & b'1') as attrEx3Unknown28,
(attributesEx3 >> 29 & b'1') as attrEx3Unknown29,
(attributesEx3 >> 30 & b'1') as attrEx3Unknown30,
(attributesEx3 >> 31 & b'1') as attrEx3Unknown31,

-- Attributes Ex4

(attributesEx4 & b'1') as attrEx4Unknown0,
(attributesEx4 >> 1 & b'1') as attrEx4Unknown1,
(attributesEx4 >> 2 & b'1') as attrEx4Unknown2,
(attributesEx4 >> 3 & b'1') as attrEx4Unknown3,
(attributesEx4 >> 4 & b'1') as attrEx4Unknown4,
(attributesEx4 >> 5 & b'1') as attrEx4Unknown5,
(attributesEx4 >> 6 & b'1') as attrEx4NotStealable,
(attributesEx4 >> 7 & b'1') as attrEx4Unknown7,
(attributesEx4 >> 8 & b'1') as attrEx4StackDotModifier,
(attributesEx4 >> 9 & b'1') as attrEx4Unknown9,
(attributesEx4 >> 10 & b'1') as attrEx4SpellVsExtendCost,
(attributesEx4 >> 11 & b'1') as attrEx4Unknown11,
(attributesEx4 >> 12 & b'1') as attrEx4Unknown12,
(attributesEx4 >> 13 & b'1') as attrEx4Unknown13,
(attributesEx4 >> 14 & b'1') as attrEx4Unknown14,
(attributesEx4 >> 15 & b'1') as attrEx4Unknown15,
(attributesEx4 >> 16 & b'1') as attrEx4NotInArena,
(attributesEx4 >> 17 & b'1') as attrEx4RequireArena,
(attributesEx4 >> 18 & b'1') as attrEx4Unknown18,
(attributesEx4 >> 19 & b'1') as attrEx4Unknown19,
(attributesEx4 >> 20 & b'1') as attrEx4Unknown20,
(attributesEx4 >> 21 & b'1') as attrEx4Unknown21,
(attributesEx4 >> 22 & b'1') as attrEx4Unknown22,
(attributesEx4 >> 23 & b'1') as attrEx4Unknown23,
(attributesEx4 >> 24 & b'1') as attrEx4Unknown24,
(attributesEx4 >> 25 & b'1') as attrEx4Unknown25,
(attributesEx4 >> 26 & b'1') as attrEx4RequireOutland,
(attributesEx4 >> 27 & b'1') as attrEx4Unknown27,
(attributesEx4 >> 28 & b'1') as attrEx4Unknown28,
(attributesEx4 >> 29 & b'1') as attrEx4Unknown29,
(attributesEx4 >> 30 & b'1') as attrEx4Unknown30,
(attributesEx4 >> 31 & b'1') as attrEx4Unknown31,

NULLIF(requiresSpellFocus,0) as fk_spellfocus,
NULLIF(casterAuraState,0) as fk_casterAuraState,
NULLIF(targetAuraState,0) as fk_targetAuraState,
sct.base as spellcasttime,
recoveryTime as recoveryTime,
categoryRecoveryTime as categoryRecoveryTime,
startRecoveryCategory as startRecoveryCategory,
startRecoveryTime as startRecoveryCategoryTime,

-- Interrupt Flags

(interruptFlags & b'1') as interruptMove,
(interruptFlags >> 1 & b'1') as interruptDamage,
(interruptFlags >> 2 & b'1') as interruptInterrupt,
(interruptFlags >> 3 & b'1') as interruptAutoAttack,
(interruptFlags >> 4 & b'1') as interruptAbordOnDamage,

-- Aura Interrupt Flags

(auraInterruptFlags & b'1') as auraInterruptUnknown0,
(auraInterruptFlags >> 1 & b'1') as auraInterruptDamage,
(auraInterruptFlags >> 2 & b'1') as auraInterruptUnknown2,
(auraInterruptFlags >> 3 & b'1') as auraInterruptMove,
(auraInterruptFlags >> 4 & b'1') as auraInterruptTurning,
(auraInterruptFlags >> 5 & b'1') as auraInterruptEntercombat,
(auraInterruptFlags >> 6 & b'1') as auraInterruptUnmounting,
(auraInterruptFlags >> 7 & b'1') as auraInterruptEnterWater,
(auraInterruptFlags >> 8 & b'1') as auraInterruptLeavingWater,
(auraInterruptFlags >> 9 & b'1') as auraInterruptUnsheating,
(auraInterruptFlags >> 10 & b'1') as auraInterruptUnknown10,
(auraInterruptFlags >> 11 & b'1') as auraInterruptUnknown11,
(auraInterruptFlags >> 12 & b'1') as auraInterruptUnknown12,
(auraInterruptFlags >> 13 & b'1') as auraInterruptUnknown13,
(auraInterruptFlags >> 14 & b'1') as auraInterruptUnknown14,
(auraInterruptFlags >> 15 & b'1') as auraInterruptUnknown15,
(auraInterruptFlags >> 16 & b'1') as auraInterruptUnknown16,
(auraInterruptFlags >> 17 & b'1') as auraInterruptMounting,
(auraInterruptFlags >> 18 & b'1') as auraInterruptStandUp,
(auraInterruptFlags >> 19 & b'1') as auraInterruptChangeMap,
(auraInterruptFlags >> 20 & b'1') as auraInterruptImmuneOrLostSelection,
(auraInterruptFlags >> 21 & b'1') as auraInterruptUnknown21,
(auraInterruptFlags >> 22 & b'1') as auraInterruptUnknown22,
(auraInterruptFlags >> 23 & b'1') as auraInterruptEnterPvPCombat,
(auraInterruptFlags >> 24 & b'1') as auraInterruptDirectDamage,

-- Channel Interrupt Flags

(channelInterruptFlags & b'1') as channelInterruptUnknown1,
(channelInterruptFlags >> 1 & b'1') as channelInterruptDamage,
(channelInterruptFlags >> 2 & b'1') as channelInterruptUnknown4,
(channelInterruptFlags >> 3 & b'1') as channelInterruptMove,
(channelInterruptFlags >> 4 & b'1') as channelInterruptTurning,
(channelInterruptFlags >> 5 & b'1') as channelInterruptUnknown7,
(channelInterruptFlags >> 6 & b'1') as channelInterruptDamage2,
(channelInterruptFlags >> 7 & b'1') as channelInterruptUnknown8,
(channelInterruptFlags >> 8 & b'1') as channelInterruptUnknown10,
(channelInterruptFlags >> 9 & b'1') as channelInterruptUnknown11,
(channelInterruptFlags >> 10 & b'1') as channelInterruptUnknown12,
(channelInterruptFlags >> 11 & b'1') as channelInterruptUnknown13,
(channelInterruptFlags >> 12 & b'1') as channelInterruptUnknown14,
(channelInterruptFlags >> 13 & b'1') as channelInterruptDelay,

-- Proc Type Mask

(procTypeMask & b'1') as procOnKilled,
(procTypeMask >> 1 & b'1') as procOnKill,
(procTypeMask >> 2 & b'1') as procOnSuccessMeleeAttackDone,
(procTypeMask >> 3 & b'1') as procOnSuccessMeleeAttackTaken,
(procTypeMask >> 4 & b'1') as procOnSuccessMeleeSpellDone,
(procTypeMask >> 5 & b'1') as procOnSuccessMeleeSpellTaken,
(procTypeMask >> 6 & b'1') as procOnSuccessRangedAttackDone,
(procTypeMask >> 7 & b'1') as procOnSuccessRangedAttackTaken,
(procTypeMask >> 8 & b'1') as procOnSuccessRangedSpellDone,
(procTypeMask >> 9 & b'1') as procOnSuccessRangedSpellTaken,
(procTypeMask >> 10 & b'1') as procOnSuccessPositiveAOEDone,
(procTypeMask >> 11 & b'1') as procOnSuccessPositiveAOETaken,
(procTypeMask >> 12 & b'1') as procOnSuccessAOEDone,
(procTypeMask >> 13 & b'1') as procOnSuccessAOETaken,
(procTypeMask >> 14 & b'1') as procOnSuccessPositiveSpellDone,
(procTypeMask >> 15 & b'1') as procOnSuccessPositiveSpellTaken,
(procTypeMask >> 16 & b'1') as procOnSuccessNegativeSpellDone,
(procTypeMask >> 17 & b'1') as procOnSuccessNegativeSpellTaken,
(procTypeMask >> 18 & b'1') as procOnSuccessDoTSpellDone,
(procTypeMask >> 19 & b'1') as procOnSuccessDoTSpellTaken,
(procTypeMask >> 20 & b'1') as procOnDamageTaken,
(procTypeMask >> 21 & b'1') as procOnTrapActivation,
(procTypeMask >> 22 & b'1') as procOnSuccessMeleeOffHandTaken,
(procTypeMask >> 23 & b'1') as procOnSuccessMeleeOffHandDone,
(procTypeMask >> 24 & b'1') as procOnRequireOffHand,

-- Proc Ex is an internal system of Mangos.

0 as procExOnNormalHit,
0 as procExOnCriticalHit,
0 as procExOnMiss,
0 as procExOnResist,
0 as procExOnDodge,
0 as procExOnParry,
0 as procExOnBlock,
0 as procExOnEvade,
0 as procExOnImmune,
0 as procExOnDeflect,
0 as procExOnAbsorb,
0 as procExOnReflect,
0 as procExOnInterrupt,
0 as procExReserved1,
0 as procExReserved2,
0 as procExReserved3,
0 as procExAlwaysTrigger,
0 as procExOneTimeTrigger,
0 as procExPeriodicPositive,

procChance as procChance,
procCharges as procCharges,
maxLevel as maxLevel,
baseLevel as baseLevel,
spellLevel as spellLevel,
maxTargetLevel as maxTargetLevel,
maxTargets as maxTargets,
NULLIF(durationIndex,0) as fk_spellduration,
powerType as fk_power,
manaCost as cost,
manaCostPct as costPct,
manaCostPerLevel as costPerLevel,
manaCostPerSecond as costPerSecond,
manaCostPerSecondPerLevel as costPerSecondPerLevel,
NULLIF(rangeIndex,0) as fk_spellrange,
speed as speed,
NULLIF(modalNextSpell,0) as fk_modalNextSpell,
stackAmount as stackAmount,
spellVisualID1 as spellVisualID1,
spellVisualID2 as spellVisualID2,
spellIconID as spellIconID,
activeIconID as activeIconID,
spellPriority as spellPriority,
name as name,
`name1`,
`name2`,
`name3`,
`name4`,
`name5`,
`name6`,
`name7`,
`nameSubText`,
`nameSubText1`,
`nameSubText2`,
`nameSubText3`,
`nameSubText4`,
`nameSubText5`,
`nameSubText6`,
`nameSubText7`,
`description`,
`description1`,
`description2`,
`description3`,
`description4`,
`description5`,
`description6`,
`description7`,
`auraDescription`,
`auraDescription1`,
`auraDescription2`,
`auraDescription3`,
`auraDescription4`,
`auraDescription5`,
`auraDescription6`,
`auraDescription7`,
NULLIF(spellClassSet,0) as fk_spellFamily,

(spellClassMask2 << 32) + spellClassMask1  as spellFamilyFlags,
NULLIF(defenseType,0) as fk_damageType,
NULLIF(preventionType,0) as fk_preventionType,
stanceBarOrder as stanceBarOrder

FROM dbc.dbc0_spell as s
LEFT JOIN dbc.dbc0_spellcasttimes as sct
ON s.castingTimeIndex = sct.id