CREATE TABLE jangosworld.`spells` (
  `spellID` int(11) UNSIGNED DEFAULT '0',
  `fk_school` TINYINT(3) NOT NULL DEFAULT '0',
  `category` int(11) NOT NULL DEFAULT '0',
  `castUI` int(11) NOT NULL DEFAULT '0',
  fk_dispelType TINYINT(2) DEFAULT NULL,
  fk_mechanic TINYINT(2) DEFAULT NULL,
  attrUnknown0 TINYINT(1) NOT NULL DEFAULT '0',
  attrRanged TINYINT(1) NOT NULL DEFAULT '0',
  attrOnNextSwing TINYINT(1) NOT NULL DEFAULT '0',
  attrUnknown3 TINYINT(1) NOT NULL DEFAULT '0',
  attrUnknown4 TINYINT(1) NOT NULL DEFAULT '0',
  attrTrade TINYINT(1) NOT NULL DEFAULT '0',
  attrPassive TINYINT(1) NOT NULL DEFAULT '0',
  attrHide TINYINT(1) NOT NULL DEFAULT '0',
  attrUnknown8 TINYINT(1) NOT NULL DEFAULT '0',
  attrUnknown9 TINYINT(1) NOT NULL DEFAULT '0',
  attrOnNextSwing2 TINYINT(1) NOT NULL DEFAULT '0',
  attrUnknown11 TINYINT(1) NOT NULL DEFAULT '0',
  attrDayOnly TINYINT(1) NOT NULL DEFAULT '0',
  attrNightOnly TINYINT(1) NOT NULL DEFAULT '0',
  attrIndoorsOnly TINYINT(1) NOT NULL DEFAULT '0',
  attrOutdoorsOnly TINYINT(1) NOT NULL DEFAULT '0',
  attrNotShapeshift TINYINT(1) NOT NULL DEFAULT '0',
  attrOnlyStealthed TINYINT(1) NOT NULL DEFAULT '0',
  attrUnknown18 TINYINT(1) NOT NULL DEFAULT '0',
  attrLevelDamageCalc TINYINT(1) NOT NULL DEFAULT '0',
  attrStopAttack TINYINT(1) NOT NULL DEFAULT '0',
  attrNotAvoidable TINYINT(1) NOT NULL DEFAULT '0',
  attrTrackTarget TINYINT(1) NOT NULL DEFAULT '0',
  attrUnknown23 TINYINT(1) NOT NULL DEFAULT '0',
  attrCastOnMount TINYINT(1) NOT NULL DEFAULT '0',
  attrDisabledWhileActive TINYINT(1) NOT NULL DEFAULT '0',
  attrUnknown26 TINYINT(1) NOT NULL DEFAULT '0',
  attrCastSit TINYINT(1) NOT NULL DEFAULT '0',
  attrNotInCombat TINYINT(1) NOT NULL DEFAULT '0',
  attrUnaffectedByInvuln TINYINT(1) NOT NULL DEFAULT '0',
  attrUnknown30 TINYINT(1) NOT NULL DEFAULT '0',
  attrNotCancellable TINYINT(1) NOT NULL DEFAULT '0',  
  attrExUnknown0 TINYINT(1) NOT NULL DEFAULT '0',
  attrExDrainAllPower TINYINT(1) NOT NULL DEFAULT '0',
  attrExChanneled TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown3 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown4 TINYINT(1) NOT NULL DEFAULT '0',
  attrExRemainStealth TINYINT(1) NOT NULL DEFAULT '0',
  attrExChanneled2 TINYINT(1) NOT NULL DEFAULT '0',
  attrExNegative TINYINT(1) NOT NULL DEFAULT '0',
  attrExTargetNotInCombat TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown9 TINYINT(1) NOT NULL DEFAULT '0',
  attrExNoThreat TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown11 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown12 TINYINT(1) NOT NULL DEFAULT '0',
  attrExFarSight TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown14 TINYINT(1) NOT NULL DEFAULT '0',
  attrExRemoveAurasOnImmune TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnaffectedBySchoolImmune TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown17 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown18 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown19 TINYINT(1) NOT NULL DEFAULT '0',
  attrExTargetComboPoints TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown21 TINYINT(1) NOT NULL DEFAULT '0',
  attrExRequireComboPoints TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown23 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown24 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown25 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown26 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown27 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown28 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown29 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown30 TINYINT(1) NOT NULL DEFAULT '0',
  attrExUnknown31 TINYINT(1) NOT NULL DEFAULT '0',  
  attrEx2Unknown0 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown1 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2CantReflect TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown3 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown4 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2AutoRepeat TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown6 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown7 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown8 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown9 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown10 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2HealthFunnel TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown12 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown13 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown14 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown15 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown16 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown17 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown18 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2NotRequireShapeshift TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown20 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Shield TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown22 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown23 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown24 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown25 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown26 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown27 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown28 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown29 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown30 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx2Unknown31 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown0 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown1 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown2 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown3 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown4 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown5 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown6 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown7 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3TargetPlayer TINYINT(1) NOT NULL DEFAULT '0',  
  attrEx3Unknown9 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3RequireMainHand TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3RequireBattleground TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3RequireTargetDeadPlayer TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown13 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown14 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown15 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown16 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3NoAggroOnSuccess TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3UnMissable TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown19 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3PersistWhileDeath TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown21 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3RequireWand TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown23 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3RequireOffHand TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown25 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown26 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown27 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown28 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown29 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown30 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx3Unknown31 TINYINT(1) NOT NULL DEFAULT '0',    
  attrEx4Unknown0 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown1 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown2 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown3 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown4 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown5 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4NotStealable TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown7 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4StackDotModifier TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown9 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4SpellVsExtendCost TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown11 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown12 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown13 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown14 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown15 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4NotInArena TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4RequireArena TINYINT(1) NOT NULL DEFAULT '0',  
  attrEx4Unknown18 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown19 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown20 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown21 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown22 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown23 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown24 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown25 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4RequireOutland TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown27 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown28 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown29 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown30 TINYINT(1) NOT NULL DEFAULT '0',
  attrEx4Unknown31 TINYINT(1) NOT NULL DEFAULT '0',    
  fk_spellfocus int(11) UNSIGNED DEFAULT NULL,
  fk_casterAuraState TINYINT(2) DEFAULT NULL,
  fk_targetAuraState TINYINT(2) DEFAULT NULL,
  spellcasttime INT(11) UNSIGNED DEFAULT '0',
  recoveryTime int(11) NOT NULL DEFAULT '0',
  categoryRecoveryTime int(11) NOT NULL DEFAULT '0',
  `startRecoveryCategory` int(11) NOT NULL DEFAULT '0',
  `startRecoveryCategoryTime` int(11) NOT NULL DEFAULT '0',
  interruptMove TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  interruptDamage TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  interruptInterrupt TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  interruptAutoAttack TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  interruptAbordOnDamage TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown0 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptDamage TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown2 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptMove TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptTurning TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptEnterCombat TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnmounting TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptEnterWater TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptLeavingWater TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnsheathing TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown10 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown11 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown12 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown13 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown14 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown15 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown16 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptMounting TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptStandUp TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptChangeMap TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptImmuneOrLostSelection TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown21 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptUnknown22 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptEnterPvPCombat TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  auraInterruptDirectDamage TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',  
  channelInterruptUnknown1 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptDamage TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptUnknown4 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptMove TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',  
  channelInterruptTurning TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',  
  channelInterruptUnknown7 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptUnknown8 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptDamage2 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptUnknown10 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptUnknown11 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptUnknown12 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptUnknown13 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptUnknown14 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptUnknown15 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  channelInterruptDelay TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',  
  procTypeMask INT(11) UNSIGNED NOT NULL DEFAULT '0',
  procOnKilled TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnKill TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessMeleeAttackDone TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessMeleeAttackTaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessMeleeSpellDone TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessMeleeSpellTaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessRangedAttackDone TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessRangedAttackTaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessRangedSpellDone TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessRangedSpellTaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessPositiveAOEDone TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessPositiveAOETaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessAOEDone TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessAOETaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessPositiveSpellDone TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessPositiveSpellTaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessNegativeSpellDone TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessNegativeSpellTaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessDoTSpellDone TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessDoTSpellTaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnDamageTaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnTrapActivation TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessMeleeOffHandTaken TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procOnSuccessMeleeOffHandDone TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnNormalHit TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnCriticalHit TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnMiss TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnResist TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnDodge TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnParry TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnBlock TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnEvade TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnImmune TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnDeflect TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnAbsorb  TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnReflect TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOnInterrupt TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExReserved1 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExReserved2 TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExReserved3  TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExAlwaysTrigger TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExOneTimeTrigger TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procExPeriodicPositive TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  procChance SMALLINT NOT NULL DEFAULT '0',  
  `procCharges` SMALLINT NOT NULL DEFAULT '0',  
  `maxLevel` SMALLINT NOT NULL DEFAULT '0',
  `baseLevel` SMALLINT NOT NULL DEFAULT '0',
  `spellLevel` SMALLINT NOT NULL DEFAULT '0',  
  `maxTargetLevel` SMALLINT NOT NULL DEFAULT '0',
  `maxTargets` SMALLINT NOT NULL DEFAULT '0',
  fk_spellduration SMALLINT DEFAULT NULL,  
  fk_power TINYINT(2) NOT NULL DEFAULT '0',  
  `cost` int(11) NOT NULL DEFAULT '0',
  `costPct` int(11) NOT NULL DEFAULT '0',
  `costPerLevel` TINYINT(11) NOT NULL DEFAULT '0',
  `costPerSecond` TINYINT(11) NOT NULL DEFAULT '0',
  `costPerSecondPerLevel` TINYINT(11) NOT NULL DEFAULT '0',
  fk_spellrange TINYINT(1) DEFAULT NULL,
  `speed` TINYINT(2) NOT NULL DEFAULT '0',
  fk_modalNextSpell int(11) UNSIGNED DEFAULT NULL,    
  `stackAmount` int(11) NOT NULL DEFAULT '0',    
  `spellVisualID1` int(11) UNSIGNED NOT NULL DEFAULT'0',
  `spellVisualID2` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `spellIconID` int(11) NOT NULL DEFAULT '0',
  `activeIconID` int(11) NOT NULL DEFAULT '0',
  `spellPriority` int(11) NOT NULL DEFAULT '0',  
  `name` text NOT NULL,
  `name1` text NOT NULL,
  `name2` text NOT NULL,
  `name3` text NOT NULL,
  `name4` text NOT NULL,
  `name5` text NOT NULL,
  `name6` text NOT NULL,
  `name7` text NOT NULL,
  `nameSubText` text NOT NULL,
  `nameSubText1` text NOT NULL,
  `nameSubText2` text NOT NULL,
  `nameSubText3` text NOT NULL,
  `nameSubText4` text NOT NULL,
  `nameSubText5` text NOT NULL,
  `nameSubText6` text NOT NULL,
  `nameSubText7` text NOT NULL,
  `description` text NOT NULL,
  `description1` text NOT NULL,
  `description2` text NOT NULL,
  `description3` text NOT NULL,
  `description4` text NOT NULL,
  `description5` text NOT NULL,
  `description6` text NOT NULL,
  `description7` text NOT NULL,
  `auraDescription` text NOT NULL,
  `auraDescription1` text NOT NULL,
  `auraDescription2` text NOT NULL,
  `auraDescription3` text NOT NULL,
  `auraDescription4` text NOT NULL,
  `auraDescription5` text NOT NULL,
  `auraDescription6` text NOT NULL,
  `auraDescription7` text NOT NULL,        
  `spellFamily` TINYINT(2) NOT NULL DEFAULT '0',
  `spellFamilyFlags` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  fk_damageType TINYINT(2) DEFAULT NULL,  
  fk_preventionType tinyint(2) DEFAULT NULL,
  `stanceBarOrder` TINYINT(2) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='This table holds all the spell data of the game';
