package eu.jangos.realm.model.auth;

import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer id;
     private Locale locale;
     private Realm realm;
     private String name;
     private String hashPass;
     private String sessionkey;
     private String verifier;
     private String salt;
     private String email;
     private Date creation;
     private String lastIp;
     private int failedattempt;
     private boolean locked;
     private Date lastlogin;
     private boolean online;
     private Set bannedaccountsForFkBannedby = new HashSet(0);
     private Set roleses = new HashSet(0);
     private Set bannedips = new HashSet(0);
     private Set bannedaccountsForFkBannedaccount = new HashSet(0);
     private Set realmAccounts = new HashSet(0);

    public Account() {
    }

	
    public Account(String name, String hashPass, Date creation, String lastIp, int failedattempt, boolean locked, Date lastlogin, boolean online) {
        this.name = name;
        this.hashPass = hashPass;
        this.creation = creation;
        this.lastIp = lastIp;
        this.failedattempt = failedattempt;
        this.locked = locked;
        this.lastlogin = lastlogin;
        this.online = online;
    }
    public Account(Locale locale, Realm realm, String name, String hashPass, String sessionkey, String verifier, String salt, String email, Date creation, String lastIp, int failedattempt, boolean locked, Date lastlogin, boolean online, Set bannedaccountsForFkBannedby, Set roleses, Set bannedips, Set bannedaccountsForFkBannedaccount, Set realmAccounts) {
       this.locale = locale;
       this.realm = realm;
       this.name = name;
       this.hashPass = hashPass;
       this.sessionkey = sessionkey;
       this.verifier = verifier;
       this.salt = salt;
       this.email = email;
       this.creation = creation;
       this.lastIp = lastIp;
       this.failedattempt = failedattempt;
       this.locked = locked;
       this.lastlogin = lastlogin;
       this.online = online;
       this.bannedaccountsForFkBannedby = bannedaccountsForFkBannedby;
       this.roleses = roleses;
       this.bannedips = bannedips;
       this.bannedaccountsForFkBannedaccount = bannedaccountsForFkBannedaccount;
       this.realmAccounts = realmAccounts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Locale getLocale() {
        return this.locale;
    }
    
    public void setLocale(Locale locale) {
        this.locale = locale;
    }
    public Realm getRealm() {
        return this.realm;
    }
    
    public void setRealm(Realm realm) {
        this.realm = realm;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getHashPass() {
        return this.hashPass;
    }
    
    public void setHashPass(String hashPass) {
        this.hashPass = hashPass;
    }
    public String getSessionkey() {
        return this.sessionkey;
    }
    
    public void setSessionkey(String sessionkey) {
        this.sessionkey = sessionkey;
    }
    public String getVerifier() {
        return this.verifier;
    }
    
    public void setVerifier(String verifier) {
        this.verifier = verifier;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public String getLastIp() {
        return this.lastIp;
    }
    
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp;
    }
    public int getFailedattempt() {
        return this.failedattempt;
    }
    
    public void setFailedattempt(int failedattempt) {
        this.failedattempt = failedattempt;
    }
    public boolean isLocked() {
        return this.locked;
    }
    
    public void setLocked(boolean locked) {
        this.locked = locked;
    }
    public Date getLastlogin() {
        return this.lastlogin;
    }
    
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }
    public boolean isOnline() {
        return this.online;
    }
    
    public void setOnline(boolean online) {
        this.online = online;
    }
    public Set getBannedaccountsForFkBannedby() {
        return this.bannedaccountsForFkBannedby;
    }
    
    public void setBannedaccountsForFkBannedby(Set bannedaccountsForFkBannedby) {
        this.bannedaccountsForFkBannedby = bannedaccountsForFkBannedby;
    }
    public Set getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set roleses) {
        this.roleses = roleses;
    }
    public Set getBannedips() {
        return this.bannedips;
    }
    
    public void setBannedips(Set bannedips) {
        this.bannedips = bannedips;
    }
    public Set getBannedaccountsForFkBannedaccount() {
        return this.bannedaccountsForFkBannedaccount;
    }
    
    public void setBannedaccountsForFkBannedaccount(Set bannedaccountsForFkBannedaccount) {
        this.bannedaccountsForFkBannedaccount = bannedaccountsForFkBannedaccount;
    }
    public Set getRealmAccounts() {
        return this.realmAccounts;
    }
    
    public void setRealmAccounts(Set realmAccounts) {
        this.realmAccounts = realmAccounts;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + Objects.hashCode(this.id);
        hash = 17 * hash + Objects.hashCode(this.locale);
        hash = 17 * hash + Objects.hashCode(this.realm);
        hash = 17 * hash + Objects.hashCode(this.name);
        hash = 17 * hash + Objects.hashCode(this.hashPass);
        hash = 17 * hash + Objects.hashCode(this.sessionkey);
        hash = 17 * hash + Objects.hashCode(this.verifier);
        hash = 17 * hash + Objects.hashCode(this.salt);
        hash = 17 * hash + Objects.hashCode(this.email);
        hash = 17 * hash + Objects.hashCode(this.creation);
        hash = 17 * hash + Objects.hashCode(this.lastIp);
        hash = 17 * hash + this.failedattempt;
        hash = 17 * hash + (this.locked ? 1 : 0);
        hash = 17 * hash + Objects.hashCode(this.lastlogin);
        hash = 17 * hash + (this.online ? 1 : 0);
        hash = 17 * hash + Objects.hashCode(this.bannedaccountsForFkBannedby);
        hash = 17 * hash + Objects.hashCode(this.roleses);
        hash = 17 * hash + Objects.hashCode(this.bannedips);
        hash = 17 * hash + Objects.hashCode(this.bannedaccountsForFkBannedaccount);
        hash = 17 * hash + Objects.hashCode(this.realmAccounts);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Account other = (Account) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }



}


