package eu.jangos.realm.model.auth;

import java.util.Date;
import java.util.Objects;

/**
 * Bannedip generated by hbm2java
 */
public class Bannedip  implements java.io.Serializable {


     private Integer id;
     private Account account;
     private String ip;
     private Date date;
     private Date unban;
     private String reason;
     private boolean active;

    public Bannedip() {
    }

	
    public Bannedip(Account account, String ip, Date date, String reason, boolean active) {
        this.account = account;
        this.ip = ip;
        this.date = date;
        this.reason = reason;
        this.active = active;
    }
    public Bannedip(Account account, String ip, Date date, Date unban, String reason, boolean active) {
       this.account = account;
       this.ip = ip;
       this.date = date;
       this.unban = unban;
       this.reason = reason;
       this.active = active;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getUnban() {
        return this.unban;
    }
    
    public void setUnban(Date unban) {
        this.unban = unban;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 97 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Bannedip other = (Bannedip) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }




}


