package eu.jangos.realm.model.auth;

import eu.jangos.realm.utils.WorldParameterConstants;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Commands generated by hbm2java
 */
public class Commands  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set roleses = new HashSet(0);

    public Commands() {
    }

	
    public Commands(String name, String description) {
        this.name = name;
        this.description = description;
    }
    public Commands(String name, String description, Set roleses) {
       this.name = name;
       this.description = description;
       this.roleses = roleses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set roleses) {
        this.roleses = roleses;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 19 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Commands other = (Commands) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return this.name.split(WorldParameterConstants.COMMAND_SEPARATOR)[this.name.split(WorldParameterConstants.COMMAND_SEPARATOR).length-1];
    }

}


