package eu.jangos.realm.model.auth;
// Generated 06-mai-2016 21:16:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Locale generated by hbm2java
 */
@Entity
@Table(name="locale"
    ,catalog="jangosauth"
)
public class Locale  implements java.io.Serializable {


     private int id;
     private Set<Account> accounts = new HashSet<Account>(0);
     private String locale;
     private String localeString;

    public Locale() {
    }

	
    public Locale(int id, String locale, String localeString) {
        this.id = id;
        this.locale = locale;
        this.localeString = localeString;
    }
    public Locale(int id, Set<Account> accounts, String locale, String localeString) {
       this.id = id;
       this.accounts = accounts;
       this.locale = locale;
       this.localeString = localeString;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="locale")
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }

    
    @Column(name="locale", nullable=false, length=30)
    public String getLocale() {
        return this.locale;
    }
    
    public void setLocale(String locale) {
        this.locale = locale;
    }

    
    @Column(name="localeString", nullable=false, length=45)
    public String getLocaleString() {
        return this.localeString;
    }
    
    public void setLocaleString(String localeString) {
        this.localeString = localeString;
    }




}


