package eu.jangos.realm.model.auth;
// Generated 06-mai-2016 21:16:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Realm generated by hbm2java
 */
@Entity
@Table(name="realm"
    ,catalog="jangosauth"
)
public class Realm  implements java.io.Serializable {


     private Integer id;
     private Set<Account> accounts = new HashSet<Account>(0);
     private String address;
     private int countPlayers;
     private boolean invalid;
     private int maxPlayers;
     private String name;
     private boolean newplayers;
     private boolean offline;
     private float population;
     private int port;
     private Set<RealmAccount> realmAccounts = new HashSet<RealmAccount>(0);
     private Realmtimezone realmtimezone;
     private Realmtype realmtype;
     private boolean recommended;
     private boolean showversion;

    public Realm() {
    }

	
    public Realm(String address, int countPlayers, boolean invalid, int maxPlayers, String name, boolean newplayers, boolean offline, float population, int port, Realmtimezone realmtimezone, Realmtype realmtype, boolean recommended, boolean showversion) {
        this.address = address;
        this.countPlayers = countPlayers;
        this.invalid = invalid;
        this.maxPlayers = maxPlayers;
        this.name = name;
        this.newplayers = newplayers;
        this.offline = offline;
        this.population = population;
        this.port = port;
        this.realmtimezone = realmtimezone;
        this.realmtype = realmtype;
        this.recommended = recommended;
        this.showversion = showversion;
    }
    public Realm(Set<Account> accounts, String address, int countPlayers, boolean invalid, int maxPlayers, String name, boolean newplayers, boolean offline, float population, int port, Set<RealmAccount> realmAccounts, Realmtimezone realmtimezone, Realmtype realmtype, boolean recommended, boolean showversion) {
       this.accounts = accounts;
       this.address = address;
       this.countPlayers = countPlayers;
       this.invalid = invalid;
       this.maxPlayers = maxPlayers;
       this.name = name;
       this.newplayers = newplayers;
       this.offline = offline;
       this.population = population;
       this.port = port;
       this.realmAccounts = realmAccounts;
       this.realmtimezone = realmtimezone;
       this.realmtype = realmtype;
       this.recommended = recommended;
       this.showversion = showversion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="realm")
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }

    
    @Column(name="address", nullable=false, length=32)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="countPlayers", nullable=false)
    public int getCountPlayers() {
        return this.countPlayers;
    }
    
    public void setCountPlayers(int countPlayers) {
        this.countPlayers = countPlayers;
    }

    
    @Column(name="invalid", nullable=false)
    public boolean isInvalid() {
        return this.invalid;
    }
    
    public void setInvalid(boolean invalid) {
        this.invalid = invalid;
    }

    
    @Column(name="maxPlayers", nullable=false)
    public int getMaxPlayers() {
        return this.maxPlayers;
    }
    
    public void setMaxPlayers(int maxPlayers) {
        this.maxPlayers = maxPlayers;
    }

    
    @Column(name="name", nullable=false, length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="newplayers", nullable=false)
    public boolean isNewplayers() {
        return this.newplayers;
    }
    
    public void setNewplayers(boolean newplayers) {
        this.newplayers = newplayers;
    }

    
    @Column(name="offline", nullable=false)
    public boolean isOffline() {
        return this.offline;
    }
    
    public void setOffline(boolean offline) {
        this.offline = offline;
    }

    
    @Column(name="population", nullable=false, precision=12, scale=0)
    public float getPopulation() {
        return this.population;
    }
    
    public void setPopulation(float population) {
        this.population = population;
    }

    
    @Column(name="port", nullable=false)
    public int getPort() {
        return this.port;
    }
    
    public void setPort(int port) {
        this.port = port;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="realm")
    public Set<RealmAccount> getRealmAccounts() {
        return this.realmAccounts;
    }
    
    public void setRealmAccounts(Set<RealmAccount> realmAccounts) {
        this.realmAccounts = realmAccounts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_timezone", nullable=false)
    public Realmtimezone getRealmtimezone() {
        return this.realmtimezone;
    }
    
    public void setRealmtimezone(Realmtimezone realmtimezone) {
        this.realmtimezone = realmtimezone;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_realmtype", nullable=false)
    public Realmtype getRealmtype() {
        return this.realmtype;
    }
    
    public void setRealmtype(Realmtype realmtype) {
        this.realmtype = realmtype;
    }

    
    @Column(name="recommended", nullable=false)
    public boolean isRecommended() {
        return this.recommended;
    }
    
    public void setRecommended(boolean recommended) {
        this.recommended = recommended;
    }

    
    @Column(name="showversion", nullable=false)
    public boolean isShowversion() {
        return this.showversion;
    }
    
    public void setShowversion(boolean showversion) {
        this.showversion = showversion;
    }




}


