package eu.jangos.realm.model.auth;
// Generated 06-mai-2016 21:16:44 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RealmAccount generated by hbm2java
 */
@Entity
@Table(name="realm_account"
    ,catalog="jangosauth"
)
public class RealmAccount  implements java.io.Serializable {


     private RealmAccountId id;
     private Account account;
     private byte numChars;
     private Realm realm;

    public RealmAccount() {
    }

    public RealmAccount(RealmAccountId id, Account account, byte numChars, Realm realm) {
       this.id = id;
       this.account = account;
       this.numChars = numChars;
       this.realm = realm;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkAccount", column=@Column(name="fk_account", nullable=false) ), 
        @AttributeOverride(name="fkRealm", column=@Column(name="fk_realm", nullable=false) ) } )
    public RealmAccountId getId() {
        return this.id;
    }
    
    public void setId(RealmAccountId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_account", nullable=false, insertable=false, updatable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

    
    @Column(name="numChars", nullable=false)
    public byte getNumChars() {
        return this.numChars;
    }
    
    public void setNumChars(byte numChars) {
        this.numChars = numChars;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_realm", nullable=false, insertable=false, updatable=false)
    public Realm getRealm() {
        return this.realm;
    }
    
    public void setRealm(Realm realm) {
        this.realm = realm;
    }




}


