package eu.jangos.realm.model.auth;

import java.util.HashSet;
import java.util.Set;

/**
 * Realmtimezone generated by hbm2java
 */
public class Realmtimezone  implements java.io.Serializable {


     private int id;
     private String name;
     private Set realms = new HashSet(0);

    public Realmtimezone() {
    }

	
    public Realmtimezone(int id) {
        this.id = id;
    }
    public Realmtimezone(int id, String name, Set realms) {
       this.id = id;
       this.name = name;
       this.realms = realms;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getRealms() {
        return this.realms;
    }
    
    public void setRealms(Set realms) {
        this.realms = realms;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + this.id;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Realmtimezone other = (Realmtimezone) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }




}


