package eu.jangos.realm.model.auth;

import java.util.Objects;

/**
 * RealmAccount generated by hbm2java
 */
public class RealmAccount  implements java.io.Serializable {


     private RealmAccountId id;
     private Account account;
     private Realm realm;
     private byte numChars;

    public RealmAccount() {
    }

    public RealmAccount(RealmAccountId id, Account account, Realm realm, byte numChars) {
       this.id = id;
       this.account = account;
       this.realm = realm;
       this.numChars = numChars;
    }
   
    public RealmAccountId getId() {
        return this.id;
    }
    
    public void setId(RealmAccountId id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Realm getRealm() {
        return this.realm;
    }
    
    public void setRealm(Realm realm) {
        this.realm = realm;
    }
    public byte getNumChars() {
        return this.numChars;
    }
    
    public void setNumChars(byte numChars) {
        this.numChars = numChars;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 53 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RealmAccount other = (RealmAccount) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }




}


