package eu.jangos.realm.model.auth;
// Generated 06-mai-2016 21:16:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Realmtimezone generated by hbm2java
 */
@Entity
@Table(name="realmtimezone"
    ,catalog="jangosauth"
)
public class Realmtimezone  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Realm> realms = new HashSet<Realm>(0);

    public Realmtimezone() {
    }

	
    public Realmtimezone(int id) {
        this.id = id;
    }
    public Realmtimezone(int id, String name, Set<Realm> realms) {
       this.id = id;
       this.name = name;
       this.realms = realms;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="realmtimezone")
    public Set<Realm> getRealms() {
        return this.realms;
    }
    
    public void setRealms(Set<Realm> realms) {
        this.realms = realms;
    }




}


