package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Creaturetype generated by hbm2java
 */
@Entity
@Table(name="creaturetype"
    ,catalog="jangosworld"
)
public class Creaturetype  implements java.io.Serializable {


     private byte id;
     private String type;
     private Set<Spells> spellses = new HashSet<Spells>(0);

    public Creaturetype() {
    }

	
    public Creaturetype(byte id, String type) {
        this.id = id;
        this.type = type;
    }
    public Creaturetype(byte id, String type, Set<Spells> spellses) {
       this.id = id;
       this.type = type;
       this.spellses = spellses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false, length=30)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="spellcreaturetype", catalog="jangosworld", joinColumns = { 
        @JoinColumn(name="fk_creaturetype", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="fk_spell", nullable=false, updatable=false) })
    public Set<Spells> getSpellses() {
        return this.spellses;
    }
    
    public void setSpellses(Set<Spells> spellses) {
        this.spellses = spellses;
    }




}


