package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dispeltype generated by hbm2java
 */
@Entity
@Table(name="dispeltype"
    ,catalog="jangosworld"
)
public class Dispeltype  implements java.io.Serializable {


     private byte id;
     private String dispel;
     private Set<Spells> spellses = new HashSet<Spells>(0);

    public Dispeltype() {
    }

	
    public Dispeltype(byte id, String dispel) {
        this.id = id;
        this.dispel = dispel;
    }
    public Dispeltype(byte id, String dispel, Set<Spells> spellses) {
       this.id = id;
       this.dispel = dispel;
       this.spellses = spellses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="dispel", nullable=false, length=45)
    public String getDispel() {
        return this.dispel;
    }
    
    public void setDispel(String dispel) {
        this.dispel = dispel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dispeltype")
    public Set<Spells> getSpellses() {
        return this.spellses;
    }
    
    public void setSpellses(Set<Spells> spellses) {
        this.spellses = spellses;
    }




}


