package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gender generated by hbm2java
 */
@Entity
@Table(name="gender"
    ,catalog="jangosworld"
)
public class Gender  implements java.io.Serializable {


     private byte id;
     private String gender;
     private Set<Startingequipment> startingequipments = new HashSet<Startingequipment>(0);

    public Gender() {
    }

	
    public Gender(byte id, String gender) {
        this.id = id;
        this.gender = gender;
    }
    public Gender(byte id, String gender, Set<Startingequipment> startingequipments) {
       this.id = id;
       this.gender = gender;
       this.startingequipments = startingequipments;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="gender", nullable=false, length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gender")
    public Set<Startingequipment> getStartingequipments() {
        return this.startingequipments;
    }
    
    public void setStartingequipments(Set<Startingequipment> startingequipments) {
        this.startingequipments = startingequipments;
    }




}


