package eu.jangos.realm.model.world;
// Generated 27-févr.-2016 16:07:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Inventorytype generated by hbm2java
 */
public class Inventorytype  implements java.io.Serializable {


     private byte id;
     private String type;
     private Set items = new HashSet(0);

    public Inventorytype() {
    }

	
    public Inventorytype(byte id, String type) {
        this.id = id;
        this.type = type;
    }
    public Inventorytype(byte id, String type, Set items) {
       this.id = id;
       this.type = type;
       this.items = items;
    }
   
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


