package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Itemclass generated by hbm2java
 */
@Entity
@Table(name="itemclass"
    ,catalog="jangosworld"
)
public class Itemclass  implements java.io.Serializable {


     private byte id;
     private String itemclass;
     private Set<Itemsubclass> itemsubclasses = new HashSet<Itemsubclass>(0);

    public Itemclass() {
    }

	
    public Itemclass(byte id) {
        this.id = id;
    }
    public Itemclass(byte id, String itemclass, Set<Itemsubclass> itemsubclasses) {
       this.id = id;
       this.itemclass = itemclass;
       this.itemsubclasses = itemsubclasses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="itemclass", length=20)
    public String getItemclass() {
        return this.itemclass;
    }
    
    public void setItemclass(String itemclass) {
        this.itemclass = itemclass;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemclass")
    public Set<Itemsubclass> getItemsubclasses() {
        return this.itemsubclasses;
    }
    
    public void setItemsubclasses(Set<Itemsubclass> itemsubclasses) {
        this.itemsubclasses = itemsubclasses;
    }




}


