package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Itemquality generated by hbm2java
 */
@Entity
@Table(name="itemquality"
    ,catalog="jangosworld"
)
public class Itemquality  implements java.io.Serializable {


     private byte id;
     private String quality;
     private Set<Item> items = new HashSet<Item>(0);

    public Itemquality() {
    }

	
    public Itemquality(byte id, String quality) {
        this.id = id;
        this.quality = quality;
    }
    public Itemquality(byte id, String quality, Set<Item> items) {
       this.id = id;
       this.quality = quality;
       this.items = items;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="quality", nullable=false, length=15)
    public String getQuality() {
        return this.quality;
    }
    
    public void setQuality(String quality) {
        this.quality = quality;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemquality")
    public Set<Item> getItems() {
        return this.items;
    }
    
    public void setItems(Set<Item> items) {
        this.items = items;
    }




}


