package eu.jangos.realm.model.world;
// Generated 27-févr.-2016 16:07:33 by Hibernate Tools 4.3.1



/**
 * ItemsubclassId generated by hbm2java
 */
public class ItemsubclassId  implements java.io.Serializable {


     private byte fkItemclass;
     private byte id;

    public ItemsubclassId() {
    }

    public ItemsubclassId(byte fkItemclass, byte id) {
       this.fkItemclass = fkItemclass;
       this.id = id;
    }
   
    public byte getFkItemclass() {
        return this.fkItemclass;
    }
    
    public void setFkItemclass(byte fkItemclass) {
        this.fkItemclass = fkItemclass;
    }
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }




}


