package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item"
    ,catalog="jangosworld"
)
public class Item  implements java.io.Serializable {


     private int entry;
     private Inventorytype inventorytype;
     private Itemquality itemquality;
     private Itemsubclass itemsubclass;
     private Pagetext pagetext;
     private String name;
     private int displayid;
     private int flags;
     private short buycount;
     private int buyprice;
     private int sellprice;
     private int allowableclass;
     private int allowablerace;
     private byte itemlevel;
     private byte requiredlevel;
     private short requiredskill;
     private short requiredskillrank;
     private int requiredspell;
     private int requiredhonorrank;
     private int requiredcityrank;
     private short requiredreputationfaction;
     private short requiredreputationrank;
     private short maxcount;
     private short stackable;
     private byte containerslots;
     private byte statType1;
     private short statValue1;
     private byte statType2;
     private short statValue2;
     private byte statType3;
     private short statValue3;
     private byte statType4;
     private short statValue4;
     private byte statType5;
     private short statValue5;
     private byte statType6;
     private short statValue6;
     private byte statType7;
     private short statValue7;
     private byte statType8;
     private short statValue8;
     private byte statType9;
     private short statValue9;
     private byte statType10;
     private short statValue10;
     private float dmgMin1;
     private float dmgMax1;
     private byte dmgType1;
     private float dmgMin2;
     private float dmgMax2;
     private byte dmgType2;
     private float dmgMin3;
     private float dmgMax3;
     private byte dmgType3;
     private float dmgMin4;
     private float dmgMax4;
     private byte dmgType4;
     private float dmgMin5;
     private float dmgMax5;
     private byte dmgType5;
     private short armor;
     private byte holyRes;
     private byte fireRes;
     private byte natureRes;
     private byte frostRes;
     private byte shadowRes;
     private byte arcaneRes;
     private short delay;
     private byte ammoType;
     private float rangedModRange;
     private int spellid1;
     private byte spelltrigger1;
     private byte spellcharges1;
     private float spellppmRate1;
     private int spellcooldown1;
     private short spellcategory1;
     private int spellcategorycooldown1;
     private int spellid2;
     private byte spelltrigger2;
     private byte spellcharges2;
     private float spellppmRate2;
     private int spellcooldown2;
     private short spellcategory2;
     private int spellcategorycooldown2;
     private int spellid3;
     private byte spelltrigger3;
     private byte spellcharges3;
     private float spellppmRate3;
     private int spellcooldown3;
     private short spellcategory3;
     private int spellcategorycooldown3;
     private int spellid4;
     private byte spelltrigger4;
     private byte spellcharges4;
     private float spellppmRate4;
     private int spellcooldown4;
     private short spellcategory4;
     private int spellcategorycooldown4;
     private int spellid5;
     private byte spelltrigger5;
     private byte spellcharges5;
     private float spellppmRate5;
     private int spellcooldown5;
     private short spellcategory5;
     private int spellcategorycooldown5;
     private byte bonding;
     private String description;
     private byte languageid;
     private byte pagematerial;
     private int startquest;
     private int lockid;
     private byte material;
     private byte sheath;
     private int randomproperty;
     private int block;
     private int itemset;
     private short maxdurability;
     private int area;
     private short map;
     private int bagfamily;
     private String scriptname;
     private int disenchantid;
     private byte foodtype;
     private int minmoneyloot;
     private int maxmoneyloot;
     private int duration;
     private boolean extraflags;
     private Set<Startingequipment> startingequipments = new HashSet<Startingequipment>(0);
     private Set<Spells> spellses = new HashSet<Spells>(0);
     private Set<Spellcomponents> spellcomponentses = new HashSet<Spellcomponents>(0);

    public Item() {
    }

	
    public Item(int entry, Inventorytype inventorytype, Itemquality itemquality, Itemsubclass itemsubclass, String name, int displayid, int flags, short buycount, int buyprice, int sellprice, int allowableclass, int allowablerace, byte itemlevel, byte requiredlevel, short requiredskill, short requiredskillrank, int requiredspell, int requiredhonorrank, int requiredcityrank, short requiredreputationfaction, short requiredreputationrank, short maxcount, short stackable, byte containerslots, byte statType1, short statValue1, byte statType2, short statValue2, byte statType3, short statValue3, byte statType4, short statValue4, byte statType5, short statValue5, byte statType6, short statValue6, byte statType7, short statValue7, byte statType8, short statValue8, byte statType9, short statValue9, byte statType10, short statValue10, float dmgMin1, float dmgMax1, byte dmgType1, float dmgMin2, float dmgMax2, byte dmgType2, float dmgMin3, float dmgMax3, byte dmgType3, float dmgMin4, float dmgMax4, byte dmgType4, float dmgMin5, float dmgMax5, byte dmgType5, short armor, byte holyRes, byte fireRes, byte natureRes, byte frostRes, byte shadowRes, byte arcaneRes, short delay, byte ammoType, float rangedModRange, int spellid1, byte spelltrigger1, byte spellcharges1, float spellppmRate1, int spellcooldown1, short spellcategory1, int spellcategorycooldown1, int spellid2, byte spelltrigger2, byte spellcharges2, float spellppmRate2, int spellcooldown2, short spellcategory2, int spellcategorycooldown2, int spellid3, byte spelltrigger3, byte spellcharges3, float spellppmRate3, int spellcooldown3, short spellcategory3, int spellcategorycooldown3, int spellid4, byte spelltrigger4, byte spellcharges4, float spellppmRate4, int spellcooldown4, short spellcategory4, int spellcategorycooldown4, int spellid5, byte spelltrigger5, byte spellcharges5, float spellppmRate5, int spellcooldown5, short spellcategory5, int spellcategorycooldown5, byte bonding, String description, byte languageid, byte pagematerial, int startquest, int lockid, byte material, byte sheath, int randomproperty, int block, int itemset, short maxdurability, int area, short map, int bagfamily, String scriptname, int disenchantid, byte foodtype, int minmoneyloot, int maxmoneyloot, int duration, boolean extraflags) {
        this.entry = entry;
        this.inventorytype = inventorytype;
        this.itemquality = itemquality;
        this.itemsubclass = itemsubclass;
        this.name = name;
        this.displayid = displayid;
        this.flags = flags;
        this.buycount = buycount;
        this.buyprice = buyprice;
        this.sellprice = sellprice;
        this.allowableclass = allowableclass;
        this.allowablerace = allowablerace;
        this.itemlevel = itemlevel;
        this.requiredlevel = requiredlevel;
        this.requiredskill = requiredskill;
        this.requiredskillrank = requiredskillrank;
        this.requiredspell = requiredspell;
        this.requiredhonorrank = requiredhonorrank;
        this.requiredcityrank = requiredcityrank;
        this.requiredreputationfaction = requiredreputationfaction;
        this.requiredreputationrank = requiredreputationrank;
        this.maxcount = maxcount;
        this.stackable = stackable;
        this.containerslots = containerslots;
        this.statType1 = statType1;
        this.statValue1 = statValue1;
        this.statType2 = statType2;
        this.statValue2 = statValue2;
        this.statType3 = statType3;
        this.statValue3 = statValue3;
        this.statType4 = statType4;
        this.statValue4 = statValue4;
        this.statType5 = statType5;
        this.statValue5 = statValue5;
        this.statType6 = statType6;
        this.statValue6 = statValue6;
        this.statType7 = statType7;
        this.statValue7 = statValue7;
        this.statType8 = statType8;
        this.statValue8 = statValue8;
        this.statType9 = statType9;
        this.statValue9 = statValue9;
        this.statType10 = statType10;
        this.statValue10 = statValue10;
        this.dmgMin1 = dmgMin1;
        this.dmgMax1 = dmgMax1;
        this.dmgType1 = dmgType1;
        this.dmgMin2 = dmgMin2;
        this.dmgMax2 = dmgMax2;
        this.dmgType2 = dmgType2;
        this.dmgMin3 = dmgMin3;
        this.dmgMax3 = dmgMax3;
        this.dmgType3 = dmgType3;
        this.dmgMin4 = dmgMin4;
        this.dmgMax4 = dmgMax4;
        this.dmgType4 = dmgType4;
        this.dmgMin5 = dmgMin5;
        this.dmgMax5 = dmgMax5;
        this.dmgType5 = dmgType5;
        this.armor = armor;
        this.holyRes = holyRes;
        this.fireRes = fireRes;
        this.natureRes = natureRes;
        this.frostRes = frostRes;
        this.shadowRes = shadowRes;
        this.arcaneRes = arcaneRes;
        this.delay = delay;
        this.ammoType = ammoType;
        this.rangedModRange = rangedModRange;
        this.spellid1 = spellid1;
        this.spelltrigger1 = spelltrigger1;
        this.spellcharges1 = spellcharges1;
        this.spellppmRate1 = spellppmRate1;
        this.spellcooldown1 = spellcooldown1;
        this.spellcategory1 = spellcategory1;
        this.spellcategorycooldown1 = spellcategorycooldown1;
        this.spellid2 = spellid2;
        this.spelltrigger2 = spelltrigger2;
        this.spellcharges2 = spellcharges2;
        this.spellppmRate2 = spellppmRate2;
        this.spellcooldown2 = spellcooldown2;
        this.spellcategory2 = spellcategory2;
        this.spellcategorycooldown2 = spellcategorycooldown2;
        this.spellid3 = spellid3;
        this.spelltrigger3 = spelltrigger3;
        this.spellcharges3 = spellcharges3;
        this.spellppmRate3 = spellppmRate3;
        this.spellcooldown3 = spellcooldown3;
        this.spellcategory3 = spellcategory3;
        this.spellcategorycooldown3 = spellcategorycooldown3;
        this.spellid4 = spellid4;
        this.spelltrigger4 = spelltrigger4;
        this.spellcharges4 = spellcharges4;
        this.spellppmRate4 = spellppmRate4;
        this.spellcooldown4 = spellcooldown4;
        this.spellcategory4 = spellcategory4;
        this.spellcategorycooldown4 = spellcategorycooldown4;
        this.spellid5 = spellid5;
        this.spelltrigger5 = spelltrigger5;
        this.spellcharges5 = spellcharges5;
        this.spellppmRate5 = spellppmRate5;
        this.spellcooldown5 = spellcooldown5;
        this.spellcategory5 = spellcategory5;
        this.spellcategorycooldown5 = spellcategorycooldown5;
        this.bonding = bonding;
        this.description = description;
        this.languageid = languageid;
        this.pagematerial = pagematerial;
        this.startquest = startquest;
        this.lockid = lockid;
        this.material = material;
        this.sheath = sheath;
        this.randomproperty = randomproperty;
        this.block = block;
        this.itemset = itemset;
        this.maxdurability = maxdurability;
        this.area = area;
        this.map = map;
        this.bagfamily = bagfamily;
        this.scriptname = scriptname;
        this.disenchantid = disenchantid;
        this.foodtype = foodtype;
        this.minmoneyloot = minmoneyloot;
        this.maxmoneyloot = maxmoneyloot;
        this.duration = duration;
        this.extraflags = extraflags;
    }
    public Item(int entry, Inventorytype inventorytype, Itemquality itemquality, Itemsubclass itemsubclass, Pagetext pagetext, String name, int displayid, int flags, short buycount, int buyprice, int sellprice, int allowableclass, int allowablerace, byte itemlevel, byte requiredlevel, short requiredskill, short requiredskillrank, int requiredspell, int requiredhonorrank, int requiredcityrank, short requiredreputationfaction, short requiredreputationrank, short maxcount, short stackable, byte containerslots, byte statType1, short statValue1, byte statType2, short statValue2, byte statType3, short statValue3, byte statType4, short statValue4, byte statType5, short statValue5, byte statType6, short statValue6, byte statType7, short statValue7, byte statType8, short statValue8, byte statType9, short statValue9, byte statType10, short statValue10, float dmgMin1, float dmgMax1, byte dmgType1, float dmgMin2, float dmgMax2, byte dmgType2, float dmgMin3, float dmgMax3, byte dmgType3, float dmgMin4, float dmgMax4, byte dmgType4, float dmgMin5, float dmgMax5, byte dmgType5, short armor, byte holyRes, byte fireRes, byte natureRes, byte frostRes, byte shadowRes, byte arcaneRes, short delay, byte ammoType, float rangedModRange, int spellid1, byte spelltrigger1, byte spellcharges1, float spellppmRate1, int spellcooldown1, short spellcategory1, int spellcategorycooldown1, int spellid2, byte spelltrigger2, byte spellcharges2, float spellppmRate2, int spellcooldown2, short spellcategory2, int spellcategorycooldown2, int spellid3, byte spelltrigger3, byte spellcharges3, float spellppmRate3, int spellcooldown3, short spellcategory3, int spellcategorycooldown3, int spellid4, byte spelltrigger4, byte spellcharges4, float spellppmRate4, int spellcooldown4, short spellcategory4, int spellcategorycooldown4, int spellid5, byte spelltrigger5, byte spellcharges5, float spellppmRate5, int spellcooldown5, short spellcategory5, int spellcategorycooldown5, byte bonding, String description, byte languageid, byte pagematerial, int startquest, int lockid, byte material, byte sheath, int randomproperty, int block, int itemset, short maxdurability, int area, short map, int bagfamily, String scriptname, int disenchantid, byte foodtype, int minmoneyloot, int maxmoneyloot, int duration, boolean extraflags, Set<Startingequipment> startingequipments, Set<Spells> spellses, Set<Spellcomponents> spellcomponentses) {
       this.entry = entry;
       this.inventorytype = inventorytype;
       this.itemquality = itemquality;
       this.itemsubclass = itemsubclass;
       this.pagetext = pagetext;
       this.name = name;
       this.displayid = displayid;
       this.flags = flags;
       this.buycount = buycount;
       this.buyprice = buyprice;
       this.sellprice = sellprice;
       this.allowableclass = allowableclass;
       this.allowablerace = allowablerace;
       this.itemlevel = itemlevel;
       this.requiredlevel = requiredlevel;
       this.requiredskill = requiredskill;
       this.requiredskillrank = requiredskillrank;
       this.requiredspell = requiredspell;
       this.requiredhonorrank = requiredhonorrank;
       this.requiredcityrank = requiredcityrank;
       this.requiredreputationfaction = requiredreputationfaction;
       this.requiredreputationrank = requiredreputationrank;
       this.maxcount = maxcount;
       this.stackable = stackable;
       this.containerslots = containerslots;
       this.statType1 = statType1;
       this.statValue1 = statValue1;
       this.statType2 = statType2;
       this.statValue2 = statValue2;
       this.statType3 = statType3;
       this.statValue3 = statValue3;
       this.statType4 = statType4;
       this.statValue4 = statValue4;
       this.statType5 = statType5;
       this.statValue5 = statValue5;
       this.statType6 = statType6;
       this.statValue6 = statValue6;
       this.statType7 = statType7;
       this.statValue7 = statValue7;
       this.statType8 = statType8;
       this.statValue8 = statValue8;
       this.statType9 = statType9;
       this.statValue9 = statValue9;
       this.statType10 = statType10;
       this.statValue10 = statValue10;
       this.dmgMin1 = dmgMin1;
       this.dmgMax1 = dmgMax1;
       this.dmgType1 = dmgType1;
       this.dmgMin2 = dmgMin2;
       this.dmgMax2 = dmgMax2;
       this.dmgType2 = dmgType2;
       this.dmgMin3 = dmgMin3;
       this.dmgMax3 = dmgMax3;
       this.dmgType3 = dmgType3;
       this.dmgMin4 = dmgMin4;
       this.dmgMax4 = dmgMax4;
       this.dmgType4 = dmgType4;
       this.dmgMin5 = dmgMin5;
       this.dmgMax5 = dmgMax5;
       this.dmgType5 = dmgType5;
       this.armor = armor;
       this.holyRes = holyRes;
       this.fireRes = fireRes;
       this.natureRes = natureRes;
       this.frostRes = frostRes;
       this.shadowRes = shadowRes;
       this.arcaneRes = arcaneRes;
       this.delay = delay;
       this.ammoType = ammoType;
       this.rangedModRange = rangedModRange;
       this.spellid1 = spellid1;
       this.spelltrigger1 = spelltrigger1;
       this.spellcharges1 = spellcharges1;
       this.spellppmRate1 = spellppmRate1;
       this.spellcooldown1 = spellcooldown1;
       this.spellcategory1 = spellcategory1;
       this.spellcategorycooldown1 = spellcategorycooldown1;
       this.spellid2 = spellid2;
       this.spelltrigger2 = spelltrigger2;
       this.spellcharges2 = spellcharges2;
       this.spellppmRate2 = spellppmRate2;
       this.spellcooldown2 = spellcooldown2;
       this.spellcategory2 = spellcategory2;
       this.spellcategorycooldown2 = spellcategorycooldown2;
       this.spellid3 = spellid3;
       this.spelltrigger3 = spelltrigger3;
       this.spellcharges3 = spellcharges3;
       this.spellppmRate3 = spellppmRate3;
       this.spellcooldown3 = spellcooldown3;
       this.spellcategory3 = spellcategory3;
       this.spellcategorycooldown3 = spellcategorycooldown3;
       this.spellid4 = spellid4;
       this.spelltrigger4 = spelltrigger4;
       this.spellcharges4 = spellcharges4;
       this.spellppmRate4 = spellppmRate4;
       this.spellcooldown4 = spellcooldown4;
       this.spellcategory4 = spellcategory4;
       this.spellcategorycooldown4 = spellcategorycooldown4;
       this.spellid5 = spellid5;
       this.spelltrigger5 = spelltrigger5;
       this.spellcharges5 = spellcharges5;
       this.spellppmRate5 = spellppmRate5;
       this.spellcooldown5 = spellcooldown5;
       this.spellcategory5 = spellcategory5;
       this.spellcategorycooldown5 = spellcategorycooldown5;
       this.bonding = bonding;
       this.description = description;
       this.languageid = languageid;
       this.pagematerial = pagematerial;
       this.startquest = startquest;
       this.lockid = lockid;
       this.material = material;
       this.sheath = sheath;
       this.randomproperty = randomproperty;
       this.block = block;
       this.itemset = itemset;
       this.maxdurability = maxdurability;
       this.area = area;
       this.map = map;
       this.bagfamily = bagfamily;
       this.scriptname = scriptname;
       this.disenchantid = disenchantid;
       this.foodtype = foodtype;
       this.minmoneyloot = minmoneyloot;
       this.maxmoneyloot = maxmoneyloot;
       this.duration = duration;
       this.extraflags = extraflags;
       this.startingequipments = startingequipments;
       this.spellses = spellses;
       this.spellcomponentses = spellcomponentses;
    }
   
     @Id 

    
    @Column(name="entry", unique=true, nullable=false)
    public int getEntry() {
        return this.entry;
    }
    
    public void setEntry(int entry) {
        this.entry = entry;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_inventorytype", nullable=false)
    public Inventorytype getInventorytype() {
        return this.inventorytype;
    }
    
    public void setInventorytype(Inventorytype inventorytype) {
        this.inventorytype = inventorytype;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_quality", nullable=false)
    public Itemquality getItemquality() {
        return this.itemquality;
    }
    
    public void setItemquality(Itemquality itemquality) {
        this.itemquality = itemquality;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="fk_class", referencedColumnName="fk_itemclass", nullable=false), 
        @JoinColumn(name="fk_subclass", referencedColumnName="id", nullable=false) } )
    public Itemsubclass getItemsubclass() {
        return this.itemsubclass;
    }
    
    public void setItemsubclass(Itemsubclass itemsubclass) {
        this.itemsubclass = itemsubclass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_pagetext")
    public Pagetext getPagetext() {
        return this.pagetext;
    }
    
    public void setPagetext(Pagetext pagetext) {
        this.pagetext = pagetext;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="displayid", nullable=false)
    public int getDisplayid() {
        return this.displayid;
    }
    
    public void setDisplayid(int displayid) {
        this.displayid = displayid;
    }

    
    @Column(name="flags", nullable=false)
    public int getFlags() {
        return this.flags;
    }
    
    public void setFlags(int flags) {
        this.flags = flags;
    }

    
    @Column(name="buycount", nullable=false)
    public short getBuycount() {
        return this.buycount;
    }
    
    public void setBuycount(short buycount) {
        this.buycount = buycount;
    }

    
    @Column(name="buyprice", nullable=false)
    public int getBuyprice() {
        return this.buyprice;
    }
    
    public void setBuyprice(int buyprice) {
        this.buyprice = buyprice;
    }

    
    @Column(name="sellprice", nullable=false)
    public int getSellprice() {
        return this.sellprice;
    }
    
    public void setSellprice(int sellprice) {
        this.sellprice = sellprice;
    }

    
    @Column(name="allowableclass", nullable=false)
    public int getAllowableclass() {
        return this.allowableclass;
    }
    
    public void setAllowableclass(int allowableclass) {
        this.allowableclass = allowableclass;
    }

    
    @Column(name="allowablerace", nullable=false)
    public int getAllowablerace() {
        return this.allowablerace;
    }
    
    public void setAllowablerace(int allowablerace) {
        this.allowablerace = allowablerace;
    }

    
    @Column(name="itemlevel", nullable=false)
    public byte getItemlevel() {
        return this.itemlevel;
    }
    
    public void setItemlevel(byte itemlevel) {
        this.itemlevel = itemlevel;
    }

    
    @Column(name="requiredlevel", nullable=false)
    public byte getRequiredlevel() {
        return this.requiredlevel;
    }
    
    public void setRequiredlevel(byte requiredlevel) {
        this.requiredlevel = requiredlevel;
    }

    
    @Column(name="requiredskill", nullable=false)
    public short getRequiredskill() {
        return this.requiredskill;
    }
    
    public void setRequiredskill(short requiredskill) {
        this.requiredskill = requiredskill;
    }

    
    @Column(name="requiredskillrank", nullable=false)
    public short getRequiredskillrank() {
        return this.requiredskillrank;
    }
    
    public void setRequiredskillrank(short requiredskillrank) {
        this.requiredskillrank = requiredskillrank;
    }

    
    @Column(name="requiredspell", nullable=false)
    public int getRequiredspell() {
        return this.requiredspell;
    }
    
    public void setRequiredspell(int requiredspell) {
        this.requiredspell = requiredspell;
    }

    
    @Column(name="requiredhonorrank", nullable=false)
    public int getRequiredhonorrank() {
        return this.requiredhonorrank;
    }
    
    public void setRequiredhonorrank(int requiredhonorrank) {
        this.requiredhonorrank = requiredhonorrank;
    }

    
    @Column(name="requiredcityrank", nullable=false)
    public int getRequiredcityrank() {
        return this.requiredcityrank;
    }
    
    public void setRequiredcityrank(int requiredcityrank) {
        this.requiredcityrank = requiredcityrank;
    }

    
    @Column(name="requiredreputationfaction", nullable=false)
    public short getRequiredreputationfaction() {
        return this.requiredreputationfaction;
    }
    
    public void setRequiredreputationfaction(short requiredreputationfaction) {
        this.requiredreputationfaction = requiredreputationfaction;
    }

    
    @Column(name="requiredreputationrank", nullable=false)
    public short getRequiredreputationrank() {
        return this.requiredreputationrank;
    }
    
    public void setRequiredreputationrank(short requiredreputationrank) {
        this.requiredreputationrank = requiredreputationrank;
    }

    
    @Column(name="maxcount", nullable=false)
    public short getMaxcount() {
        return this.maxcount;
    }
    
    public void setMaxcount(short maxcount) {
        this.maxcount = maxcount;
    }

    
    @Column(name="stackable", nullable=false)
    public short getStackable() {
        return this.stackable;
    }
    
    public void setStackable(short stackable) {
        this.stackable = stackable;
    }

    
    @Column(name="containerslots", nullable=false)
    public byte getContainerslots() {
        return this.containerslots;
    }
    
    public void setContainerslots(byte containerslots) {
        this.containerslots = containerslots;
    }

    
    @Column(name="stat_type1", nullable=false)
    public byte getStatType1() {
        return this.statType1;
    }
    
    public void setStatType1(byte statType1) {
        this.statType1 = statType1;
    }

    
    @Column(name="stat_value1", nullable=false)
    public short getStatValue1() {
        return this.statValue1;
    }
    
    public void setStatValue1(short statValue1) {
        this.statValue1 = statValue1;
    }

    
    @Column(name="stat_type2", nullable=false)
    public byte getStatType2() {
        return this.statType2;
    }
    
    public void setStatType2(byte statType2) {
        this.statType2 = statType2;
    }

    
    @Column(name="stat_value2", nullable=false)
    public short getStatValue2() {
        return this.statValue2;
    }
    
    public void setStatValue2(short statValue2) {
        this.statValue2 = statValue2;
    }

    
    @Column(name="stat_type3", nullable=false)
    public byte getStatType3() {
        return this.statType3;
    }
    
    public void setStatType3(byte statType3) {
        this.statType3 = statType3;
    }

    
    @Column(name="stat_value3", nullable=false)
    public short getStatValue3() {
        return this.statValue3;
    }
    
    public void setStatValue3(short statValue3) {
        this.statValue3 = statValue3;
    }

    
    @Column(name="stat_type4", nullable=false)
    public byte getStatType4() {
        return this.statType4;
    }
    
    public void setStatType4(byte statType4) {
        this.statType4 = statType4;
    }

    
    @Column(name="stat_value4", nullable=false)
    public short getStatValue4() {
        return this.statValue4;
    }
    
    public void setStatValue4(short statValue4) {
        this.statValue4 = statValue4;
    }

    
    @Column(name="stat_type5", nullable=false)
    public byte getStatType5() {
        return this.statType5;
    }
    
    public void setStatType5(byte statType5) {
        this.statType5 = statType5;
    }

    
    @Column(name="stat_value5", nullable=false)
    public short getStatValue5() {
        return this.statValue5;
    }
    
    public void setStatValue5(short statValue5) {
        this.statValue5 = statValue5;
    }

    
    @Column(name="stat_type6", nullable=false)
    public byte getStatType6() {
        return this.statType6;
    }
    
    public void setStatType6(byte statType6) {
        this.statType6 = statType6;
    }

    
    @Column(name="stat_value6", nullable=false)
    public short getStatValue6() {
        return this.statValue6;
    }
    
    public void setStatValue6(short statValue6) {
        this.statValue6 = statValue6;
    }

    
    @Column(name="stat_type7", nullable=false)
    public byte getStatType7() {
        return this.statType7;
    }
    
    public void setStatType7(byte statType7) {
        this.statType7 = statType7;
    }

    
    @Column(name="stat_value7", nullable=false)
    public short getStatValue7() {
        return this.statValue7;
    }
    
    public void setStatValue7(short statValue7) {
        this.statValue7 = statValue7;
    }

    
    @Column(name="stat_type8", nullable=false)
    public byte getStatType8() {
        return this.statType8;
    }
    
    public void setStatType8(byte statType8) {
        this.statType8 = statType8;
    }

    
    @Column(name="stat_value8", nullable=false)
    public short getStatValue8() {
        return this.statValue8;
    }
    
    public void setStatValue8(short statValue8) {
        this.statValue8 = statValue8;
    }

    
    @Column(name="stat_type9", nullable=false)
    public byte getStatType9() {
        return this.statType9;
    }
    
    public void setStatType9(byte statType9) {
        this.statType9 = statType9;
    }

    
    @Column(name="stat_value9", nullable=false)
    public short getStatValue9() {
        return this.statValue9;
    }
    
    public void setStatValue9(short statValue9) {
        this.statValue9 = statValue9;
    }

    
    @Column(name="stat_type10", nullable=false)
    public byte getStatType10() {
        return this.statType10;
    }
    
    public void setStatType10(byte statType10) {
        this.statType10 = statType10;
    }

    
    @Column(name="stat_value10", nullable=false)
    public short getStatValue10() {
        return this.statValue10;
    }
    
    public void setStatValue10(short statValue10) {
        this.statValue10 = statValue10;
    }

    
    @Column(name="dmg_min1", nullable=false, precision=12, scale=0)
    public float getDmgMin1() {
        return this.dmgMin1;
    }
    
    public void setDmgMin1(float dmgMin1) {
        this.dmgMin1 = dmgMin1;
    }

    
    @Column(name="dmg_max1", nullable=false, precision=12, scale=0)
    public float getDmgMax1() {
        return this.dmgMax1;
    }
    
    public void setDmgMax1(float dmgMax1) {
        this.dmgMax1 = dmgMax1;
    }

    
    @Column(name="dmg_type1", nullable=false)
    public byte getDmgType1() {
        return this.dmgType1;
    }
    
    public void setDmgType1(byte dmgType1) {
        this.dmgType1 = dmgType1;
    }

    
    @Column(name="dmg_min2", nullable=false, precision=12, scale=0)
    public float getDmgMin2() {
        return this.dmgMin2;
    }
    
    public void setDmgMin2(float dmgMin2) {
        this.dmgMin2 = dmgMin2;
    }

    
    @Column(name="dmg_max2", nullable=false, precision=12, scale=0)
    public float getDmgMax2() {
        return this.dmgMax2;
    }
    
    public void setDmgMax2(float dmgMax2) {
        this.dmgMax2 = dmgMax2;
    }

    
    @Column(name="dmg_type2", nullable=false)
    public byte getDmgType2() {
        return this.dmgType2;
    }
    
    public void setDmgType2(byte dmgType2) {
        this.dmgType2 = dmgType2;
    }

    
    @Column(name="dmg_min3", nullable=false, precision=12, scale=0)
    public float getDmgMin3() {
        return this.dmgMin3;
    }
    
    public void setDmgMin3(float dmgMin3) {
        this.dmgMin3 = dmgMin3;
    }

    
    @Column(name="dmg_max3", nullable=false, precision=12, scale=0)
    public float getDmgMax3() {
        return this.dmgMax3;
    }
    
    public void setDmgMax3(float dmgMax3) {
        this.dmgMax3 = dmgMax3;
    }

    
    @Column(name="dmg_type3", nullable=false)
    public byte getDmgType3() {
        return this.dmgType3;
    }
    
    public void setDmgType3(byte dmgType3) {
        this.dmgType3 = dmgType3;
    }

    
    @Column(name="dmg_min4", nullable=false, precision=12, scale=0)
    public float getDmgMin4() {
        return this.dmgMin4;
    }
    
    public void setDmgMin4(float dmgMin4) {
        this.dmgMin4 = dmgMin4;
    }

    
    @Column(name="dmg_max4", nullable=false, precision=12, scale=0)
    public float getDmgMax4() {
        return this.dmgMax4;
    }
    
    public void setDmgMax4(float dmgMax4) {
        this.dmgMax4 = dmgMax4;
    }

    
    @Column(name="dmg_type4", nullable=false)
    public byte getDmgType4() {
        return this.dmgType4;
    }
    
    public void setDmgType4(byte dmgType4) {
        this.dmgType4 = dmgType4;
    }

    
    @Column(name="dmg_min5", nullable=false, precision=12, scale=0)
    public float getDmgMin5() {
        return this.dmgMin5;
    }
    
    public void setDmgMin5(float dmgMin5) {
        this.dmgMin5 = dmgMin5;
    }

    
    @Column(name="dmg_max5", nullable=false, precision=12, scale=0)
    public float getDmgMax5() {
        return this.dmgMax5;
    }
    
    public void setDmgMax5(float dmgMax5) {
        this.dmgMax5 = dmgMax5;
    }

    
    @Column(name="dmg_type5", nullable=false)
    public byte getDmgType5() {
        return this.dmgType5;
    }
    
    public void setDmgType5(byte dmgType5) {
        this.dmgType5 = dmgType5;
    }

    
    @Column(name="armor", nullable=false)
    public short getArmor() {
        return this.armor;
    }
    
    public void setArmor(short armor) {
        this.armor = armor;
    }

    
    @Column(name="holy_res", nullable=false)
    public byte getHolyRes() {
        return this.holyRes;
    }
    
    public void setHolyRes(byte holyRes) {
        this.holyRes = holyRes;
    }

    
    @Column(name="fire_res", nullable=false)
    public byte getFireRes() {
        return this.fireRes;
    }
    
    public void setFireRes(byte fireRes) {
        this.fireRes = fireRes;
    }

    
    @Column(name="nature_res", nullable=false)
    public byte getNatureRes() {
        return this.natureRes;
    }
    
    public void setNatureRes(byte natureRes) {
        this.natureRes = natureRes;
    }

    
    @Column(name="frost_res", nullable=false)
    public byte getFrostRes() {
        return this.frostRes;
    }
    
    public void setFrostRes(byte frostRes) {
        this.frostRes = frostRes;
    }

    
    @Column(name="shadow_res", nullable=false)
    public byte getShadowRes() {
        return this.shadowRes;
    }
    
    public void setShadowRes(byte shadowRes) {
        this.shadowRes = shadowRes;
    }

    
    @Column(name="arcane_res", nullable=false)
    public byte getArcaneRes() {
        return this.arcaneRes;
    }
    
    public void setArcaneRes(byte arcaneRes) {
        this.arcaneRes = arcaneRes;
    }

    
    @Column(name="delay", nullable=false)
    public short getDelay() {
        return this.delay;
    }
    
    public void setDelay(short delay) {
        this.delay = delay;
    }

    
    @Column(name="ammo_type", nullable=false)
    public byte getAmmoType() {
        return this.ammoType;
    }
    
    public void setAmmoType(byte ammoType) {
        this.ammoType = ammoType;
    }

    
    @Column(name="RangedModRange", nullable=false, precision=12, scale=0)
    public float getRangedModRange() {
        return this.rangedModRange;
    }
    
    public void setRangedModRange(float rangedModRange) {
        this.rangedModRange = rangedModRange;
    }

    
    @Column(name="spellid_1", nullable=false)
    public int getSpellid1() {
        return this.spellid1;
    }
    
    public void setSpellid1(int spellid1) {
        this.spellid1 = spellid1;
    }

    
    @Column(name="spelltrigger_1", nullable=false)
    public byte getSpelltrigger1() {
        return this.spelltrigger1;
    }
    
    public void setSpelltrigger1(byte spelltrigger1) {
        this.spelltrigger1 = spelltrigger1;
    }

    
    @Column(name="spellcharges_1", nullable=false)
    public byte getSpellcharges1() {
        return this.spellcharges1;
    }
    
    public void setSpellcharges1(byte spellcharges1) {
        this.spellcharges1 = spellcharges1;
    }

    
    @Column(name="spellppmRate_1", nullable=false, precision=12, scale=0)
    public float getSpellppmRate1() {
        return this.spellppmRate1;
    }
    
    public void setSpellppmRate1(float spellppmRate1) {
        this.spellppmRate1 = spellppmRate1;
    }

    
    @Column(name="spellcooldown_1", nullable=false)
    public int getSpellcooldown1() {
        return this.spellcooldown1;
    }
    
    public void setSpellcooldown1(int spellcooldown1) {
        this.spellcooldown1 = spellcooldown1;
    }

    
    @Column(name="spellcategory_1", nullable=false)
    public short getSpellcategory1() {
        return this.spellcategory1;
    }
    
    public void setSpellcategory1(short spellcategory1) {
        this.spellcategory1 = spellcategory1;
    }

    
    @Column(name="spellcategorycooldown_1", nullable=false)
    public int getSpellcategorycooldown1() {
        return this.spellcategorycooldown1;
    }
    
    public void setSpellcategorycooldown1(int spellcategorycooldown1) {
        this.spellcategorycooldown1 = spellcategorycooldown1;
    }

    
    @Column(name="spellid_2", nullable=false)
    public int getSpellid2() {
        return this.spellid2;
    }
    
    public void setSpellid2(int spellid2) {
        this.spellid2 = spellid2;
    }

    
    @Column(name="spelltrigger_2", nullable=false)
    public byte getSpelltrigger2() {
        return this.spelltrigger2;
    }
    
    public void setSpelltrigger2(byte spelltrigger2) {
        this.spelltrigger2 = spelltrigger2;
    }

    
    @Column(name="spellcharges_2", nullable=false)
    public byte getSpellcharges2() {
        return this.spellcharges2;
    }
    
    public void setSpellcharges2(byte spellcharges2) {
        this.spellcharges2 = spellcharges2;
    }

    
    @Column(name="spellppmRate_2", nullable=false, precision=12, scale=0)
    public float getSpellppmRate2() {
        return this.spellppmRate2;
    }
    
    public void setSpellppmRate2(float spellppmRate2) {
        this.spellppmRate2 = spellppmRate2;
    }

    
    @Column(name="spellcooldown_2", nullable=false)
    public int getSpellcooldown2() {
        return this.spellcooldown2;
    }
    
    public void setSpellcooldown2(int spellcooldown2) {
        this.spellcooldown2 = spellcooldown2;
    }

    
    @Column(name="spellcategory_2", nullable=false)
    public short getSpellcategory2() {
        return this.spellcategory2;
    }
    
    public void setSpellcategory2(short spellcategory2) {
        this.spellcategory2 = spellcategory2;
    }

    
    @Column(name="spellcategorycooldown_2", nullable=false)
    public int getSpellcategorycooldown2() {
        return this.spellcategorycooldown2;
    }
    
    public void setSpellcategorycooldown2(int spellcategorycooldown2) {
        this.spellcategorycooldown2 = spellcategorycooldown2;
    }

    
    @Column(name="spellid_3", nullable=false)
    public int getSpellid3() {
        return this.spellid3;
    }
    
    public void setSpellid3(int spellid3) {
        this.spellid3 = spellid3;
    }

    
    @Column(name="spelltrigger_3", nullable=false)
    public byte getSpelltrigger3() {
        return this.spelltrigger3;
    }
    
    public void setSpelltrigger3(byte spelltrigger3) {
        this.spelltrigger3 = spelltrigger3;
    }

    
    @Column(name="spellcharges_3", nullable=false)
    public byte getSpellcharges3() {
        return this.spellcharges3;
    }
    
    public void setSpellcharges3(byte spellcharges3) {
        this.spellcharges3 = spellcharges3;
    }

    
    @Column(name="spellppmRate_3", nullable=false, precision=12, scale=0)
    public float getSpellppmRate3() {
        return this.spellppmRate3;
    }
    
    public void setSpellppmRate3(float spellppmRate3) {
        this.spellppmRate3 = spellppmRate3;
    }

    
    @Column(name="spellcooldown_3", nullable=false)
    public int getSpellcooldown3() {
        return this.spellcooldown3;
    }
    
    public void setSpellcooldown3(int spellcooldown3) {
        this.spellcooldown3 = spellcooldown3;
    }

    
    @Column(name="spellcategory_3", nullable=false)
    public short getSpellcategory3() {
        return this.spellcategory3;
    }
    
    public void setSpellcategory3(short spellcategory3) {
        this.spellcategory3 = spellcategory3;
    }

    
    @Column(name="spellcategorycooldown_3", nullable=false)
    public int getSpellcategorycooldown3() {
        return this.spellcategorycooldown3;
    }
    
    public void setSpellcategorycooldown3(int spellcategorycooldown3) {
        this.spellcategorycooldown3 = spellcategorycooldown3;
    }

    
    @Column(name="spellid_4", nullable=false)
    public int getSpellid4() {
        return this.spellid4;
    }
    
    public void setSpellid4(int spellid4) {
        this.spellid4 = spellid4;
    }

    
    @Column(name="spelltrigger_4", nullable=false)
    public byte getSpelltrigger4() {
        return this.spelltrigger4;
    }
    
    public void setSpelltrigger4(byte spelltrigger4) {
        this.spelltrigger4 = spelltrigger4;
    }

    
    @Column(name="spellcharges_4", nullable=false)
    public byte getSpellcharges4() {
        return this.spellcharges4;
    }
    
    public void setSpellcharges4(byte spellcharges4) {
        this.spellcharges4 = spellcharges4;
    }

    
    @Column(name="spellppmRate_4", nullable=false, precision=12, scale=0)
    public float getSpellppmRate4() {
        return this.spellppmRate4;
    }
    
    public void setSpellppmRate4(float spellppmRate4) {
        this.spellppmRate4 = spellppmRate4;
    }

    
    @Column(name="spellcooldown_4", nullable=false)
    public int getSpellcooldown4() {
        return this.spellcooldown4;
    }
    
    public void setSpellcooldown4(int spellcooldown4) {
        this.spellcooldown4 = spellcooldown4;
    }

    
    @Column(name="spellcategory_4", nullable=false)
    public short getSpellcategory4() {
        return this.spellcategory4;
    }
    
    public void setSpellcategory4(short spellcategory4) {
        this.spellcategory4 = spellcategory4;
    }

    
    @Column(name="spellcategorycooldown_4", nullable=false)
    public int getSpellcategorycooldown4() {
        return this.spellcategorycooldown4;
    }
    
    public void setSpellcategorycooldown4(int spellcategorycooldown4) {
        this.spellcategorycooldown4 = spellcategorycooldown4;
    }

    
    @Column(name="spellid_5", nullable=false)
    public int getSpellid5() {
        return this.spellid5;
    }
    
    public void setSpellid5(int spellid5) {
        this.spellid5 = spellid5;
    }

    
    @Column(name="spelltrigger_5", nullable=false)
    public byte getSpelltrigger5() {
        return this.spelltrigger5;
    }
    
    public void setSpelltrigger5(byte spelltrigger5) {
        this.spelltrigger5 = spelltrigger5;
    }

    
    @Column(name="spellcharges_5", nullable=false)
    public byte getSpellcharges5() {
        return this.spellcharges5;
    }
    
    public void setSpellcharges5(byte spellcharges5) {
        this.spellcharges5 = spellcharges5;
    }

    
    @Column(name="spellppmRate_5", nullable=false, precision=12, scale=0)
    public float getSpellppmRate5() {
        return this.spellppmRate5;
    }
    
    public void setSpellppmRate5(float spellppmRate5) {
        this.spellppmRate5 = spellppmRate5;
    }

    
    @Column(name="spellcooldown_5", nullable=false)
    public int getSpellcooldown5() {
        return this.spellcooldown5;
    }
    
    public void setSpellcooldown5(int spellcooldown5) {
        this.spellcooldown5 = spellcooldown5;
    }

    
    @Column(name="spellcategory_5", nullable=false)
    public short getSpellcategory5() {
        return this.spellcategory5;
    }
    
    public void setSpellcategory5(short spellcategory5) {
        this.spellcategory5 = spellcategory5;
    }

    
    @Column(name="spellcategorycooldown_5", nullable=false)
    public int getSpellcategorycooldown5() {
        return this.spellcategorycooldown5;
    }
    
    public void setSpellcategorycooldown5(int spellcategorycooldown5) {
        this.spellcategorycooldown5 = spellcategorycooldown5;
    }

    
    @Column(name="bonding", nullable=false)
    public byte getBonding() {
        return this.bonding;
    }
    
    public void setBonding(byte bonding) {
        this.bonding = bonding;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="languageid", nullable=false)
    public byte getLanguageid() {
        return this.languageid;
    }
    
    public void setLanguageid(byte languageid) {
        this.languageid = languageid;
    }

    
    @Column(name="pagematerial", nullable=false)
    public byte getPagematerial() {
        return this.pagematerial;
    }
    
    public void setPagematerial(byte pagematerial) {
        this.pagematerial = pagematerial;
    }

    
    @Column(name="startquest", nullable=false)
    public int getStartquest() {
        return this.startquest;
    }
    
    public void setStartquest(int startquest) {
        this.startquest = startquest;
    }

    
    @Column(name="lockid", nullable=false)
    public int getLockid() {
        return this.lockid;
    }
    
    public void setLockid(int lockid) {
        this.lockid = lockid;
    }

    
    @Column(name="material", nullable=false)
    public byte getMaterial() {
        return this.material;
    }
    
    public void setMaterial(byte material) {
        this.material = material;
    }

    
    @Column(name="sheath", nullable=false)
    public byte getSheath() {
        return this.sheath;
    }
    
    public void setSheath(byte sheath) {
        this.sheath = sheath;
    }

    
    @Column(name="randomproperty", nullable=false)
    public int getRandomproperty() {
        return this.randomproperty;
    }
    
    public void setRandomproperty(int randomproperty) {
        this.randomproperty = randomproperty;
    }

    
    @Column(name="block", nullable=false)
    public int getBlock() {
        return this.block;
    }
    
    public void setBlock(int block) {
        this.block = block;
    }

    
    @Column(name="itemset", nullable=false)
    public int getItemset() {
        return this.itemset;
    }
    
    public void setItemset(int itemset) {
        this.itemset = itemset;
    }

    
    @Column(name="maxdurability", nullable=false)
    public short getMaxdurability() {
        return this.maxdurability;
    }
    
    public void setMaxdurability(short maxdurability) {
        this.maxdurability = maxdurability;
    }

    
    @Column(name="area", nullable=false)
    public int getArea() {
        return this.area;
    }
    
    public void setArea(int area) {
        this.area = area;
    }

    
    @Column(name="map", nullable=false)
    public short getMap() {
        return this.map;
    }
    
    public void setMap(short map) {
        this.map = map;
    }

    
    @Column(name="bagfamily", nullable=false)
    public int getBagfamily() {
        return this.bagfamily;
    }
    
    public void setBagfamily(int bagfamily) {
        this.bagfamily = bagfamily;
    }

    
    @Column(name="scriptname", nullable=false, length=64)
    public String getScriptname() {
        return this.scriptname;
    }
    
    public void setScriptname(String scriptname) {
        this.scriptname = scriptname;
    }

    
    @Column(name="disenchantid", nullable=false)
    public int getDisenchantid() {
        return this.disenchantid;
    }
    
    public void setDisenchantid(int disenchantid) {
        this.disenchantid = disenchantid;
    }

    
    @Column(name="foodtype", nullable=false)
    public byte getFoodtype() {
        return this.foodtype;
    }
    
    public void setFoodtype(byte foodtype) {
        this.foodtype = foodtype;
    }

    
    @Column(name="minmoneyloot", nullable=false)
    public int getMinmoneyloot() {
        return this.minmoneyloot;
    }
    
    public void setMinmoneyloot(int minmoneyloot) {
        this.minmoneyloot = minmoneyloot;
    }

    
    @Column(name="maxmoneyloot", nullable=false)
    public int getMaxmoneyloot() {
        return this.maxmoneyloot;
    }
    
    public void setMaxmoneyloot(int maxmoneyloot) {
        this.maxmoneyloot = maxmoneyloot;
    }

    
    @Column(name="duration", nullable=false)
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }

    
    @Column(name="extraflags", nullable=false)
    public boolean isExtraflags() {
        return this.extraflags;
    }
    
    public void setExtraflags(boolean extraflags) {
        this.extraflags = extraflags;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set<Startingequipment> getStartingequipments() {
        return this.startingequipments;
    }
    
    public void setStartingequipments(Set<Startingequipment> startingequipments) {
        this.startingequipments = startingequipments;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="spelltools", catalog="jangosworld", joinColumns = { 
        @JoinColumn(name="fk_item", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="fk_spell", nullable=false, updatable=false) })
    public Set<Spells> getSpellses() {
        return this.spellses;
    }
    
    public void setSpellses(Set<Spells> spellses) {
        this.spellses = spellses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set<Spellcomponents> getSpellcomponentses() {
        return this.spellcomponentses;
    }
    
    public void setSpellcomponentses(Set<Spellcomponents> spellcomponentses) {
        this.spellcomponentses = spellcomponentses;
    }




}


