package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name="language"
    ,catalog="jangosworld"
)
public class Language  implements java.io.Serializable {


     private int id;
     private String language;

    public Language() {
    }

	
    public Language(int id) {
        this.id = id;
    }
    public Language(int id, String language) {
       this.id = id;
       this.language = language;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="language", length=20)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }




}


