package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pagetext generated by hbm2java
 */
@Entity
@Table(name = "pagetext", catalog = "jangosworld"
)
public class Pagetext implements java.io.Serializable {

    private int id;
    private Pagetext pagetext;
    private String text;
    private Set<Item> items = new HashSet<Item>(0);
    private Set<Pagetext> pagetexts = new HashSet<Pagetext>(0);

    public Pagetext() {
    }

    public Pagetext(int id, String text) {
        this.id = id;
        this.text = text;
    }

    public Pagetext(int id, Pagetext pagetext, String text, Set<Item> items, Set<Pagetext> pagetexts) {
        this.id = id;
        this.pagetext = pagetext;
        this.text = text;
        this.items = items;
        this.pagetexts = pagetexts;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_next")
    public Pagetext getPagetext() {
        return this.pagetext;
    }

    public void setPagetext(Pagetext pagetext) {
        this.pagetext = pagetext;
    }

    @Column(name = "text", nullable = false, length = 1500)
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pagetext")
    public Set<Item> getItems() {
        return this.items;
    }

    public void setItems(Set<Item> items) {
        this.items = items;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pagetext")
    public Set<Pagetext> getPagetexts() {
        return this.pagetexts;
    }

    public void setPagetexts(Set<Pagetext> pagetexts) {
        this.pagetexts = pagetexts;
    }

}
