package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Powertype generated by hbm2java
 */
@Entity
@Table(name="powertype"
    ,catalog="jangosworld"
)
public class Powertype  implements java.io.Serializable {


     private byte id;
     private String power;
     private Set<Spells> spellses = new HashSet<Spells>(0);

    public Powertype() {
    }

	
    public Powertype(byte id) {
        this.id = id;
    }
    public Powertype(byte id, String power, Set<Spells> spellses) {
       this.id = id;
       this.power = power;
       this.spellses = spellses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="power", length=20)
    public String getPower() {
        return this.power;
    }
    
    public void setPower(String power) {
        this.power = power;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="powertype")
    public Set<Spells> getSpellses() {
        return this.spellses;
    }
    
    public void setSpellses(Set<Spells> spellses) {
        this.spellses = spellses;
    }




}


