package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Professions generated by hbm2java
 */
@Entity
@Table(name="professions"
    ,catalog="jangosworld"
)
public class Professions  implements java.io.Serializable {


     private byte id;
     private String professions;
     private Set<Startingequipment> startingequipments = new HashSet<Startingequipment>(0);
     private Set<Startingspell> startingspells = new HashSet<Startingspell>(0);

    public Professions() {
    }

	
    public Professions(byte id, String professions) {
        this.id = id;
        this.professions = professions;
    }
    public Professions(byte id, String professions, Set<Startingequipment> startingequipments, Set<Startingspell> startingspells) {
       this.id = id;
       this.professions = professions;
       this.startingequipments = startingequipments;
       this.startingspells = startingspells;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="professions", nullable=false, length=15)
    public String getProfessions() {
        return this.professions;
    }
    
    public void setProfessions(String professions) {
        this.professions = professions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="professions")
    public Set<Startingequipment> getStartingequipments() {
        return this.startingequipments;
    }
    
    public void setStartingequipments(Set<Startingequipment> startingequipments) {
        this.startingequipments = startingequipments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="professions")
    public Set<Startingspell> getStartingspells() {
        return this.startingspells;
    }
    
    public void setStartingspells(Set<Startingspell> startingspells) {
        this.startingspells = startingspells;
    }




}


