package eu.jangos.realm.model.world;
// Generated 19-f�vr.-2016 21:00:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Race generated by hbm2java
 */
public class Race  implements java.io.Serializable {


     private byte id;
     private String race;     
     private float positionX;
     private float positionY;
     private float positionZ;     
     private float orientation;
     private int fkDbcMap;
     private int fkDbcZone;
     
     private Set startingequipments = new HashSet(0);

    public Race() {
    }

    public Race(byte id, String race, float positionX, float positionY, float positionZ, float orientation, int fkDbcMap, int fkDbcZone) {
        this.id = id;
        this.race = race;
        this.positionX = positionX;
        this.positionY = positionY;
        this.positionZ = positionZ;
        this.orientation = orientation;
        this.fkDbcMap = fkDbcMap;
        this.fkDbcZone = fkDbcZone;
    }	
    
    public Race(byte id, String race, float positionX, float positionY, float positionZ, float orientation, int fkDbcMap, int fkDbcZone, Set startingequipments) {
        this.id = id;
        this.race = race;
        this.positionX = positionX;
        this.positionY = positionY;
        this.positionZ = positionZ;
        this.orientation = orientation;
        this.fkDbcMap = fkDbcMap;
        this.fkDbcZone = fkDbcZone;
        this.startingequipments = startingequipments;
    }	        
   
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }
    public String getRace() {
        return this.race;
    }
    
    public void setRace(String race) {
        this.race = race;
    }

    public float getPositionX() {
        return positionX;
    }

    public void setPositionX(float positionX) {
        this.positionX = positionX;
    }

    public float getPositionY() {
        return positionY;
    }

    public void setPositionY(float positionY) {
        this.positionY = positionY;
    }

    public float getPositionZ() {
        return positionZ;
    }

    public void setPositionZ(float positionZ) {
        this.positionZ = positionZ;
    }

    public float getOrientation() {
        return orientation;
    }

    public void setOrientation(float orientation) {
        this.orientation = orientation;
    }

    public int getFkDbcMap() {
        return fkDbcMap;
    }

    public void setFkDbcMap(int fkDbcMap) {
        this.fkDbcMap = fkDbcMap;
    }

    public int getFkDbcZone() {
        return fkDbcZone;
    }

    public void setFkDbcZone(int fkDbcZone) {
        this.fkDbcZone = fkDbcZone;
    }
    
    
    
    public Set getStartingequipments() {
        return this.startingequipments;
    }
    
    public void setStartingequipments(Set startingequipments) {
        this.startingequipments = startingequipments;
    }




}


