package eu.jangos.realm.model.world;
// Generated 19-févr.-2016 21:00:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Race generated by hbm2java
 */
public class Race  implements java.io.Serializable {


     private byte id;
     private String race;
     private Set startingequipments = new HashSet(0);

    public Race() {
    }

	
    public Race(byte id, String race) {
        this.id = id;
        this.race = race;
    }
    public Race(byte id, String race, Set startingequipments) {
       this.id = id;
       this.race = race;
       this.startingequipments = startingequipments;
    }
   
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }
    public String getRace() {
        return this.race;
    }
    
    public void setRace(String race) {
        this.race = race;
    }
    public Set getStartingequipments() {
        return this.startingequipments;
    }
    
    public void setStartingequipments(Set startingequipments) {
        this.startingequipments = startingequipments;
    }




}


