package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Race generated by hbm2java
 */
@Entity
@Table(name="race"
    ,catalog="jangosworld"
)
public class Race  implements java.io.Serializable {


     private byte id;
     private String race;
     private float positionX;
     private float positionY;
     private float positionZ;
     private int fkDbcMap;
     private float orientation;
     private int fkDbcZone;
     private Set<Startingequipment> startingequipments = new HashSet<Startingequipment>(0);
     private Set<Startingspell> startingspells = new HashSet<Startingspell>(0);

    public Race() {
    }

	
    public Race(byte id, String race, float positionX, float positionY, float positionZ, int fkDbcMap, float orientation, int fkDbcZone) {
        this.id = id;
        this.race = race;
        this.positionX = positionX;
        this.positionY = positionY;
        this.positionZ = positionZ;
        this.fkDbcMap = fkDbcMap;
        this.orientation = orientation;
        this.fkDbcZone = fkDbcZone;
    }
    public Race(byte id, String race, float positionX, float positionY, float positionZ, int fkDbcMap, float orientation, int fkDbcZone, Set<Startingequipment> startingequipments, Set<Startingspell> startingspells) {
       this.id = id;
       this.race = race;
       this.positionX = positionX;
       this.positionY = positionY;
       this.positionZ = positionZ;
       this.fkDbcMap = fkDbcMap;
       this.orientation = orientation;
       this.fkDbcZone = fkDbcZone;
       this.startingequipments = startingequipments;
       this.startingspells = startingspells;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="race", nullable=false, length=15)
    public String getRace() {
        return this.race;
    }
    
    public void setRace(String race) {
        this.race = race;
    }

    
    @Column(name="position_x", nullable=false, precision=12, scale=0)
    public float getPositionX() {
        return this.positionX;
    }
    
    public void setPositionX(float positionX) {
        this.positionX = positionX;
    }

    
    @Column(name="position_y", nullable=false, precision=12, scale=0)
    public float getPositionY() {
        return this.positionY;
    }
    
    public void setPositionY(float positionY) {
        this.positionY = positionY;
    }

    
    @Column(name="position_z", nullable=false, precision=12, scale=0)
    public float getPositionZ() {
        return this.positionZ;
    }
    
    public void setPositionZ(float positionZ) {
        this.positionZ = positionZ;
    }

    
    @Column(name="fk_dbc_map", nullable=false)
    public int getFkDbcMap() {
        return this.fkDbcMap;
    }
    
    public void setFkDbcMap(int fkDbcMap) {
        this.fkDbcMap = fkDbcMap;
    }

    
    @Column(name="orientation", nullable=false, precision=12, scale=0)
    public float getOrientation() {
        return this.orientation;
    }
    
    public void setOrientation(float orientation) {
        this.orientation = orientation;
    }

    
    @Column(name="fk_dbc_zone", nullable=false)
    public int getFkDbcZone() {
        return this.fkDbcZone;
    }
    
    public void setFkDbcZone(int fkDbcZone) {
        this.fkDbcZone = fkDbcZone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="race")
    public Set<Startingequipment> getStartingequipments() {
        return this.startingequipments;
    }
    
    public void setStartingequipments(Set<Startingequipment> startingequipments) {
        this.startingequipments = startingequipments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="race")
    public Set<Startingspell> getStartingspells() {
        return this.startingspells;
    }
    
    public void setStartingspells(Set<Startingspell> startingspells) {
        this.startingspells = startingspells;
    }




}


