package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shapeshift generated by hbm2java
 */
@Entity
@Table(name="shapeshift"
    ,catalog="jangosworld"
)
public class Shapeshift  implements java.io.Serializable {


     private byte id;
     private String shapeshift;
     private Byte actionBar;
     private Byte fkCreaturetype;
     private Boolean allowedMount;
     private Boolean unshapeOnCast;
     private Boolean warrior;
     private Boolean priest;
     private Boolean unknown3;
     private Boolean modifyApforAgility;
     private Boolean unknown5;
     private Set<Spellshapeshift> spellshapeshifts = new HashSet<Spellshapeshift>(0);

    public Shapeshift() {
    }

	
    public Shapeshift(byte id, String shapeshift) {
        this.id = id;
        this.shapeshift = shapeshift;
    }
    public Shapeshift(byte id, String shapeshift, Byte actionBar, Byte fkCreaturetype, Boolean allowedMount, Boolean unshapeOnCast, Boolean warrior, Boolean priest, Boolean unknown3, Boolean modifyApforAgility, Boolean unknown5, Set<Spellshapeshift> spellshapeshifts) {
       this.id = id;
       this.shapeshift = shapeshift;
       this.actionBar = actionBar;
       this.fkCreaturetype = fkCreaturetype;
       this.allowedMount = allowedMount;
       this.unshapeOnCast = unshapeOnCast;
       this.warrior = warrior;
       this.priest = priest;
       this.unknown3 = unknown3;
       this.modifyApforAgility = modifyApforAgility;
       this.unknown5 = unknown5;
       this.spellshapeshifts = spellshapeshifts;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="shapeshift", nullable=false, length=45)
    public String getShapeshift() {
        return this.shapeshift;
    }
    
    public void setShapeshift(String shapeshift) {
        this.shapeshift = shapeshift;
    }

    
    @Column(name="actionBar")
    public Byte getActionBar() {
        return this.actionBar;
    }
    
    public void setActionBar(Byte actionBar) {
        this.actionBar = actionBar;
    }

    
    @Column(name="fk_creaturetype")
    public Byte getFkCreaturetype() {
        return this.fkCreaturetype;
    }
    
    public void setFkCreaturetype(Byte fkCreaturetype) {
        this.fkCreaturetype = fkCreaturetype;
    }

    
    @Column(name="allowedMount")
    public Boolean getAllowedMount() {
        return this.allowedMount;
    }
    
    public void setAllowedMount(Boolean allowedMount) {
        this.allowedMount = allowedMount;
    }

    
    @Column(name="unshapeOnCast")
    public Boolean getUnshapeOnCast() {
        return this.unshapeOnCast;
    }
    
    public void setUnshapeOnCast(Boolean unshapeOnCast) {
        this.unshapeOnCast = unshapeOnCast;
    }

    
    @Column(name="warrior")
    public Boolean getWarrior() {
        return this.warrior;
    }
    
    public void setWarrior(Boolean warrior) {
        this.warrior = warrior;
    }

    
    @Column(name="priest")
    public Boolean getPriest() {
        return this.priest;
    }
    
    public void setPriest(Boolean priest) {
        this.priest = priest;
    }

    
    @Column(name="unknown3")
    public Boolean getUnknown3() {
        return this.unknown3;
    }
    
    public void setUnknown3(Boolean unknown3) {
        this.unknown3 = unknown3;
    }

    
    @Column(name="modifyAPforAgility")
    public Boolean getModifyApforAgility() {
        return this.modifyApforAgility;
    }
    
    public void setModifyApforAgility(Boolean modifyApforAgility) {
        this.modifyApforAgility = modifyApforAgility;
    }

    
    @Column(name="unknown5")
    public Boolean getUnknown5() {
        return this.unknown5;
    }
    
    public void setUnknown5(Boolean unknown5) {
        this.unknown5 = unknown5;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shapeshift")
    public Set<Spellshapeshift> getSpellshapeshifts() {
        return this.spellshapeshifts;
    }
    
    public void setSpellshapeshifts(Set<Spellshapeshift> spellshapeshifts) {
        this.spellshapeshifts = spellshapeshifts;
    }




}


