package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Spellfocus generated by hbm2java
 */
@Entity
@Table(name="spellfocus"
    ,catalog="jangosworld"
)
public class Spellfocus  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Spells> spellses = new HashSet<Spells>(0);

    public Spellfocus() {
    }

	
    public Spellfocus(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Spellfocus(int id, String name, Set<Spells> spellses) {
       this.id = id;
       this.name = name;
       this.spellses = spellses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="spellfocus")
    public Set<Spells> getSpellses() {
        return this.spellses;
    }
    
    public void setSpellses(Set<Spells> spellses) {
        this.spellses = spellses;
    }




}


