package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Spellrange generated by hbm2java
 */
@Entity
@Table(name="spellrange"
    ,catalog="jangosworld"
)
public class Spellrange  implements java.io.Serializable {


     private byte id;
     private String range;
     private Short minRange;
     private Short maxRange;
     private Set<Spells> spellses = new HashSet<Spells>(0);

    public Spellrange() {
    }

	
    public Spellrange(byte id, String range) {
        this.id = id;
        this.range = range;
    }
    public Spellrange(byte id, String range, Short minRange, Short maxRange, Set<Spells> spellses) {
       this.id = id;
       this.range = range;
       this.minRange = minRange;
       this.maxRange = maxRange;
       this.spellses = spellses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="range", nullable=false, length=45)
    public String getRange() {
        return this.range;
    }
    
    public void setRange(String range) {
        this.range = range;
    }

    
    @Column(name="minRange")
    public Short getMinRange() {
        return this.minRange;
    }
    
    public void setMinRange(Short minRange) {
        this.minRange = minRange;
    }

    
    @Column(name="maxRange")
    public Short getMaxRange() {
        return this.maxRange;
    }
    
    public void setMaxRange(Short maxRange) {
        this.maxRange = maxRange;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="spellrange")
    public Set<Spells> getSpellses() {
        return this.spellses;
    }
    
    public void setSpellses(Set<Spells> spellses) {
        this.spellses = spellses;
    }




}


