package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Spellitemsubclass generated by hbm2java
 */
@Entity
@Table(name = "spellitemsubclass", catalog = "jangosworld"
)
public class Spellitemsubclass implements java.io.Serializable {

    private Integer id;
    private Itemsubclass itemsubclass;
    private Spells spells;

    public Spellitemsubclass() {
    }

    public Spellitemsubclass(Itemsubclass itemsubclass, Spells spells) {
        this.itemsubclass = itemsubclass;
        this.spells = spells;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "fk_itemclass", referencedColumnName = "fk_itemclass", nullable = false),
        @JoinColumn(name = "fk_itemsubclass", referencedColumnName = "id", nullable = false)})
    public Itemsubclass getItemsubclass() {
        return this.itemsubclass;
    }

    public void setItemsubclass(Itemsubclass itemsubclass) {
        this.itemsubclass = itemsubclass;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_spell", nullable = false)
    public Spells getSpells() {
        return this.spells;
    }

    public void setSpells(Spells spells) {
        this.spells = spells;
    }

}
