package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpellspelleffectsId generated by hbm2java
 */
@Embeddable
public class SpellspelleffectsId  implements java.io.Serializable {


     private int fkSpell;
     private short fkEffect;
     private byte sequence;

    public SpellspelleffectsId() {
    }

    public SpellspelleffectsId(int fkSpell, short fkEffect, byte sequence) {
       this.fkSpell = fkSpell;
       this.fkEffect = fkEffect;
       this.sequence = sequence;
    }
   


    @Column(name="fk_spell", nullable=false)
    public int getFkSpell() {
        return this.fkSpell;
    }
    
    public void setFkSpell(int fkSpell) {
        this.fkSpell = fkSpell;
    }


    @Column(name="fk_effect", nullable=false)
    public short getFkEffect() {
        return this.fkEffect;
    }
    
    public void setFkEffect(short fkEffect) {
        this.fkEffect = fkEffect;
    }


    @Column(name="sequence", nullable=false)
    public byte getSequence() {
        return this.sequence;
    }
    
    public void setSequence(byte sequence) {
        this.sequence = sequence;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SpellspelleffectsId) ) return false;
		 SpellspelleffectsId castOther = ( SpellspelleffectsId ) other; 
         
		 return (this.getFkSpell()==castOther.getFkSpell())
 && (this.getFkEffect()==castOther.getFkEffect())
 && (this.getSequence()==castOther.getSequence());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkSpell();
         result = 37 * result + this.getFkEffect();
         result = 37 * result + this.getSequence();
         return result;
   }   


}


