package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Spellshapeshift generated by hbm2java
 */
@Entity
@Table(name="spellshapeshift"
    ,catalog="jangosworld"
)
public class Spellshapeshift  implements java.io.Serializable {


     private SpellshapeshiftId id;
     private Shapeshift shapeshift;
     private Spells spells;
     private byte excluded;

    public Spellshapeshift() {
    }

    public Spellshapeshift(SpellshapeshiftId id, Shapeshift shapeshift, Spells spells, byte excluded) {
       this.id = id;
       this.shapeshift = shapeshift;
       this.spells = spells;
       this.excluded = excluded;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkSpell", column=@Column(name="fk_spell", nullable=false) ), 
        @AttributeOverride(name="fkShapeshift", column=@Column(name="fk_shapeshift", nullable=false) ) } )
    public SpellshapeshiftId getId() {
        return this.id;
    }
    
    public void setId(SpellshapeshiftId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_shapeshift", nullable=false, insertable=false, updatable=false)
    public Shapeshift getShapeshift() {
        return this.shapeshift;
    }
    
    public void setShapeshift(Shapeshift shapeshift) {
        this.shapeshift = shapeshift;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_spell", nullable=false, insertable=false, updatable=false)
    public Spells getSpells() {
        return this.spells;
    }
    
    public void setSpells(Spells spells) {
        this.spells = spells;
    }

    
    @Column(name="excluded", nullable=false)
    public byte getExcluded() {
        return this.excluded;
    }
    
    public void setExcluded(byte excluded) {
        this.excluded = excluded;
    }




}


