package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Spellcomponents generated by hbm2java
 */
@Entity
@Table(name="spellcomponents"
    ,catalog="jangosworld"
)
public class Spellcomponents  implements java.io.Serializable {


     private SpellcomponentsId id;
     private Item item;
     private Spells spells;
     private short amount;

    public Spellcomponents() {
    }

    public Spellcomponents(SpellcomponentsId id, Item item, Spells spells, short amount) {
       this.id = id;
       this.item = item;
       this.spells = spells;
       this.amount = amount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkSpell", column=@Column(name="fk_spell", nullable=false) ), 
        @AttributeOverride(name="fkItem", column=@Column(name="fk_item", nullable=false) ) } )
    public SpellcomponentsId getId() {
        return this.id;
    }
    
    public void setId(SpellcomponentsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_item", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_spell", nullable=false, insertable=false, updatable=false)
    public Spells getSpells() {
        return this.spells;
    }
    
    public void setSpells(Spells spells) {
        this.spells = spells;
    }

    
    @Column(name="amount", nullable=false)
    public short getAmount() {
        return this.amount;
    }
    
    public void setAmount(short amount) {
        this.amount = amount;
    }




}


