package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Spellfamily generated by hbm2java
 */
@Entity
@Table(name="spellfamily"
    ,catalog="jangosworld"
)
public class Spellfamily  implements java.io.Serializable {


     private byte id;
     private String family;
     private Set<Spells> spellses = new HashSet<Spells>(0);

    public Spellfamily() {
    }

	
    public Spellfamily(byte id, String family) {
        this.id = id;
        this.family = family;
    }
    public Spellfamily(byte id, String family, Set<Spells> spellses) {
       this.id = id;
       this.family = family;
       this.spellses = spellses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="family", nullable=false, length=45)
    public String getFamily() {
        return this.family;
    }
    
    public void setFamily(String family) {
        this.family = family;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="spellfamily")
    public Set<Spells> getSpellses() {
        return this.spellses;
    }
    
    public void setSpellses(Set<Spells> spellses) {
        this.spellses = spellses;
    }




}


