package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Spellduration generated by hbm2java
 */
@Entity
@Table(name="spellduration"
    ,catalog="jangosworld"
)
public class Spellduration  implements java.io.Serializable {


     private short id;
     private Integer duration;
     private Integer durationPerLevel;
     private Integer durationMax;
     private Set<Spells> spellses = new HashSet<Spells>(0);

    public Spellduration() {
    }

	
    public Spellduration(short id) {
        this.id = id;
    }
    public Spellduration(short id, Integer duration, Integer durationPerLevel, Integer durationMax, Set<Spells> spellses) {
       this.id = id;
       this.duration = duration;
       this.durationPerLevel = durationPerLevel;
       this.durationMax = durationMax;
       this.spellses = spellses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }

    
    @Column(name="duration")
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    
    @Column(name="durationPerLevel")
    public Integer getDurationPerLevel() {
        return this.durationPerLevel;
    }
    
    public void setDurationPerLevel(Integer durationPerLevel) {
        this.durationPerLevel = durationPerLevel;
    }

    
    @Column(name="durationMax")
    public Integer getDurationMax() {
        return this.durationMax;
    }
    
    public void setDurationMax(Integer durationMax) {
        this.durationMax = durationMax;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="spellduration")
    public Set<Spells> getSpellses() {
        return this.spellses;
    }
    
    public void setSpellses(Set<Spells> spellses) {
        this.spellses = spellses;
    }




}


