package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Spelleffects generated by hbm2java
 */
@Entity
@Table(name="spelleffects"
    ,catalog="jangosworld"
)
public class Spelleffects  implements java.io.Serializable {


     private short id;
     private String effect;
     private Set<Spellspelleffects> spellspelleffectses = new HashSet<Spellspelleffects>(0);

    public Spelleffects() {
    }

	
    public Spelleffects(short id, String effect) {
        this.id = id;
        this.effect = effect;
    }
    public Spelleffects(short id, String effect, Set<Spellspelleffects> spellspelleffectses) {
       this.id = id;
       this.effect = effect;
       this.spellspelleffectses = spellspelleffectses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }

    
    @Column(name="effect", nullable=false, length=45)
    public String getEffect() {
        return this.effect;
    }
    
    public void setEffect(String effect) {
        this.effect = effect;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="spelleffects")
    public Set<Spellspelleffects> getSpellspelleffectses() {
        return this.spellspelleffectses;
    }
    
    public void setSpellspelleffectses(Set<Spellspelleffects> spellspelleffectses) {
        this.spellspelleffectses = spellspelleffectses;
    }




}


