package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Spellauras generated by hbm2java
 */
@Entity
@Table(name="spellauras"
    ,catalog="jangosworld"
)
public class Spellauras  implements java.io.Serializable {


     private short id;
     private String aura;
     private Set<Spellspelleffects> spellspelleffectses = new HashSet<Spellspelleffects>(0);

    public Spellauras() {
    }

	
    public Spellauras(short id, String aura) {
        this.id = id;
        this.aura = aura;
    }
    public Spellauras(short id, String aura, Set<Spellspelleffects> spellspelleffectses) {
       this.id = id;
       this.aura = aura;
       this.spellspelleffectses = spellspelleffectses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }

    
    @Column(name="aura", nullable=false, length=45)
    public String getAura() {
        return this.aura;
    }
    
    public void setAura(String aura) {
        this.aura = aura;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="spellauras")
    public Set<Spellspelleffects> getSpellspelleffectses() {
        return this.spellspelleffectses;
    }
    
    public void setSpellspelleffectses(Set<Spellspelleffects> spellspelleffectses) {
        this.spellspelleffectses = spellspelleffectses;
    }




}


