package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Spelldamagetype generated by hbm2java
 */
@Entity
@Table(name="spelldamagetype"
    ,catalog="jangosworld"
)
public class Spelldamagetype  implements java.io.Serializable {


     private byte id;
     private String type;
     private Set<Spells> spellses = new HashSet<Spells>(0);

    public Spelldamagetype() {
    }

	
    public Spelldamagetype(byte id) {
        this.id = id;
    }
    public Spelldamagetype(byte id, String type, Set<Spells> spellses) {
       this.id = id;
       this.type = type;
       this.spellses = spellses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="spelldamagetype")
    public Set<Spells> getSpellses() {
        return this.spellses;
    }
    
    public void setSpellses(Set<Spells> spellses) {
        this.spellses = spellses;
    }




}


