package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpellcomponentsId generated by hbm2java
 */
@Embeddable
public class SpellcomponentsId  implements java.io.Serializable {


     private int fkSpell;
     private int fkItem;

    public SpellcomponentsId() {
    }

    public SpellcomponentsId(int fkSpell, int fkItem) {
       this.fkSpell = fkSpell;
       this.fkItem = fkItem;
    }
   


    @Column(name="fk_spell", nullable=false)
    public int getFkSpell() {
        return this.fkSpell;
    }
    
    public void setFkSpell(int fkSpell) {
        this.fkSpell = fkSpell;
    }


    @Column(name="fk_item", nullable=false)
    public int getFkItem() {
        return this.fkItem;
    }
    
    public void setFkItem(int fkItem) {
        this.fkItem = fkItem;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SpellcomponentsId) ) return false;
		 SpellcomponentsId castOther = ( SpellcomponentsId ) other; 
         
		 return (this.getFkSpell()==castOther.getFkSpell())
 && (this.getFkItem()==castOther.getFkItem());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkSpell();
         result = 37 * result + this.getFkItem();
         return result;
   }   


}


