package eu.jangos.realm.model.world;
// Generated 27-févr.-2016 16:07:33 by Hibernate Tools 4.3.1



/**
 * Startingequipment generated by hbm2java
 */
public class Startingequipment  implements java.io.Serializable {


     private StartingequipmentId id;
     private Gender gender;
     private Item item;
     private Professions professions;
     private Race race;

    public Startingequipment() {
    }

    public Startingequipment(StartingequipmentId id, Gender gender, Item item, Professions professions, Race race) {
       this.id = id;
       this.gender = gender;
       this.item = item;
       this.professions = professions;
       this.race = race;
    }
   
    public StartingequipmentId getId() {
        return this.id;
    }
    
    public void setId(StartingequipmentId id) {
        this.id = id;
    }
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Professions getProfessions() {
        return this.professions;
    }
    
    public void setProfessions(Professions professions) {
        this.professions = professions;
    }
    public Race getRace() {
        return this.race;
    }
    
    public void setRace(Race race) {
        this.race = race;
    }




}


