package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StartingspellId generated by hbm2java
 */
@Embeddable
public class StartingspellId  implements java.io.Serializable {


     private byte fkClass;
     private byte fkRace;
     private int fkDbcSpell;

    public StartingspellId() {
    }

    public StartingspellId(byte fkClass, byte fkRace, int fkDbcSpell) {
       this.fkClass = fkClass;
       this.fkRace = fkRace;
       this.fkDbcSpell = fkDbcSpell;
    }
   


    @Column(name="fk_class", nullable=false)
    public byte getFkClass() {
        return this.fkClass;
    }
    
    public void setFkClass(byte fkClass) {
        this.fkClass = fkClass;
    }


    @Column(name="fk_race", nullable=false)
    public byte getFkRace() {
        return this.fkRace;
    }
    
    public void setFkRace(byte fkRace) {
        this.fkRace = fkRace;
    }


    @Column(name="fk_dbc_spell", nullable=false)
    public int getFkDbcSpell() {
        return this.fkDbcSpell;
    }
    
    public void setFkDbcSpell(int fkDbcSpell) {
        this.fkDbcSpell = fkDbcSpell;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StartingspellId) ) return false;
		 StartingspellId castOther = ( StartingspellId ) other; 
         
		 return (this.getFkClass()==castOther.getFkClass())
 && (this.getFkRace()==castOther.getFkRace())
 && (this.getFkDbcSpell()==castOther.getFkDbcSpell());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkClass();
         result = 37 * result + this.getFkRace();
         result = 37 * result + this.getFkDbcSpell();
         return result;
   }   


}


