package eu.jangos.realm.model.world;




/**
 * Startingspell generated by hbm2java
 */
public class Startingspell  implements java.io.Serializable {


     private StartingspellId id;
     private Professions professions;
     private Race race;

    public Startingspell() {
    }

    public Startingspell(StartingspellId id, Professions professions, Race race) {
       this.id = id;
       this.professions = professions;
       this.race = race;
    }
   
    public StartingspellId getId() {
        return this.id;
    }
    
    public void setId(StartingspellId id) {
        this.id = id;
    }
    public Professions getProfessions() {
        return this.professions;
    }
    
    public void setProfessions(Professions professions) {
        this.professions = professions;
    }
    public Race getRace() {
        return this.race;
    }
    
    public void setRace(Race race) {
        this.race = race;
    }




}


