package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Startingequipment generated by hbm2java
 */
@Entity
@Table(name="startingequipment"
    ,catalog="jangosworld"
)
public class Startingequipment  implements java.io.Serializable {


     private StartingequipmentId id;
     private Gender gender;
     private Item item;
     private Professions professions;
     private Race race;

    public Startingequipment() {
    }

    public Startingequipment(StartingequipmentId id, Gender gender, Item item, Professions professions, Race race) {
       this.id = id;
       this.gender = gender;
       this.item = item;
       this.professions = professions;
       this.race = race;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkClass", column=@Column(name="fk_class", nullable=false) ), 
        @AttributeOverride(name="fkItem", column=@Column(name="fk_item", nullable=false) ), 
        @AttributeOverride(name="fkRace", column=@Column(name="fk_race", nullable=false) ), 
        @AttributeOverride(name="fkGender", column=@Column(name="fk_gender", nullable=false) ) } )
    public StartingequipmentId getId() {
        return this.id;
    }
    
    public void setId(StartingequipmentId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_gender", nullable=false, insertable=false, updatable=false)
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_item", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_class", nullable=false, insertable=false, updatable=false)
    public Professions getProfessions() {
        return this.professions;
    }
    
    public void setProfessions(Professions professions) {
        this.professions = professions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_race", nullable=false, insertable=false, updatable=false)
    public Race getRace() {
        return this.race;
    }
    
    public void setRace(Race race) {
        this.race = race;
    }




}


