package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Startingspell generated by hbm2java
 */
@Entity
@Table(name="startingspell"
    ,catalog="jangosworld"
)
public class Startingspell  implements java.io.Serializable {


     private StartingspellId id;
     private Professions professions;
     private Race race;
     private Spells spells;

    public Startingspell() {
    }

    public Startingspell(StartingspellId id, Professions professions, Race race, Spells spells) {
       this.id = id;
       this.professions = professions;
       this.race = race;
       this.spells = spells;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkClass", column=@Column(name="fk_class", nullable=false) ), 
        @AttributeOverride(name="fkRace", column=@Column(name="fk_race", nullable=false) ), 
        @AttributeOverride(name="fkDbcSpell", column=@Column(name="fk_dbc_spell", nullable=false) ) } )
    public StartingspellId getId() {
        return this.id;
    }
    
    public void setId(StartingspellId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_class", nullable=false, insertable=false, updatable=false)
    public Professions getProfessions() {
        return this.professions;
    }
    
    public void setProfessions(Professions professions) {
        this.professions = professions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_race", nullable=false, insertable=false, updatable=false)
    public Race getRace() {
        return this.race;
    }
    
    public void setRace(Race race) {
        this.race = race;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fk_dbc_spell", nullable=false, insertable=false, updatable=false)
    public Spells getSpells() {
        return this.spells;
    }
    
    public void setSpells(Spells spells) {
        this.spells = spells;
    }




}


