package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StartingequipmentId generated by hbm2java
 */
@Embeddable
public class StartingequipmentId  implements java.io.Serializable {


     private byte fkClass;
     private int fkItem;
     private byte fkRace;
     private byte fkGender;

    public StartingequipmentId() {
    }

    public StartingequipmentId(byte fkClass, int fkItem, byte fkRace, byte fkGender) {
       this.fkClass = fkClass;
       this.fkItem = fkItem;
       this.fkRace = fkRace;
       this.fkGender = fkGender;
    }
   


    @Column(name="fk_class", nullable=false)
    public byte getFkClass() {
        return this.fkClass;
    }
    
    public void setFkClass(byte fkClass) {
        this.fkClass = fkClass;
    }


    @Column(name="fk_item", nullable=false)
    public int getFkItem() {
        return this.fkItem;
    }
    
    public void setFkItem(int fkItem) {
        this.fkItem = fkItem;
    }


    @Column(name="fk_race", nullable=false)
    public byte getFkRace() {
        return this.fkRace;
    }
    
    public void setFkRace(byte fkRace) {
        this.fkRace = fkRace;
    }


    @Column(name="fk_gender", nullable=false)
    public byte getFkGender() {
        return this.fkGender;
    }
    
    public void setFkGender(byte fkGender) {
        this.fkGender = fkGender;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StartingequipmentId) ) return false;
		 StartingequipmentId castOther = ( StartingequipmentId ) other; 
         
		 return (this.getFkClass()==castOther.getFkClass())
 && (this.getFkItem()==castOther.getFkItem())
 && (this.getFkRace()==castOther.getFkRace())
 && (this.getFkGender()==castOther.getFkGender());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkClass();
         result = 37 * result + this.getFkItem();
         result = 37 * result + this.getFkRace();
         result = 37 * result + this.getFkGender();
         return result;
   }   


}


