package eu.jangos.realm.model.world;
// Generated 06-mai-2016 21:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Targets generated by hbm2java
 */
@Entity
@Table(name="targets"
    ,catalog="jangosworld"
)
public class Targets  implements java.io.Serializable {


     private byte id;
     private String target;
     private Set<Spellspelleffects> spellspelleffectsesForFkTargetA = new HashSet<Spellspelleffects>(0);
     private Set<Spellspelleffects> spellspelleffectsesForFkTargetB = new HashSet<Spellspelleffects>(0);

    public Targets() {
    }

	
    public Targets(byte id) {
        this.id = id;
    }
    public Targets(byte id, String target, Set<Spellspelleffects> spellspelleffectsesForFkTargetA, Set<Spellspelleffects> spellspelleffectsesForFkTargetB) {
       this.id = id;
       this.target = target;
       this.spellspelleffectsesForFkTargetA = spellspelleffectsesForFkTargetA;
       this.spellspelleffectsesForFkTargetB = spellspelleffectsesForFkTargetB;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="target", length=50)
    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="targetsByFkTargetA")
    public Set<Spellspelleffects> getSpellspelleffectsesForFkTargetA() {
        return this.spellspelleffectsesForFkTargetA;
    }
    
    public void setSpellspelleffectsesForFkTargetA(Set<Spellspelleffects> spellspelleffectsesForFkTargetA) {
        this.spellspelleffectsesForFkTargetA = spellspelleffectsesForFkTargetA;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="targetsByFkTargetB")
    public Set<Spellspelleffects> getSpellspelleffectsesForFkTargetB() {
        return this.spellspelleffectsesForFkTargetB;
    }
    
    public void setSpellspelleffectsesForFkTargetB(Set<Spellspelleffects> spellspelleffectsesForFkTargetB) {
        this.spellspelleffectsesForFkTargetB = spellspelleffectsesForFkTargetB;
    }




}


