package eu.jangos.realm.model.world;

import java.util.Objects;

/**
 * Parameter1 generated by hbm2java
 */
public class WParameter  implements java.io.Serializable {


     private Integer id;
     private String param;
     private String val;

    public WParameter() {
    }

    public WParameter(String param, String val) {
       this.param = param;
       this.val = val;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getParam() {
        return this.param;
    }
    
    public void setParam(String param) {
        this.param = param;
    }
    public String getVal() {
        return this.val;
    }
    
    public void setVal(String val) {
        this.val = val;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final WParameter other = (WParameter) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }
}


