package eu.jangos.realm.model.world;
// Generated 27-févr.-2016 16:07:33 by Hibernate Tools 4.3.1



/**
 * WParameter generated by hbm2java
 */
public class WParameter  implements java.io.Serializable {


     private Integer id;
     private String param;
     private String val;

    public WParameter() {
    }

    public WParameter(String param, String val) {
       this.param = param;
       this.val = val;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getParam() {
        return this.param;
    }
    
    public void setParam(String param) {
        this.param = param;
    }
    public String getVal() {
        return this.val;
    }
    
    public void setVal(String val) {
        this.val = val;
    }




}


