package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Actionbar generated by hbm2java
 */
@Entity
@Table(name="actionbar"
    ,catalog="jangoscharacters"
)
public class Actionbar  implements java.io.Serializable {


     private ActionbarId id;
     private Characters characters;
     private int action;
     private byte type;

    public Actionbar() {
    }

    public Actionbar(ActionbarId id, Characters characters, int action, byte type) {
       this.id = id;
       this.characters = characters;
       this.action = action;
       this.type = type;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkGuid", column=@Column(name="fk_guid", nullable=false) ), 
        @AttributeOverride(name="button", column=@Column(name="button", nullable=false) ) } )
    public ActionbarId getId() {
        return this.id;
    }
    
    public void setId(ActionbarId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_guid", nullable=false, insertable=false, updatable=false)
    public Characters getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Characters characters) {
        this.characters = characters;
    }

    
    @Column(name="action", nullable=false)
    public int getAction() {
        return this.action;
    }
    
    public void setAction(int action) {
        this.action = action;
    }

    
    @Column(name="type", nullable=false)
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }




}


