package eu.jangos.realm.model.characters;




/**
 * ActionbarId generated by hbm2java
 */
public class ActionbarId  implements java.io.Serializable {


     private int fkGuid;
     private byte button;

    public ActionbarId() {
    }

    public ActionbarId(int fkGuid, byte button) {
       this.fkGuid = fkGuid;
       this.button = button;
    }
   
    public int getFkGuid() {
        return this.fkGuid;
    }
    
    public void setFkGuid(int fkGuid) {
        this.fkGuid = fkGuid;
    }
    public byte getButton() {
        return this.button;
    }
    
    public void setButton(byte button) {
        this.button = button;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActionbarId) ) return false;
		 ActionbarId castOther = ( ActionbarId ) other; 
         
		 return (this.getFkGuid()==castOther.getFkGuid())
 && (this.getButton()==castOther.getButton());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkGuid();
         result = 37 * result + this.getButton();
         return result;
   }   


}


