package eu.jangos.realm.model.characters;
// Generated 19-févr.-2016 21:17:55 by Hibernate Tools 4.3.1



/**
 * Actionbar generated by hbm2java
 */
public class Actionbar  implements java.io.Serializable {


     private ActionbarId id;
     private Characters characters;
     private int action;
     private byte type;

    public Actionbar() {
    }

    public Actionbar(ActionbarId id, Characters characters, int action, byte type) {
       this.id = id;
       this.characters = characters;
       this.action = action;
       this.type = type;
    }
   
    public ActionbarId getId() {
        return this.id;
    }
    
    public void setId(ActionbarId id) {
        this.id = id;
    }
    public Characters getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Characters characters) {
        this.characters = characters;
    }
    public int getAction() {
        return this.action;
    }
    
    public void setAction(int action) {
        this.action = action;
    }
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }




}


