package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Characters generated by hbm2java
 */
@Entity
@Table(name = "characters", catalog = "jangoscharacters"
)
public class Characters implements java.io.Serializable {

    private Long guid;
    private GuildRank guildRank;
    private ItemInstance itemInstance;
    private int fkAccount;
    private String name;
    private byte race;
    private byte fkDbcClass;
    private byte gender;
    private byte level;
    private int xp;
    private int money;
    private float positionX;
    private float positionY;
    private float positionZ;
    private int fkDbcMap;
    private float orientation;
    private boolean online;
    private boolean cinematic;
    private int totaltime;
    private int leveltime;
    private long logoutTime;
    private float restBonus;
    private int resettalentsCost;
    private long resettalentsTime;
    private float transX;
    private float transY;
    private float transZ;
    private float transO;
    private long fkTransguid;
    private byte stableSlots;
    private int fkDbcZone;
    private long deathExpireTime;
    private String fkDbcTaxiPath;
    private int honorHighestRank;
    private int honorStanding;
    private float storedHonorRating;
    private int storedDishonorableKills;
    private int storedHonorableKills;
    private int fkDbcWatchedFaction;
    private boolean drunk;
    private int health;
    private int power1;
    private int power2;
    private int power3;
    private int power4;
    private int power5;
    private int fkAmmoId;
    private Boolean deleted;
    private Date deleteDate;
    private Byte skin;
    private Byte face;
    private Byte hairstyle;
    private Byte haircolor;
    private Byte facialhair;
    private Byte unknownByte;
    private Byte bankbagslot;
    private Byte resttype;
    private Boolean changename;
    private Boolean resetspell;
    private Boolean resettalents;
    private Boolean charcustom;
    private Boolean groupleader;
    private Boolean afk;
    private Boolean dnd;
    private Boolean gm;
    private Boolean ghost;
    private Boolean resting;
    private Boolean unknown7;
    private Boolean ffapvp;
    private Boolean contestedpvp;
    private Boolean inpvp;
    private Boolean hidehelm;
    private Boolean hidecloak;
    private Boolean partialplaytime;
    private Boolean noplaytime;
    private Boolean unknown15;
    private Boolean unknown16;
    private Boolean sanctuary;
    private Boolean taxibenchmark;
    private Boolean pvptimer;
    private Boolean gmon;
    private Boolean gmaccepttickets;
    private Boolean gmacceptwhispers;
    private Boolean gmtaxicheat;
    private Boolean gminvisible;
    private Boolean gmchat;
    private Boolean gmauctionneutral;
    private Boolean gmauctionenemy;
    private Boolean pvpdeath;
    private String note;
    private String officernote;
    private Float homeX;
    private Float homeY;
    private Float homeZ;
    private Float homeOrientation;
    private Integer homeFkDbcMap;
    private Integer homeFkDbcZone;
    private Set<Skills> skillses = new HashSet<Skills>(0);
    private Set<Social> socialsForFkOwner = new HashSet<Social>(0);
    private Set<Social> socialsForFkRelation = new HashSet<Social>(0);
    private Set<Actionbar> actionbars = new HashSet<Actionbar>(0);
    private Set<Ticket> tickets = new HashSet<Ticket>(0);
    private Set<ItemInstance> itemInstances = new HashSet<ItemInstance>(0);
    private Set<Whispers> whispersesForFkTo = new HashSet<Whispers>(0);
    private Set<Whispers> whispersesForFkFrom = new HashSet<Whispers>(0);
    private Set<Reputation> reputations = new HashSet<Reputation>(0);
    private Set<Spell> spells = new HashSet<Spell>(0);

    public Characters() {
    }

    public Characters(int fkAccount, String name, byte race, byte fkDbcClass, byte gender, byte level, int xp, int money, float positionX, float positionY, float positionZ, int fkDbcMap, float orientation, boolean online, boolean cinematic, int totaltime, int leveltime, long logoutTime, float restBonus, int resettalentsCost, long resettalentsTime, float transX, float transY, float transZ, float transO, long fkTransguid, byte stableSlots, int fkDbcZone, long deathExpireTime, int honorHighestRank, int honorStanding, float storedHonorRating, int storedDishonorableKills, int storedHonorableKills, int fkDbcWatchedFaction, boolean drunk, int health, int power1, int power2, int power3, int power4, int power5, int fkAmmoId) {
        this.fkAccount = fkAccount;
        this.name = name;
        this.race = race;
        this.fkDbcClass = fkDbcClass;
        this.gender = gender;
        this.level = level;
        this.xp = xp;
        this.money = money;
        this.positionX = positionX;
        this.positionY = positionY;
        this.positionZ = positionZ;
        this.fkDbcMap = fkDbcMap;
        this.orientation = orientation;
        this.online = online;
        this.cinematic = cinematic;
        this.totaltime = totaltime;
        this.leveltime = leveltime;
        this.logoutTime = logoutTime;
        this.restBonus = restBonus;
        this.resettalentsCost = resettalentsCost;
        this.resettalentsTime = resettalentsTime;
        this.transX = transX;
        this.transY = transY;
        this.transZ = transZ;
        this.transO = transO;
        this.fkTransguid = fkTransguid;
        this.stableSlots = stableSlots;
        this.fkDbcZone = fkDbcZone;
        this.deathExpireTime = deathExpireTime;
        this.honorHighestRank = honorHighestRank;
        this.honorStanding = honorStanding;
        this.storedHonorRating = storedHonorRating;
        this.storedDishonorableKills = storedDishonorableKills;
        this.storedHonorableKills = storedHonorableKills;
        this.fkDbcWatchedFaction = fkDbcWatchedFaction;
        this.drunk = drunk;
        this.health = health;
        this.power1 = power1;
        this.power2 = power2;
        this.power3 = power3;
        this.power4 = power4;
        this.power5 = power5;
        this.fkAmmoId = fkAmmoId;
    }

    public Characters(GuildRank guildRank, ItemInstance itemInstance, int fkAccount, String name, byte race, byte fkDbcClass, byte gender, byte level, int xp, int money, float positionX, float positionY, float positionZ, int fkDbcMap, float orientation, boolean online, boolean cinematic, int totaltime, int leveltime, long logoutTime, float restBonus, int resettalentsCost, long resettalentsTime, float transX, float transY, float transZ, float transO, long fkTransguid, byte stableSlots, int fkDbcZone, long deathExpireTime, String fkDbcTaxiPath, int honorHighestRank, int honorStanding, float storedHonorRating, int storedDishonorableKills, int storedHonorableKills, int fkDbcWatchedFaction, boolean drunk, int health, int power1, int power2, int power3, int power4, int power5, int fkAmmoId, Boolean deleted, Date deleteDate, Byte skin, Byte face, Byte hairstyle, Byte haircolor, Byte facialhair, Byte unknownByte, Byte bankbagslot, Byte resttype, Boolean changename, Boolean resetspell, Boolean resettalents, Boolean charcustom, Boolean groupleader, Boolean afk, Boolean dnd, Boolean gm, Boolean ghost, Boolean resting, Boolean unknown7, Boolean ffapvp, Boolean contestedpvp, Boolean inpvp, Boolean hidehelm, Boolean hidecloak, Boolean partialplaytime, Boolean noplaytime, Boolean unknown15, Boolean unknown16, Boolean sanctuary, Boolean taxibenchmark, Boolean pvptimer, Boolean gmon, Boolean gmaccepttickets, Boolean gmacceptwhispers, Boolean gmtaxicheat, Boolean gminvisible, Boolean gmchat, Boolean gmauctionneutral, Boolean gmauctionenemy, Boolean pvpdeath, String note, String officernote, Float homeX, Float homeY, Float homeZ, Float homeOrientation, Integer homeFkDbcMap, Integer homeFkDbcZone, Set<Skills> skillses, Set<Social> socialsForFkOwner, Set<Social> socialsForFkRelation, Set<Actionbar> actionbars, Set<Ticket> tickets, Set<ItemInstance> itemInstances, Set<Whispers> whispersesForFkTo, Set<Whispers> whispersesForFkFrom, Set<Reputation> reputations, Set<Spell> spells) {
        this.guildRank = guildRank;
        this.itemInstance = itemInstance;
        this.fkAccount = fkAccount;
        this.name = name;
        this.race = race;
        this.fkDbcClass = fkDbcClass;
        this.gender = gender;
        this.level = level;
        this.xp = xp;
        this.money = money;
        this.positionX = positionX;
        this.positionY = positionY;
        this.positionZ = positionZ;
        this.fkDbcMap = fkDbcMap;
        this.orientation = orientation;
        this.online = online;
        this.cinematic = cinematic;
        this.totaltime = totaltime;
        this.leveltime = leveltime;
        this.logoutTime = logoutTime;
        this.restBonus = restBonus;
        this.resettalentsCost = resettalentsCost;
        this.resettalentsTime = resettalentsTime;
        this.transX = transX;
        this.transY = transY;
        this.transZ = transZ;
        this.transO = transO;
        this.fkTransguid = fkTransguid;
        this.stableSlots = stableSlots;
        this.fkDbcZone = fkDbcZone;
        this.deathExpireTime = deathExpireTime;
        this.fkDbcTaxiPath = fkDbcTaxiPath;
        this.honorHighestRank = honorHighestRank;
        this.honorStanding = honorStanding;
        this.storedHonorRating = storedHonorRating;
        this.storedDishonorableKills = storedDishonorableKills;
        this.storedHonorableKills = storedHonorableKills;
        this.fkDbcWatchedFaction = fkDbcWatchedFaction;
        this.drunk = drunk;
        this.health = health;
        this.power1 = power1;
        this.power2 = power2;
        this.power3 = power3;
        this.power4 = power4;
        this.power5 = power5;
        this.fkAmmoId = fkAmmoId;
        this.deleted = deleted;
        this.deleteDate = deleteDate;
        this.skin = skin;
        this.face = face;
        this.hairstyle = hairstyle;
        this.haircolor = haircolor;
        this.facialhair = facialhair;
        this.unknownByte = unknownByte;
        this.bankbagslot = bankbagslot;
        this.resttype = resttype;
        this.changename = changename;
        this.resetspell = resetspell;
        this.resettalents = resettalents;
        this.charcustom = charcustom;
        this.groupleader = groupleader;
        this.afk = afk;
        this.dnd = dnd;
        this.gm = gm;
        this.ghost = ghost;
        this.resting = resting;
        this.unknown7 = unknown7;
        this.ffapvp = ffapvp;
        this.contestedpvp = contestedpvp;
        this.inpvp = inpvp;
        this.hidehelm = hidehelm;
        this.hidecloak = hidecloak;
        this.partialplaytime = partialplaytime;
        this.noplaytime = noplaytime;
        this.unknown15 = unknown15;
        this.unknown16 = unknown16;
        this.sanctuary = sanctuary;
        this.taxibenchmark = taxibenchmark;
        this.pvptimer = pvptimer;
        this.gmon = gmon;
        this.gmaccepttickets = gmaccepttickets;
        this.gmacceptwhispers = gmacceptwhispers;
        this.gmtaxicheat = gmtaxicheat;
        this.gminvisible = gminvisible;
        this.gmchat = gmchat;
        this.gmauctionneutral = gmauctionneutral;
        this.gmauctionenemy = gmauctionenemy;
        this.pvpdeath = pvpdeath;
        this.note = note;
        this.officernote = officernote;
        this.homeX = homeX;
        this.homeY = homeY;
        this.homeZ = homeZ;
        this.homeOrientation = homeOrientation;
        this.homeFkDbcMap = homeFkDbcMap;
        this.homeFkDbcZone = homeFkDbcZone;
        this.skillses = skillses;
        this.socialsForFkOwner = socialsForFkOwner;
        this.socialsForFkRelation = socialsForFkRelation;
        this.actionbars = actionbars;
        this.tickets = tickets;
        this.itemInstances = itemInstances;
        this.whispersesForFkTo = whispersesForFkTo;
        this.whispersesForFkFrom = whispersesForFkFrom;
        this.reputations = reputations;
        this.spells = spells;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "guid", unique = true, nullable = false)
    public Long getGuid() {
        return this.guid;
    }

    public void setGuid(Long guid) {
        this.guid = guid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "fk_guild_rank_guild", referencedColumnName = "fk_guild_id"),
        @JoinColumn(name = "fk_guild_rank", referencedColumnName = "id")})
    public GuildRank getGuildRank() {
        return this.guildRank;
    }

    public void setGuildRank(GuildRank guildRank) {
        this.guildRank = guildRank;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_petition")
    public ItemInstance getItemInstance() {
        return this.itemInstance;
    }

    public void setItemInstance(ItemInstance itemInstance) {
        this.itemInstance = itemInstance;
    }

    @Column(name = "fk_account", nullable = false)
    public int getFkAccount() {
        return this.fkAccount;
    }

    public void setFkAccount(int fkAccount) {
        this.fkAccount = fkAccount;
    }

    @Column(name = "name", nullable = false, length = 12)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "race", nullable = false)
    public byte getRace() {
        return this.race;
    }

    public void setRace(byte race) {
        this.race = race;
    }

    @Column(name = "fk_dbc_class", nullable = false)
    public byte getFkDbcClass() {
        return this.fkDbcClass;
    }

    public void setFkDbcClass(byte fkDbcClass) {
        this.fkDbcClass = fkDbcClass;
    }

    @Column(name = "gender", nullable = false)
    public byte getGender() {
        return this.gender;
    }

    public void setGender(byte gender) {
        this.gender = gender;
    }

    @Column(name = "level", nullable = false)
    public byte getLevel() {
        return this.level;
    }

    public void setLevel(byte level) {
        this.level = level;
    }

    @Column(name = "xp", nullable = false)
    public int getXp() {
        return this.xp;
    }

    public void setXp(int xp) {
        this.xp = xp;
    }

    @Column(name = "money", nullable = false)
    public int getMoney() {
        return this.money;
    }

    public void setMoney(int money) {
        this.money = money;
    }

    @Column(name = "position_x", nullable = false, precision = 12, scale = 0)
    public float getPositionX() {
        return this.positionX;
    }

    public void setPositionX(float positionX) {
        this.positionX = positionX;
    }

    @Column(name = "position_y", nullable = false, precision = 12, scale = 0)
    public float getPositionY() {
        return this.positionY;
    }

    public void setPositionY(float positionY) {
        this.positionY = positionY;
    }

    @Column(name = "position_z", nullable = false, precision = 12, scale = 0)
    public float getPositionZ() {
        return this.positionZ;
    }

    public void setPositionZ(float positionZ) {
        this.positionZ = positionZ;
    }

    @Column(name = "fk_dbc_map", nullable = false)
    public int getFkDbcMap() {
        return this.fkDbcMap;
    }

    public void setFkDbcMap(int fkDbcMap) {
        this.fkDbcMap = fkDbcMap;
    }

    @Column(name = "orientation", nullable = false, precision = 12, scale = 0)
    public float getOrientation() {
        return this.orientation;
    }

    public void setOrientation(float orientation) {
        this.orientation = orientation;
    }

    @Column(name = "online", nullable = false)
    public boolean isOnline() {
        return this.online;
    }

    public void setOnline(boolean online) {
        this.online = online;
    }

    @Column(name = "cinematic", nullable = false)
    public boolean isCinematic() {
        return this.cinematic;
    }

    public void setCinematic(boolean cinematic) {
        this.cinematic = cinematic;
    }

    @Column(name = "totaltime", nullable = false)
    public int getTotaltime() {
        return this.totaltime;
    }

    public void setTotaltime(int totaltime) {
        this.totaltime = totaltime;
    }

    @Column(name = "leveltime", nullable = false)
    public int getLeveltime() {
        return this.leveltime;
    }

    public void setLeveltime(int leveltime) {
        this.leveltime = leveltime;
    }

    @Column(name = "logout_time", nullable = false)
    public long getLogoutTime() {
        return this.logoutTime;
    }

    public void setLogoutTime(long logoutTime) {
        this.logoutTime = logoutTime;
    }

    @Column(name = "rest_bonus", nullable = false, precision = 12, scale = 0)
    public float getRestBonus() {
        return this.restBonus;
    }

    public void setRestBonus(float restBonus) {
        this.restBonus = restBonus;
    }

    @Column(name = "resettalents_cost", nullable = false)
    public int getResettalentsCost() {
        return this.resettalentsCost;
    }

    public void setResettalentsCost(int resettalentsCost) {
        this.resettalentsCost = resettalentsCost;
    }

    @Column(name = "resettalents_time", nullable = false)
    public long getResettalentsTime() {
        return this.resettalentsTime;
    }

    public void setResettalentsTime(long resettalentsTime) {
        this.resettalentsTime = resettalentsTime;
    }

    @Column(name = "trans_x", nullable = false, precision = 12, scale = 0)
    public float getTransX() {
        return this.transX;
    }

    public void setTransX(float transX) {
        this.transX = transX;
    }

    @Column(name = "trans_y", nullable = false, precision = 12, scale = 0)
    public float getTransY() {
        return this.transY;
    }

    public void setTransY(float transY) {
        this.transY = transY;
    }

    @Column(name = "trans_z", nullable = false, precision = 12, scale = 0)
    public float getTransZ() {
        return this.transZ;
    }

    public void setTransZ(float transZ) {
        this.transZ = transZ;
    }

    @Column(name = "trans_o", nullable = false, precision = 12, scale = 0)
    public float getTransO() {
        return this.transO;
    }

    public void setTransO(float transO) {
        this.transO = transO;
    }

    @Column(name = "fk_transguid", nullable = false)
    public long getFkTransguid() {
        return this.fkTransguid;
    }

    public void setFkTransguid(long fkTransguid) {
        this.fkTransguid = fkTransguid;
    }

    @Column(name = "stable_slots", nullable = false)
    public byte getStableSlots() {
        return this.stableSlots;
    }

    public void setStableSlots(byte stableSlots) {
        this.stableSlots = stableSlots;
    }

    @Column(name = "fk_dbc_zone", nullable = false)
    public int getFkDbcZone() {
        return this.fkDbcZone;
    }

    public void setFkDbcZone(int fkDbcZone) {
        this.fkDbcZone = fkDbcZone;
    }

    @Column(name = "death_expire_time", nullable = false)
    public long getDeathExpireTime() {
        return this.deathExpireTime;
    }

    public void setDeathExpireTime(long deathExpireTime) {
        this.deathExpireTime = deathExpireTime;
    }

    @Column(name = "fk_dbc_taxi_path", length = 65535)
    public String getFkDbcTaxiPath() {
        return this.fkDbcTaxiPath;
    }

    public void setFkDbcTaxiPath(String fkDbcTaxiPath) {
        this.fkDbcTaxiPath = fkDbcTaxiPath;
    }

    @Column(name = "honor_highest_rank", nullable = false)
    public int getHonorHighestRank() {
        return this.honorHighestRank;
    }

    public void setHonorHighestRank(int honorHighestRank) {
        this.honorHighestRank = honorHighestRank;
    }

    @Column(name = "honor_standing", nullable = false)
    public int getHonorStanding() {
        return this.honorStanding;
    }

    public void setHonorStanding(int honorStanding) {
        this.honorStanding = honorStanding;
    }

    @Column(name = "stored_honor_rating", nullable = false, precision = 12, scale = 0)
    public float getStoredHonorRating() {
        return this.storedHonorRating;
    }

    public void setStoredHonorRating(float storedHonorRating) {
        this.storedHonorRating = storedHonorRating;
    }

    @Column(name = "stored_dishonorable_kills", nullable = false)
    public int getStoredDishonorableKills() {
        return this.storedDishonorableKills;
    }

    public void setStoredDishonorableKills(int storedDishonorableKills) {
        this.storedDishonorableKills = storedDishonorableKills;
    }

    @Column(name = "stored_honorable_kills", nullable = false)
    public int getStoredHonorableKills() {
        return this.storedHonorableKills;
    }

    public void setStoredHonorableKills(int storedHonorableKills) {
        this.storedHonorableKills = storedHonorableKills;
    }

    @Column(name = "fk_dbc_watchedFaction", nullable = false)
    public int getFkDbcWatchedFaction() {
        return this.fkDbcWatchedFaction;
    }

    public void setFkDbcWatchedFaction(int fkDbcWatchedFaction) {
        this.fkDbcWatchedFaction = fkDbcWatchedFaction;
    }

    @Column(name = "drunk", nullable = false)
    public boolean isDrunk() {
        return this.drunk;
    }

    public void setDrunk(boolean drunk) {
        this.drunk = drunk;
    }

    @Column(name = "health", nullable = false)
    public int getHealth() {
        return this.health;
    }

    public void setHealth(int health) {
        this.health = health;
    }

    @Column(name = "power1", nullable = false)
    public int getPower1() {
        return this.power1;
    }

    public void setPower1(int power1) {
        this.power1 = power1;
    }

    @Column(name = "power2", nullable = false)
    public int getPower2() {
        return this.power2;
    }

    public void setPower2(int power2) {
        this.power2 = power2;
    }

    @Column(name = "power3", nullable = false)
    public int getPower3() {
        return this.power3;
    }

    public void setPower3(int power3) {
        this.power3 = power3;
    }

    @Column(name = "power4", nullable = false)
    public int getPower4() {
        return this.power4;
    }

    public void setPower4(int power4) {
        this.power4 = power4;
    }

    @Column(name = "power5", nullable = false)
    public int getPower5() {
        return this.power5;
    }

    public void setPower5(int power5) {
        this.power5 = power5;
    }

    @Column(name = "fk_ammoId", nullable = false)
    public int getFkAmmoId() {
        return this.fkAmmoId;
    }

    public void setFkAmmoId(int fkAmmoId) {
        this.fkAmmoId = fkAmmoId;
    }

    @Column(name = "deleted")
    public Boolean getDeleted() {
        return this.deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "deleteDate", length = 19)
    public Date getDeleteDate() {
        return this.deleteDate;
    }

    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }

    @Column(name = "skin")
    public Byte getSkin() {
        return this.skin;
    }

    public void setSkin(Byte skin) {
        this.skin = skin;
    }

    @Column(name = "face")
    public Byte getFace() {
        return this.face;
    }

    public void setFace(Byte face) {
        this.face = face;
    }

    @Column(name = "hairstyle")
    public Byte getHairstyle() {
        return this.hairstyle;
    }

    public void setHairstyle(Byte hairstyle) {
        this.hairstyle = hairstyle;
    }

    @Column(name = "haircolor")
    public Byte getHaircolor() {
        return this.haircolor;
    }

    public void setHaircolor(Byte haircolor) {
        this.haircolor = haircolor;
    }

    @Column(name = "facialhair")
    public Byte getFacialhair() {
        return this.facialhair;
    }

    public void setFacialhair(Byte facialhair) {
        this.facialhair = facialhair;
    }

    @Column(name = "unknownByte")
    public Byte getUnknownByte() {
        return this.unknownByte;
    }

    public void setUnknownByte(Byte unknownByte) {
        this.unknownByte = unknownByte;
    }

    @Column(name = "bankbagslot")
    public Byte getBankbagslot() {
        return this.bankbagslot;
    }

    public void setBankbagslot(Byte bankbagslot) {
        this.bankbagslot = bankbagslot;
    }

    @Column(name = "resttype")
    public Byte getResttype() {
        return this.resttype;
    }

    public void setResttype(Byte resttype) {
        this.resttype = resttype;
    }

    @Column(name = "changename")
    public Boolean getChangename() {
        return this.changename;
    }

    public void setChangename(Boolean changename) {
        this.changename = changename;
    }

    @Column(name = "resetspell")
    public Boolean getResetspell() {
        return this.resetspell;
    }

    public void setResetspell(Boolean resetspell) {
        this.resetspell = resetspell;
    }

    @Column(name = "resettalents")
    public Boolean getResettalents() {
        return this.resettalents;
    }

    public void setResettalents(Boolean resettalents) {
        this.resettalents = resettalents;
    }

    @Column(name = "charcustom")
    public Boolean getCharcustom() {
        return this.charcustom;
    }

    public void setCharcustom(Boolean charcustom) {
        this.charcustom = charcustom;
    }

    @Column(name = "groupleader")
    public Boolean getGroupleader() {
        return this.groupleader;
    }

    public void setGroupleader(Boolean groupleader) {
        this.groupleader = groupleader;
    }

    @Column(name = "afk")
    public Boolean getAfk() {
        return this.afk;
    }

    public void setAfk(Boolean afk) {
        this.afk = afk;
    }

    @Column(name = "dnd")
    public Boolean getDnd() {
        return this.dnd;
    }

    public void setDnd(Boolean dnd) {
        this.dnd = dnd;
    }

    @Column(name = "gm")
    public Boolean getGm() {
        return this.gm;
    }

    public void setGm(Boolean gm) {
        this.gm = gm;
    }

    @Column(name = "ghost")
    public Boolean getGhost() {
        return this.ghost;
    }

    public void setGhost(Boolean ghost) {
        this.ghost = ghost;
    }

    @Column(name = "resting")
    public Boolean getResting() {
        return this.resting;
    }

    public void setResting(Boolean resting) {
        this.resting = resting;
    }

    @Column(name = "unknown7")
    public Boolean getUnknown7() {
        return this.unknown7;
    }

    public void setUnknown7(Boolean unknown7) {
        this.unknown7 = unknown7;
    }

    @Column(name = "ffapvp")
    public Boolean getFfapvp() {
        return this.ffapvp;
    }

    public void setFfapvp(Boolean ffapvp) {
        this.ffapvp = ffapvp;
    }

    @Column(name = "contestedpvp")
    public Boolean getContestedpvp() {
        return this.contestedpvp;
    }

    public void setContestedpvp(Boolean contestedpvp) {
        this.contestedpvp = contestedpvp;
    }

    @Column(name = "inpvp")
    public Boolean getInpvp() {
        return this.inpvp;
    }

    public void setInpvp(Boolean inpvp) {
        this.inpvp = inpvp;
    }

    @Column(name = "hidehelm")
    public Boolean getHidehelm() {
        return this.hidehelm;
    }

    public void setHidehelm(Boolean hidehelm) {
        this.hidehelm = hidehelm;
    }

    @Column(name = "hidecloak")
    public Boolean getHidecloak() {
        return this.hidecloak;
    }

    public void setHidecloak(Boolean hidecloak) {
        this.hidecloak = hidecloak;
    }

    @Column(name = "partialplaytime")
    public Boolean getPartialplaytime() {
        return this.partialplaytime;
    }

    public void setPartialplaytime(Boolean partialplaytime) {
        this.partialplaytime = partialplaytime;
    }

    @Column(name = "noplaytime")
    public Boolean getNoplaytime() {
        return this.noplaytime;
    }

    public void setNoplaytime(Boolean noplaytime) {
        this.noplaytime = noplaytime;
    }

    @Column(name = "unknown15")
    public Boolean getUnknown15() {
        return this.unknown15;
    }

    public void setUnknown15(Boolean unknown15) {
        this.unknown15 = unknown15;
    }

    @Column(name = "unknown16")
    public Boolean getUnknown16() {
        return this.unknown16;
    }

    public void setUnknown16(Boolean unknown16) {
        this.unknown16 = unknown16;
    }

    @Column(name = "sanctuary")
    public Boolean getSanctuary() {
        return this.sanctuary;
    }

    public void setSanctuary(Boolean sanctuary) {
        this.sanctuary = sanctuary;
    }

    @Column(name = "taxibenchmark")
    public Boolean getTaxibenchmark() {
        return this.taxibenchmark;
    }

    public void setTaxibenchmark(Boolean taxibenchmark) {
        this.taxibenchmark = taxibenchmark;
    }

    @Column(name = "pvptimer")
    public Boolean getPvptimer() {
        return this.pvptimer;
    }

    public void setPvptimer(Boolean pvptimer) {
        this.pvptimer = pvptimer;
    }

    @Column(name = "gmon")
    public Boolean getGmon() {
        return this.gmon;
    }

    public void setGmon(Boolean gmon) {
        this.gmon = gmon;
    }

    @Column(name = "gmaccepttickets")
    public Boolean getGmaccepttickets() {
        return this.gmaccepttickets;
    }

    public void setGmaccepttickets(Boolean gmaccepttickets) {
        this.gmaccepttickets = gmaccepttickets;
    }

    @Column(name = "gmacceptwhispers")
    public Boolean getGmacceptwhispers() {
        return this.gmacceptwhispers;
    }

    public void setGmacceptwhispers(Boolean gmacceptwhispers) {
        this.gmacceptwhispers = gmacceptwhispers;
    }

    @Column(name = "gmtaxicheat")
    public Boolean getGmtaxicheat() {
        return this.gmtaxicheat;
    }

    public void setGmtaxicheat(Boolean gmtaxicheat) {
        this.gmtaxicheat = gmtaxicheat;
    }

    @Column(name = "gminvisible")
    public Boolean getGminvisible() {
        return this.gminvisible;
    }

    public void setGminvisible(Boolean gminvisible) {
        this.gminvisible = gminvisible;
    }

    @Column(name = "gmchat")
    public Boolean getGmchat() {
        return this.gmchat;
    }

    public void setGmchat(Boolean gmchat) {
        this.gmchat = gmchat;
    }

    @Column(name = "gmauctionneutral")
    public Boolean getGmauctionneutral() {
        return this.gmauctionneutral;
    }

    public void setGmauctionneutral(Boolean gmauctionneutral) {
        this.gmauctionneutral = gmauctionneutral;
    }

    @Column(name = "gmauctionenemy")
    public Boolean getGmauctionenemy() {
        return this.gmauctionenemy;
    }

    public void setGmauctionenemy(Boolean gmauctionenemy) {
        this.gmauctionenemy = gmauctionenemy;
    }

    @Column(name = "pvpdeath")
    public Boolean getPvpdeath() {
        return this.pvpdeath;
    }

    public void setPvpdeath(Boolean pvpdeath) {
        this.pvpdeath = pvpdeath;
    }

    @Column(name = "note", length = 60)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Column(name = "officernote", length = 60)
    public String getOfficernote() {
        return this.officernote;
    }

    public void setOfficernote(String officernote) {
        this.officernote = officernote;
    }

    @Column(name = "home_x", precision = 12, scale = 0)
    public Float getHomeX() {
        return this.homeX;
    }

    public void setHomeX(Float homeX) {
        this.homeX = homeX;
    }

    @Column(name = "home_y", precision = 12, scale = 0)
    public Float getHomeY() {
        return this.homeY;
    }

    public void setHomeY(Float homeY) {
        this.homeY = homeY;
    }

    @Column(name = "home_z", precision = 12, scale = 0)
    public Float getHomeZ() {
        return this.homeZ;
    }

    public void setHomeZ(Float homeZ) {
        this.homeZ = homeZ;
    }

    @Column(name = "home_orientation", precision = 12, scale = 0)
    public Float getHomeOrientation() {
        return this.homeOrientation;
    }

    public void setHomeOrientation(Float homeOrientation) {
        this.homeOrientation = homeOrientation;
    }

    @Column(name = "home_fk_dbc_map")
    public Integer getHomeFkDbcMap() {
        return this.homeFkDbcMap;
    }

    public void setHomeFkDbcMap(Integer homeFkDbcMap) {
        this.homeFkDbcMap = homeFkDbcMap;
    }

    @Column(name = "home_fk_dbc_zone")
    public Integer getHomeFkDbcZone() {
        return this.homeFkDbcZone;
    }

    public void setHomeFkDbcZone(Integer homeFkDbcZone) {
        this.homeFkDbcZone = homeFkDbcZone;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "characters")
    public Set<Skills> getSkillses() {
        return this.skillses;
    }

    public void setSkillses(Set<Skills> skillses) {
        this.skillses = skillses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "charactersByFkOwner")
    public Set<Social> getSocialsForFkOwner() {
        return this.socialsForFkOwner;
    }

    public void setSocialsForFkOwner(Set<Social> socialsForFkOwner) {
        this.socialsForFkOwner = socialsForFkOwner;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "charactersByFkRelation")
    public Set<Social> getSocialsForFkRelation() {
        return this.socialsForFkRelation;
    }

    public void setSocialsForFkRelation(Set<Social> socialsForFkRelation) {
        this.socialsForFkRelation = socialsForFkRelation;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "characters")
    public Set<Actionbar> getActionbars() {
        return this.actionbars;
    }

    public void setActionbars(Set<Actionbar> actionbars) {
        this.actionbars = actionbars;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "characters")
    public Set<Ticket> getTickets() {
        return this.tickets;
    }

    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "characters", cascade = CascadeType.ALL)
    public Set<ItemInstance> getItemInstances() {
        return this.itemInstances;
    }

    public void setItemInstances(Set<ItemInstance> itemInstances) {
        this.itemInstances = itemInstances;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "charactersByFkTo")
    public Set<Whispers> getWhispersesForFkTo() {
        return this.whispersesForFkTo;
    }

    public void setWhispersesForFkTo(Set<Whispers> whispersesForFkTo) {
        this.whispersesForFkTo = whispersesForFkTo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "charactersByFkFrom")
    public Set<Whispers> getWhispersesForFkFrom() {
        return this.whispersesForFkFrom;
    }

    public void setWhispersesForFkFrom(Set<Whispers> whispersesForFkFrom) {
        this.whispersesForFkFrom = whispersesForFkFrom;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "characters")
    public Set<Reputation> getReputations() {
        return this.reputations;
    }

    public void setReputations(Set<Reputation> reputations) {
        this.reputations = reputations;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "characters", cascade = CascadeType.ALL)
    public Set<Spell> getSpells() {
        return this.spells;
    }

    public void setSpells(Set<Spell> spells) {
        this.spells = spells;
    }

}
