package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GuildEventType generated by hbm2java
 */
@Entity
@Table(name="guild_event_type"
    ,catalog="jangoscharacters"
)
public class GuildEventType  implements java.io.Serializable {


     private byte id;
     private String type;
     private Set<GuildEvents> guildEventses = new HashSet<GuildEvents>(0);

    public GuildEventType() {
    }

	
    public GuildEventType(byte id) {
        this.id = id;
    }
    public GuildEventType(byte id, String type, Set<GuildEvents> guildEventses) {
       this.id = id;
       this.type = type;
       this.guildEventses = guildEventses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guildEventType")
    public Set<GuildEvents> getGuildEventses() {
        return this.guildEventses;
    }
    
    public void setGuildEventses(Set<GuildEvents> guildEventses) {
        this.guildEventses = guildEventses;
    }




}


