package eu.jangos.realm.model.characters;
// Generated 19-févr.-2016 21:17:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GuildRank generated by hbm2java
 */
public class GuildRank  implements java.io.Serializable {


     private GuildRankId id;
     private Guild guild;
     private String name;
     private Byte authzReadChannel;
     private Byte authzWriteChannel;
     private Byte authzReadOffChannel;
     private Byte authzWriteOffChannel;
     private Byte authzPromote;
     private Byte authzDemote;
     private Byte authzInvite;
     private Byte authzRevoke;
     private Byte authzMotd;
     private Byte authzWriteNote;
     private Byte authzReadOffNote;
     private Byte authzWriteOffNote;
     private Byte authzGuildinfo;
     private Set characterses = new HashSet(0);

    public GuildRank() {
    }

	
    public GuildRank(GuildRankId id, Guild guild, String name) {
        this.id = id;
        this.guild = guild;
        this.name = name;
    }
    public GuildRank(GuildRankId id, Guild guild, String name, Byte authzReadChannel, Byte authzWriteChannel, Byte authzReadOffChannel, Byte authzWriteOffChannel, Byte authzPromote, Byte authzDemote, Byte authzInvite, Byte authzRevoke, Byte authzMotd, Byte authzWriteNote, Byte authzReadOffNote, Byte authzWriteOffNote, Byte authzGuildinfo, Set characterses) {
       this.id = id;
       this.guild = guild;
       this.name = name;
       this.authzReadChannel = authzReadChannel;
       this.authzWriteChannel = authzWriteChannel;
       this.authzReadOffChannel = authzReadOffChannel;
       this.authzWriteOffChannel = authzWriteOffChannel;
       this.authzPromote = authzPromote;
       this.authzDemote = authzDemote;
       this.authzInvite = authzInvite;
       this.authzRevoke = authzRevoke;
       this.authzMotd = authzMotd;
       this.authzWriteNote = authzWriteNote;
       this.authzReadOffNote = authzReadOffNote;
       this.authzWriteOffNote = authzWriteOffNote;
       this.authzGuildinfo = authzGuildinfo;
       this.characterses = characterses;
    }
   
    public GuildRankId getId() {
        return this.id;
    }
    
    public void setId(GuildRankId id) {
        this.id = id;
    }
    public Guild getGuild() {
        return this.guild;
    }
    
    public void setGuild(Guild guild) {
        this.guild = guild;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Byte getAuthzReadChannel() {
        return this.authzReadChannel;
    }
    
    public void setAuthzReadChannel(Byte authzReadChannel) {
        this.authzReadChannel = authzReadChannel;
    }
    public Byte getAuthzWriteChannel() {
        return this.authzWriteChannel;
    }
    
    public void setAuthzWriteChannel(Byte authzWriteChannel) {
        this.authzWriteChannel = authzWriteChannel;
    }
    public Byte getAuthzReadOffChannel() {
        return this.authzReadOffChannel;
    }
    
    public void setAuthzReadOffChannel(Byte authzReadOffChannel) {
        this.authzReadOffChannel = authzReadOffChannel;
    }
    public Byte getAuthzWriteOffChannel() {
        return this.authzWriteOffChannel;
    }
    
    public void setAuthzWriteOffChannel(Byte authzWriteOffChannel) {
        this.authzWriteOffChannel = authzWriteOffChannel;
    }
    public Byte getAuthzPromote() {
        return this.authzPromote;
    }
    
    public void setAuthzPromote(Byte authzPromote) {
        this.authzPromote = authzPromote;
    }
    public Byte getAuthzDemote() {
        return this.authzDemote;
    }
    
    public void setAuthzDemote(Byte authzDemote) {
        this.authzDemote = authzDemote;
    }
    public Byte getAuthzInvite() {
        return this.authzInvite;
    }
    
    public void setAuthzInvite(Byte authzInvite) {
        this.authzInvite = authzInvite;
    }
    public Byte getAuthzRevoke() {
        return this.authzRevoke;
    }
    
    public void setAuthzRevoke(Byte authzRevoke) {
        this.authzRevoke = authzRevoke;
    }
    public Byte getAuthzMotd() {
        return this.authzMotd;
    }
    
    public void setAuthzMotd(Byte authzMotd) {
        this.authzMotd = authzMotd;
    }
    public Byte getAuthzWriteNote() {
        return this.authzWriteNote;
    }
    
    public void setAuthzWriteNote(Byte authzWriteNote) {
        this.authzWriteNote = authzWriteNote;
    }
    public Byte getAuthzReadOffNote() {
        return this.authzReadOffNote;
    }
    
    public void setAuthzReadOffNote(Byte authzReadOffNote) {
        this.authzReadOffNote = authzReadOffNote;
    }
    public Byte getAuthzWriteOffNote() {
        return this.authzWriteOffNote;
    }
    
    public void setAuthzWriteOffNote(Byte authzWriteOffNote) {
        this.authzWriteOffNote = authzWriteOffNote;
    }
    public Byte getAuthzGuildinfo() {
        return this.authzGuildinfo;
    }
    
    public void setAuthzGuildinfo(Byte authzGuildinfo) {
        this.authzGuildinfo = authzGuildinfo;
    }
    public Set getCharacterses() {
        return this.characterses;
    }
    
    public void setCharacterses(Set characterses) {
        this.characterses = characterses;
    }




}


