package eu.jangos.realm.model.characters;
// Generated 19-févr.-2016 21:17:55 by Hibernate Tools 4.3.1



/**
 * GuildEventsId generated by hbm2java
 */
public class GuildEventsId  implements java.io.Serializable {


     private int id;
     private int fkGuild;

    public GuildEventsId() {
    }

    public GuildEventsId(int id, int fkGuild) {
       this.id = id;
       this.fkGuild = fkGuild;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getFkGuild() {
        return this.fkGuild;
    }
    
    public void setFkGuild(int fkGuild) {
        this.fkGuild = fkGuild;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GuildEventsId) ) return false;
		 GuildEventsId castOther = ( GuildEventsId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getFkGuild()==castOther.getFkGuild());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getFkGuild();
         return result;
   }   


}


