package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GuildEvents generated by hbm2java
 */
@Entity
@Table(name="guild_events"
    ,catalog="jangoscharacters"
)
public class GuildEvents  implements java.io.Serializable {


     private GuildEventsId id;
     private Guild guild;
     private GuildEventType guildEventType;
     private Long fkEventSender;
     private Long fkEventReceiver;
     private Byte rank;
     private Date date;

    public GuildEvents() {
    }

	
    public GuildEvents(GuildEventsId id, Guild guild) {
        this.id = id;
        this.guild = guild;
    }
    public GuildEvents(GuildEventsId id, Guild guild, GuildEventType guildEventType, Long fkEventSender, Long fkEventReceiver, Byte rank, Date date) {
       this.id = id;
       this.guild = guild;
       this.guildEventType = guildEventType;
       this.fkEventSender = fkEventSender;
       this.fkEventReceiver = fkEventReceiver;
       this.rank = rank;
       this.date = date;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="fkGuild", column=@Column(name="fk_guild", nullable=false) ) } )
    public GuildEventsId getId() {
        return this.id;
    }
    
    public void setId(GuildEventsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_guild", nullable=false, insertable=false, updatable=false)
    public Guild getGuild() {
        return this.guild;
    }
    
    public void setGuild(Guild guild) {
        this.guild = guild;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_event_type")
    public GuildEventType getGuildEventType() {
        return this.guildEventType;
    }
    
    public void setGuildEventType(GuildEventType guildEventType) {
        this.guildEventType = guildEventType;
    }

    
    @Column(name="fk_event_sender")
    public Long getFkEventSender() {
        return this.fkEventSender;
    }
    
    public void setFkEventSender(Long fkEventSender) {
        this.fkEventSender = fkEventSender;
    }

    
    @Column(name="fk_event_receiver")
    public Long getFkEventReceiver() {
        return this.fkEventReceiver;
    }
    
    public void setFkEventReceiver(Long fkEventReceiver) {
        this.fkEventReceiver = fkEventReceiver;
    }

    
    @Column(name="rank")
    public Byte getRank() {
        return this.rank;
    }
    
    public void setRank(Byte rank) {
        this.rank = rank;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


