package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GuildRank generated by hbm2java
 */
@Entity
@Table(name="guild_rank"
    ,catalog="jangoscharacters"
)
public class GuildRank  implements java.io.Serializable {


     private GuildRankId id;
     private Guild guild;
     private String name;
     private Byte authzReadChannel;
     private Byte authzWriteChannel;
     private Byte authzReadOffChannel;
     private Byte authzWriteOffChannel;
     private Byte authzPromote;
     private Byte authzDemote;
     private Byte authzInvite;
     private Byte authzRevoke;
     private Byte authzMotd;
     private Byte authzWriteNote;
     private Byte authzReadOffNote;
     private Byte authzWriteOffNote;
     private Byte authzGuildinfo;
     private Set<Characters> characterses = new HashSet<Characters>(0);

    public GuildRank() {
    }

	
    public GuildRank(GuildRankId id, Guild guild, String name) {
        this.id = id;
        this.guild = guild;
        this.name = name;
    }
    public GuildRank(GuildRankId id, Guild guild, String name, Byte authzReadChannel, Byte authzWriteChannel, Byte authzReadOffChannel, Byte authzWriteOffChannel, Byte authzPromote, Byte authzDemote, Byte authzInvite, Byte authzRevoke, Byte authzMotd, Byte authzWriteNote, Byte authzReadOffNote, Byte authzWriteOffNote, Byte authzGuildinfo, Set<Characters> characterses) {
       this.id = id;
       this.guild = guild;
       this.name = name;
       this.authzReadChannel = authzReadChannel;
       this.authzWriteChannel = authzWriteChannel;
       this.authzReadOffChannel = authzReadOffChannel;
       this.authzWriteOffChannel = authzWriteOffChannel;
       this.authzPromote = authzPromote;
       this.authzDemote = authzDemote;
       this.authzInvite = authzInvite;
       this.authzRevoke = authzRevoke;
       this.authzMotd = authzMotd;
       this.authzWriteNote = authzWriteNote;
       this.authzReadOffNote = authzReadOffNote;
       this.authzWriteOffNote = authzWriteOffNote;
       this.authzGuildinfo = authzGuildinfo;
       this.characterses = characterses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkGuildId", column=@Column(name="fk_guild_id", nullable=false) ), 
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ) } )
    public GuildRankId getId() {
        return this.id;
    }
    
    public void setId(GuildRankId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_guild_id", nullable=false, insertable=false, updatable=false)
    public Guild getGuild() {
        return this.guild;
    }
    
    public void setGuild(Guild guild) {
        this.guild = guild;
    }

    
    @Column(name="name", nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="authz_read_channel")
    public Byte getAuthzReadChannel() {
        return this.authzReadChannel;
    }
    
    public void setAuthzReadChannel(Byte authzReadChannel) {
        this.authzReadChannel = authzReadChannel;
    }

    
    @Column(name="authz_write_channel")
    public Byte getAuthzWriteChannel() {
        return this.authzWriteChannel;
    }
    
    public void setAuthzWriteChannel(Byte authzWriteChannel) {
        this.authzWriteChannel = authzWriteChannel;
    }

    
    @Column(name="authz_read_off_channel")
    public Byte getAuthzReadOffChannel() {
        return this.authzReadOffChannel;
    }
    
    public void setAuthzReadOffChannel(Byte authzReadOffChannel) {
        this.authzReadOffChannel = authzReadOffChannel;
    }

    
    @Column(name="authz_write_off_channel")
    public Byte getAuthzWriteOffChannel() {
        return this.authzWriteOffChannel;
    }
    
    public void setAuthzWriteOffChannel(Byte authzWriteOffChannel) {
        this.authzWriteOffChannel = authzWriteOffChannel;
    }

    
    @Column(name="authz_promote")
    public Byte getAuthzPromote() {
        return this.authzPromote;
    }
    
    public void setAuthzPromote(Byte authzPromote) {
        this.authzPromote = authzPromote;
    }

    
    @Column(name="authz_demote")
    public Byte getAuthzDemote() {
        return this.authzDemote;
    }
    
    public void setAuthzDemote(Byte authzDemote) {
        this.authzDemote = authzDemote;
    }

    
    @Column(name="authz_invite")
    public Byte getAuthzInvite() {
        return this.authzInvite;
    }
    
    public void setAuthzInvite(Byte authzInvite) {
        this.authzInvite = authzInvite;
    }

    
    @Column(name="authz_revoke")
    public Byte getAuthzRevoke() {
        return this.authzRevoke;
    }
    
    public void setAuthzRevoke(Byte authzRevoke) {
        this.authzRevoke = authzRevoke;
    }

    
    @Column(name="authz_motd")
    public Byte getAuthzMotd() {
        return this.authzMotd;
    }
    
    public void setAuthzMotd(Byte authzMotd) {
        this.authzMotd = authzMotd;
    }

    
    @Column(name="authz_write_note")
    public Byte getAuthzWriteNote() {
        return this.authzWriteNote;
    }
    
    public void setAuthzWriteNote(Byte authzWriteNote) {
        this.authzWriteNote = authzWriteNote;
    }

    
    @Column(name="authz_read_off_note")
    public Byte getAuthzReadOffNote() {
        return this.authzReadOffNote;
    }
    
    public void setAuthzReadOffNote(Byte authzReadOffNote) {
        this.authzReadOffNote = authzReadOffNote;
    }

    
    @Column(name="authz_write_off_note")
    public Byte getAuthzWriteOffNote() {
        return this.authzWriteOffNote;
    }
    
    public void setAuthzWriteOffNote(Byte authzWriteOffNote) {
        this.authzWriteOffNote = authzWriteOffNote;
    }

    
    @Column(name="authz_guildinfo")
    public Byte getAuthzGuildinfo() {
        return this.authzGuildinfo;
    }
    
    public void setAuthzGuildinfo(Byte authzGuildinfo) {
        this.authzGuildinfo = authzGuildinfo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guildRank")
    public Set<Characters> getCharacterses() {
        return this.characterses;
    }
    
    public void setCharacterses(Set<Characters> characterses) {
        this.characterses = characterses;
    }




}


