package eu.jangos.realm.model.characters;


import java.util.Date;

/**
 * GuildEvents generated by hbm2java
 */
public class GuildEvents  implements java.io.Serializable {


     private GuildEventsId id;
     private Characters charactersByFkEventReceiver;
     private Characters charactersByFkEventSender;
     private Guild guild;
     private GuildEventType guildEventType;
     private Byte rank;
     private Date date;

    public GuildEvents() {
    }

	
    public GuildEvents(GuildEventsId id, Guild guild) {
        this.id = id;
        this.guild = guild;
    }
    public GuildEvents(GuildEventsId id, Characters charactersByFkEventReceiver, Characters charactersByFkEventSender, Guild guild, GuildEventType guildEventType, Byte rank, Date date) {
       this.id = id;
       this.charactersByFkEventReceiver = charactersByFkEventReceiver;
       this.charactersByFkEventSender = charactersByFkEventSender;
       this.guild = guild;
       this.guildEventType = guildEventType;
       this.rank = rank;
       this.date = date;
    }
   
    public GuildEventsId getId() {
        return this.id;
    }
    
    public void setId(GuildEventsId id) {
        this.id = id;
    }
    public Characters getCharactersByFkEventReceiver() {
        return this.charactersByFkEventReceiver;
    }
    
    public void setCharactersByFkEventReceiver(Characters charactersByFkEventReceiver) {
        this.charactersByFkEventReceiver = charactersByFkEventReceiver;
    }
    public Characters getCharactersByFkEventSender() {
        return this.charactersByFkEventSender;
    }
    
    public void setCharactersByFkEventSender(Characters charactersByFkEventSender) {
        this.charactersByFkEventSender = charactersByFkEventSender;
    }
    public Guild getGuild() {
        return this.guild;
    }
    
    public void setGuild(Guild guild) {
        this.guild = guild;
    }
    public GuildEventType getGuildEventType() {
        return this.guildEventType;
    }
    
    public void setGuildEventType(GuildEventType guildEventType) {
        this.guildEventType = guildEventType;
    }
    public Byte getRank() {
        return this.rank;
    }
    
    public void setRank(Byte rank) {
        this.rank = rank;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


