package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GuildEventsId generated by hbm2java
 */
@Embeddable
public class GuildEventsId  implements java.io.Serializable {


     private int id;
     private int fkGuild;

    public GuildEventsId() {
    }

    public GuildEventsId(int id, int fkGuild) {
       this.id = id;
       this.fkGuild = fkGuild;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="fk_guild", nullable=false)
    public int getFkGuild() {
        return this.fkGuild;
    }
    
    public void setFkGuild(int fkGuild) {
        this.fkGuild = fkGuild;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GuildEventsId) ) return false;
		 GuildEventsId castOther = ( GuildEventsId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getFkGuild()==castOther.getFkGuild());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getFkGuild();
         return result;
   }   


}


