package eu.jangos.realm.model.characters;



import java.util.HashSet;
import java.util.Set;

/**
 * GuildEventType generated by hbm2java
 */
public class GuildEventType  implements java.io.Serializable {


     private byte id;
     private String type;
     private Set guildEventses = new HashSet(0);

    public GuildEventType() {
    }

	
    public GuildEventType(byte id) {
        this.id = id;
    }
    public GuildEventType(byte id, String type, Set guildEventses) {
       this.id = id;
       this.type = type;
       this.guildEventses = guildEventses;
    }
   
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getGuildEventses() {
        return this.guildEventses;
    }
    
    public void setGuildEventses(Set guildEventses) {
        this.guildEventses = guildEventses;
    }




}


