package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Guild generated by hbm2java
 */
@Entity
@Table(name="guild"
    ,catalog="jangoscharacters"
)
public class Guild  implements java.io.Serializable {


     private int id;
     private String name;
     private byte emblemstyle;
     private byte emblemcolor;
     private byte borderstyle;
     private byte bordercolor;
     private byte background;
     private String info;
     private String motd;
     private Date creationdate;
     private Byte deleted;
     private Date deletiondate;
     private Set<GuildEvents> guildEventses = new HashSet<GuildEvents>(0);
     private Set<GuildRank> guildRanks = new HashSet<GuildRank>(0);

    public Guild() {
    }

	
    public Guild(int id, String name, byte emblemstyle, byte emblemcolor, byte borderstyle, byte bordercolor, byte background, String info, String motd, Date creationdate) {
        this.id = id;
        this.name = name;
        this.emblemstyle = emblemstyle;
        this.emblemcolor = emblemcolor;
        this.borderstyle = borderstyle;
        this.bordercolor = bordercolor;
        this.background = background;
        this.info = info;
        this.motd = motd;
        this.creationdate = creationdate;
    }
    public Guild(int id, String name, byte emblemstyle, byte emblemcolor, byte borderstyle, byte bordercolor, byte background, String info, String motd, Date creationdate, Byte deleted, Date deletiondate, Set<GuildEvents> guildEventses, Set<GuildRank> guildRanks) {
       this.id = id;
       this.name = name;
       this.emblemstyle = emblemstyle;
       this.emblemcolor = emblemcolor;
       this.borderstyle = borderstyle;
       this.bordercolor = bordercolor;
       this.background = background;
       this.info = info;
       this.motd = motd;
       this.creationdate = creationdate;
       this.deleted = deleted;
       this.deletiondate = deletiondate;
       this.guildEventses = guildEventses;
       this.guildRanks = guildRanks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=24)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="emblemstyle", nullable=false)
    public byte getEmblemstyle() {
        return this.emblemstyle;
    }
    
    public void setEmblemstyle(byte emblemstyle) {
        this.emblemstyle = emblemstyle;
    }

    
    @Column(name="emblemcolor", nullable=false)
    public byte getEmblemcolor() {
        return this.emblemcolor;
    }
    
    public void setEmblemcolor(byte emblemcolor) {
        this.emblemcolor = emblemcolor;
    }

    
    @Column(name="borderstyle", nullable=false)
    public byte getBorderstyle() {
        return this.borderstyle;
    }
    
    public void setBorderstyle(byte borderstyle) {
        this.borderstyle = borderstyle;
    }

    
    @Column(name="bordercolor", nullable=false)
    public byte getBordercolor() {
        return this.bordercolor;
    }
    
    public void setBordercolor(byte bordercolor) {
        this.bordercolor = bordercolor;
    }

    
    @Column(name="background", nullable=false)
    public byte getBackground() {
        return this.background;
    }
    
    public void setBackground(byte background) {
        this.background = background;
    }

    
    @Column(name="info", nullable=false, length=65535)
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }

    
    @Column(name="motd", nullable=false)
    public String getMotd() {
        return this.motd;
    }
    
    public void setMotd(String motd) {
        this.motd = motd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creationdate", nullable=false, length=19)
    public Date getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    
    @Column(name="deleted")
    public Byte getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deletiondate", length=19)
    public Date getDeletiondate() {
        return this.deletiondate;
    }
    
    public void setDeletiondate(Date deletiondate) {
        this.deletiondate = deletiondate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guild")
    public Set<GuildEvents> getGuildEventses() {
        return this.guildEventses;
    }
    
    public void setGuildEventses(Set<GuildEvents> guildEventses) {
        this.guildEventses = guildEventses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guild")
    public Set<GuildRank> getGuildRanks() {
        return this.guildRanks;
    }
    
    public void setGuildRanks(Set<GuildRank> guildRanks) {
        this.guildRanks = guildRanks;
    }




}


