package eu.jangos.realm.model.characters;
// Generated 19-févr.-2016 21:17:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Guild generated by hbm2java
 */
public class Guild  implements java.io.Serializable {


     private int id;
     private String name;
     private byte emblemstyle;
     private byte emblemcolor;
     private byte borderstyle;
     private byte bordercolor;
     private byte background;
     private String info;
     private String motd;
     private Date creationdate;
     private Byte deleted;
     private Date deletiondate;
     private Set guildEventses = new HashSet(0);
     private Set guildRanks = new HashSet(0);

    public Guild() {
    }

	
    public Guild(int id, String name, byte emblemstyle, byte emblemcolor, byte borderstyle, byte bordercolor, byte background, String info, String motd, Date creationdate) {
        this.id = id;
        this.name = name;
        this.emblemstyle = emblemstyle;
        this.emblemcolor = emblemcolor;
        this.borderstyle = borderstyle;
        this.bordercolor = bordercolor;
        this.background = background;
        this.info = info;
        this.motd = motd;
        this.creationdate = creationdate;
    }
    public Guild(int id, String name, byte emblemstyle, byte emblemcolor, byte borderstyle, byte bordercolor, byte background, String info, String motd, Date creationdate, Byte deleted, Date deletiondate, Set guildEventses, Set guildRanks) {
       this.id = id;
       this.name = name;
       this.emblemstyle = emblemstyle;
       this.emblemcolor = emblemcolor;
       this.borderstyle = borderstyle;
       this.bordercolor = bordercolor;
       this.background = background;
       this.info = info;
       this.motd = motd;
       this.creationdate = creationdate;
       this.deleted = deleted;
       this.deletiondate = deletiondate;
       this.guildEventses = guildEventses;
       this.guildRanks = guildRanks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte getEmblemstyle() {
        return this.emblemstyle;
    }
    
    public void setEmblemstyle(byte emblemstyle) {
        this.emblemstyle = emblemstyle;
    }
    public byte getEmblemcolor() {
        return this.emblemcolor;
    }
    
    public void setEmblemcolor(byte emblemcolor) {
        this.emblemcolor = emblemcolor;
    }
    public byte getBorderstyle() {
        return this.borderstyle;
    }
    
    public void setBorderstyle(byte borderstyle) {
        this.borderstyle = borderstyle;
    }
    public byte getBordercolor() {
        return this.bordercolor;
    }
    
    public void setBordercolor(byte bordercolor) {
        this.bordercolor = bordercolor;
    }
    public byte getBackground() {
        return this.background;
    }
    
    public void setBackground(byte background) {
        this.background = background;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public String getMotd() {
        return this.motd;
    }
    
    public void setMotd(String motd) {
        this.motd = motd;
    }
    public Date getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }
    public Byte getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
    public Date getDeletiondate() {
        return this.deletiondate;
    }
    
    public void setDeletiondate(Date deletiondate) {
        this.deletiondate = deletiondate;
    }
    public Set getGuildEventses() {
        return this.guildEventses;
    }
    
    public void setGuildEventses(Set guildEventses) {
        this.guildEventses = guildEventses;
    }
    public Set getGuildRanks() {
        return this.guildRanks;
    }
    
    public void setGuildRanks(Set guildRanks) {
        this.guildRanks = guildRanks;
    }




}


