package eu.jangos.realm.model.characters;
// Generated 19-f�vr.-2016 21:17:55 by Hibernate Tools 4.3.1


import eu.jangos.realm.model.world.Item;
import java.util.HashSet;
import java.util.Set;

/**
 * ItemInstance generated by hbm2java
 */
public class ItemInstance  implements java.io.Serializable {


     private int objectGuid;
     private Characters characters;
     private ItemInstance itemInstanceByFkWrappedIn;
     private ItemInstance itemInstanceByFkStorageBag;
     private ItemStorageType itemStorageType;
     private Byte objectType;
     private Integer fkObjectEntry;
     private Float objectScaleX;
     private Integer objectPadding;
     private Integer fkCreatorGuid;
     private Integer fkGiftGuid;
     private Integer duration;
     private Integer spellCharges1;
     private Integer spellCharges2;
     private Integer spellCharges3;
     private Integer spellCharges4;
     private Integer spellCharges5;
     private Byte binded;
     private Byte unknown1;
     private Byte unlocked;
     private Byte wrapped;
     private Byte unknown4;
     private Byte unknown5;
     private Byte unknown6;
     private Byte unknown7;
     private Byte unknown8;
     private Byte readable;
     private Byte unknown10;
     private Byte unknown11;
     private Byte unknown12;
     private Byte unknown13;
     private Byte unknown14;
     private Byte unknown15;
     private Byte unknown16;
     private Byte unknown17;
     private Integer fkDbcPermEnchantId;
     private Integer permEnchantDuration;
     private Byte permEnchantCharges;
     private Integer fkDbcTempEnchantId;
     private Integer tempEnchantDuration;
     private Byte tempEnchantCharges;
     private Integer fkDbcProp0EnchantId;
     private Integer prop0EnchantDuration;
     private Byte prop0EnchantCharges;
     private Integer fkDbcProp1EnchantId;
     private Integer prop1EnchantDuration;
     private Byte prop1EnchantCharges;
     private Integer fkDbcProp2EnchantId;
     private Integer prop2EnchantDuration;
     private Byte prop2EnchantCharges;
     private Integer fkDbcProp3EnchantId;
     private Integer prop3EnchantDuration;
     private Byte prop3EnchantCharges;
     private Integer fkDbcProp4EnchantId;
     private Integer prop4EnchantDuration;
     private Byte prop4EnchantCharges;
     private Integer propertySeed;
     private Integer fkDbcRandomPropertyId;
     private Integer fkItemTextId;
     private Integer durability;
     private Byte slot;
     private short stackCount;
     private String guildPetitionName;
     private Set equipments = new HashSet(0);
     private Set itemInstancesForFkWrappedIn = new HashSet(0);
     private Set itemInstancesForFkStorageBag = new HashSet(0);
     private Set characterses = new HashSet(0);

    public ItemInstance() {
    }

	
    public ItemInstance(int objectGuid) {
        this.objectGuid = objectGuid;
    }
    public ItemInstance(int objectGuid, Characters characters, ItemInstance itemInstanceByFkWrappedIn, ItemInstance itemInstanceByFkStorageBag, ItemStorageType itemStorageType, Byte objectType, Integer fkObjectEntry, Float objectScaleX, Integer objectPadding, Integer fkCreatorGuid, Integer fkGiftGuid, Integer duration, Integer spellCharges1, Integer spellCharges2, Integer spellCharges3, Integer spellCharges4, Integer spellCharges5, Byte binded, Byte unknown1, Byte unlocked, Byte wrapped, Byte unknown4, Byte unknown5, Byte unknown6, Byte unknown7, Byte unknown8, Byte readable, Byte unknown10, Byte unknown11, Byte unknown12, Byte unknown13, Byte unknown14, Byte unknown15, Byte unknown16, Byte unknown17, Integer fkDbcPermEnchantId, Integer permEnchantDuration, Byte permEnchantCharges, Integer fkDbcTempEnchantId, Integer tempEnchantDuration, Byte tempEnchantCharges, Integer fkDbcProp0EnchantId, Integer prop0EnchantDuration, Byte prop0EnchantCharges, Integer fkDbcProp1EnchantId, Integer prop1EnchantDuration, Byte prop1EnchantCharges, Integer fkDbcProp2EnchantId, Integer prop2EnchantDuration, Byte prop2EnchantCharges, Integer fkDbcProp3EnchantId, Integer prop3EnchantDuration, Byte prop3EnchantCharges, Integer fkDbcProp4EnchantId, Integer prop4EnchantDuration, Byte prop4EnchantCharges, Integer propertySeed, Integer fkDbcRandomPropertyId, Integer fkItemTextId, Integer durability, Byte slot, short stackCount, String guildPetitionName, Set equipments, Set itemInstancesForFkWrappedIn, Set itemInstancesForFkStorageBag, Set characterses) {
       this.objectGuid = objectGuid;
       this.characters = characters;
       this.itemInstanceByFkWrappedIn = itemInstanceByFkWrappedIn;
       this.itemInstanceByFkStorageBag = itemInstanceByFkStorageBag;
       this.itemStorageType = itemStorageType;
       this.objectType = objectType;
       this.fkObjectEntry = fkObjectEntry;
       this.objectScaleX = objectScaleX;
       this.objectPadding = objectPadding;
       this.fkCreatorGuid = fkCreatorGuid;
       this.fkGiftGuid = fkGiftGuid;
       this.duration = duration;
       this.spellCharges1 = spellCharges1;
       this.spellCharges2 = spellCharges2;
       this.spellCharges3 = spellCharges3;
       this.spellCharges4 = spellCharges4;
       this.spellCharges5 = spellCharges5;
       this.binded = binded;
       this.unknown1 = unknown1;
       this.unlocked = unlocked;
       this.wrapped = wrapped;
       this.unknown4 = unknown4;
       this.unknown5 = unknown5;
       this.unknown6 = unknown6;
       this.unknown7 = unknown7;
       this.unknown8 = unknown8;
       this.readable = readable;
       this.unknown10 = unknown10;
       this.unknown11 = unknown11;
       this.unknown12 = unknown12;
       this.unknown13 = unknown13;
       this.unknown14 = unknown14;
       this.unknown15 = unknown15;
       this.unknown16 = unknown16;
       this.unknown17 = unknown17;
       this.fkDbcPermEnchantId = fkDbcPermEnchantId;
       this.permEnchantDuration = permEnchantDuration;
       this.permEnchantCharges = permEnchantCharges;
       this.fkDbcTempEnchantId = fkDbcTempEnchantId;
       this.tempEnchantDuration = tempEnchantDuration;
       this.tempEnchantCharges = tempEnchantCharges;
       this.fkDbcProp0EnchantId = fkDbcProp0EnchantId;
       this.prop0EnchantDuration = prop0EnchantDuration;
       this.prop0EnchantCharges = prop0EnchantCharges;
       this.fkDbcProp1EnchantId = fkDbcProp1EnchantId;
       this.prop1EnchantDuration = prop1EnchantDuration;
       this.prop1EnchantCharges = prop1EnchantCharges;
       this.fkDbcProp2EnchantId = fkDbcProp2EnchantId;
       this.prop2EnchantDuration = prop2EnchantDuration;
       this.prop2EnchantCharges = prop2EnchantCharges;
       this.fkDbcProp3EnchantId = fkDbcProp3EnchantId;
       this.prop3EnchantDuration = prop3EnchantDuration;
       this.prop3EnchantCharges = prop3EnchantCharges;
       this.fkDbcProp4EnchantId = fkDbcProp4EnchantId;
       this.prop4EnchantDuration = prop4EnchantDuration;
       this.prop4EnchantCharges = prop4EnchantCharges;
       this.propertySeed = propertySeed;
       this.fkDbcRandomPropertyId = fkDbcRandomPropertyId;
       this.fkItemTextId = fkItemTextId;
       this.durability = durability;
       this.slot = slot;
       this.stackCount = stackCount;
       this.guildPetitionName = guildPetitionName;
       this.equipments = equipments;
       this.itemInstancesForFkWrappedIn = itemInstancesForFkWrappedIn;
       this.itemInstancesForFkStorageBag = itemInstancesForFkStorageBag;
       this.characterses = characterses;    
    }
   
    public int getObjectGuid() {
        return this.objectGuid;
    }
    
    public void setObjectGuid(int objectGuid) {
        this.objectGuid = objectGuid;
    }
    public Characters getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Characters characters) {
        this.characters = characters;
    }
    public ItemInstance getItemInstanceByFkWrappedIn() {
        return this.itemInstanceByFkWrappedIn;
    }
    
    public void setItemInstanceByFkWrappedIn(ItemInstance itemInstanceByFkWrappedIn) {
        this.itemInstanceByFkWrappedIn = itemInstanceByFkWrappedIn;
    }
    public ItemInstance getItemInstanceByFkStorageBag() {
        return this.itemInstanceByFkStorageBag;
    }
    
    public void setItemInstanceByFkStorageBag(ItemInstance itemInstanceByFkStorageBag) {
        this.itemInstanceByFkStorageBag = itemInstanceByFkStorageBag;
    }
    public ItemStorageType getItemStorageType() {
        return this.itemStorageType;
    }
    
    public void setItemStorageType(ItemStorageType itemStorageType) {
        this.itemStorageType = itemStorageType;
    }
    public Byte getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(Byte objectType) {
        this.objectType = objectType;
    }
    public Integer getFkObjectEntry() {
        return this.fkObjectEntry;
    }
    
    public void setFkObjectEntry(Integer fkObjectEntry) {
        this.fkObjectEntry = fkObjectEntry;
    }
    public Float getObjectScaleX() {
        return this.objectScaleX;
    }
    
    public void setObjectScaleX(Float objectScaleX) {
        this.objectScaleX = objectScaleX;
    }
    public Integer getObjectPadding() {
        return this.objectPadding;
    }
    
    public void setObjectPadding(Integer objectPadding) {
        this.objectPadding = objectPadding;
    }
    public Integer getFkCreatorGuid() {
        return this.fkCreatorGuid;
    }
    
    public void setFkCreatorGuid(Integer fkCreatorGuid) {
        this.fkCreatorGuid = fkCreatorGuid;
    }
    public Integer getFkGiftGuid() {
        return this.fkGiftGuid;
    }
    
    public void setFkGiftGuid(Integer fkGiftGuid) {
        this.fkGiftGuid = fkGiftGuid;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    public Integer getSpellCharges1() {
        return this.spellCharges1;
    }
    
    public void setSpellCharges1(Integer spellCharges1) {
        this.spellCharges1 = spellCharges1;
    }
    public Integer getSpellCharges2() {
        return this.spellCharges2;
    }
    
    public void setSpellCharges2(Integer spellCharges2) {
        this.spellCharges2 = spellCharges2;
    }
    public Integer getSpellCharges3() {
        return this.spellCharges3;
    }
    
    public void setSpellCharges3(Integer spellCharges3) {
        this.spellCharges3 = spellCharges3;
    }
    public Integer getSpellCharges4() {
        return this.spellCharges4;
    }
    
    public void setSpellCharges4(Integer spellCharges4) {
        this.spellCharges4 = spellCharges4;
    }
    public Integer getSpellCharges5() {
        return this.spellCharges5;
    }
    
    public void setSpellCharges5(Integer spellCharges5) {
        this.spellCharges5 = spellCharges5;
    }
    public Byte getBinded() {
        return this.binded;
    }
    
    public void setBinded(Byte binded) {
        this.binded = binded;
    }
    public Byte getUnknown1() {
        return this.unknown1;
    }
    
    public void setUnknown1(Byte unknown1) {
        this.unknown1 = unknown1;
    }
    public Byte getUnlocked() {
        return this.unlocked;
    }
    
    public void setUnlocked(Byte unlocked) {
        this.unlocked = unlocked;
    }
    public Byte getWrapped() {
        return this.wrapped;
    }
    
    public void setWrapped(Byte wrapped) {
        this.wrapped = wrapped;
    }
    public Byte getUnknown4() {
        return this.unknown4;
    }
    
    public void setUnknown4(Byte unknown4) {
        this.unknown4 = unknown4;
    }
    public Byte getUnknown5() {
        return this.unknown5;
    }
    
    public void setUnknown5(Byte unknown5) {
        this.unknown5 = unknown5;
    }
    public Byte getUnknown6() {
        return this.unknown6;
    }
    
    public void setUnknown6(Byte unknown6) {
        this.unknown6 = unknown6;
    }
    public Byte getUnknown7() {
        return this.unknown7;
    }
    
    public void setUnknown7(Byte unknown7) {
        this.unknown7 = unknown7;
    }
    public Byte getUnknown8() {
        return this.unknown8;
    }
    
    public void setUnknown8(Byte unknown8) {
        this.unknown8 = unknown8;
    }
    public Byte getReadable() {
        return this.readable;
    }
    
    public void setReadable(Byte readable) {
        this.readable = readable;
    }
    public Byte getUnknown10() {
        return this.unknown10;
    }
    
    public void setUnknown10(Byte unknown10) {
        this.unknown10 = unknown10;
    }
    public Byte getUnknown11() {
        return this.unknown11;
    }
    
    public void setUnknown11(Byte unknown11) {
        this.unknown11 = unknown11;
    }
    public Byte getUnknown12() {
        return this.unknown12;
    }
    
    public void setUnknown12(Byte unknown12) {
        this.unknown12 = unknown12;
    }
    public Byte getUnknown13() {
        return this.unknown13;
    }
    
    public void setUnknown13(Byte unknown13) {
        this.unknown13 = unknown13;
    }
    public Byte getUnknown14() {
        return this.unknown14;
    }
    
    public void setUnknown14(Byte unknown14) {
        this.unknown14 = unknown14;
    }
    public Byte getUnknown15() {
        return this.unknown15;
    }
    
    public void setUnknown15(Byte unknown15) {
        this.unknown15 = unknown15;
    }
    public Byte getUnknown16() {
        return this.unknown16;
    }
    
    public void setUnknown16(Byte unknown16) {
        this.unknown16 = unknown16;
    }
    public Byte getUnknown17() {
        return this.unknown17;
    }
    
    public void setUnknown17(Byte unknown17) {
        this.unknown17 = unknown17;
    }
    public Integer getFkDbcPermEnchantId() {
        return this.fkDbcPermEnchantId;
    }
    
    public void setFkDbcPermEnchantId(Integer fkDbcPermEnchantId) {
        this.fkDbcPermEnchantId = fkDbcPermEnchantId;
    }
    public Integer getPermEnchantDuration() {
        return this.permEnchantDuration;
    }
    
    public void setPermEnchantDuration(Integer permEnchantDuration) {
        this.permEnchantDuration = permEnchantDuration;
    }
    public Byte getPermEnchantCharges() {
        return this.permEnchantCharges;
    }
    
    public void setPermEnchantCharges(Byte permEnchantCharges) {
        this.permEnchantCharges = permEnchantCharges;
    }
    public Integer getFkDbcTempEnchantId() {
        return this.fkDbcTempEnchantId;
    }
    
    public void setFkDbcTempEnchantId(Integer fkDbcTempEnchantId) {
        this.fkDbcTempEnchantId = fkDbcTempEnchantId;
    }
    public Integer getTempEnchantDuration() {
        return this.tempEnchantDuration;
    }
    
    public void setTempEnchantDuration(Integer tempEnchantDuration) {
        this.tempEnchantDuration = tempEnchantDuration;
    }
    public Byte getTempEnchantCharges() {
        return this.tempEnchantCharges;
    }
    
    public void setTempEnchantCharges(Byte tempEnchantCharges) {
        this.tempEnchantCharges = tempEnchantCharges;
    }
    public Integer getFkDbcProp0EnchantId() {
        return this.fkDbcProp0EnchantId;
    }
    
    public void setFkDbcProp0EnchantId(Integer fkDbcProp0EnchantId) {
        this.fkDbcProp0EnchantId = fkDbcProp0EnchantId;
    }
    public Integer getProp0EnchantDuration() {
        return this.prop0EnchantDuration;
    }
    
    public void setProp0EnchantDuration(Integer prop0EnchantDuration) {
        this.prop0EnchantDuration = prop0EnchantDuration;
    }
    public Byte getProp0EnchantCharges() {
        return this.prop0EnchantCharges;
    }
    
    public void setProp0EnchantCharges(Byte prop0EnchantCharges) {
        this.prop0EnchantCharges = prop0EnchantCharges;
    }
    public Integer getFkDbcProp1EnchantId() {
        return this.fkDbcProp1EnchantId;
    }
    
    public void setFkDbcProp1EnchantId(Integer fkDbcProp1EnchantId) {
        this.fkDbcProp1EnchantId = fkDbcProp1EnchantId;
    }
    public Integer getProp1EnchantDuration() {
        return this.prop1EnchantDuration;
    }
    
    public void setProp1EnchantDuration(Integer prop1EnchantDuration) {
        this.prop1EnchantDuration = prop1EnchantDuration;
    }
    public Byte getProp1EnchantCharges() {
        return this.prop1EnchantCharges;
    }
    
    public void setProp1EnchantCharges(Byte prop1EnchantCharges) {
        this.prop1EnchantCharges = prop1EnchantCharges;
    }
    public Integer getFkDbcProp2EnchantId() {
        return this.fkDbcProp2EnchantId;
    }
    
    public void setFkDbcProp2EnchantId(Integer fkDbcProp2EnchantId) {
        this.fkDbcProp2EnchantId = fkDbcProp2EnchantId;
    }
    public Integer getProp2EnchantDuration() {
        return this.prop2EnchantDuration;
    }
    
    public void setProp2EnchantDuration(Integer prop2EnchantDuration) {
        this.prop2EnchantDuration = prop2EnchantDuration;
    }
    public Byte getProp2EnchantCharges() {
        return this.prop2EnchantCharges;
    }
    
    public void setProp2EnchantCharges(Byte prop2EnchantCharges) {
        this.prop2EnchantCharges = prop2EnchantCharges;
    }
    public Integer getFkDbcProp3EnchantId() {
        return this.fkDbcProp3EnchantId;
    }
    
    public void setFkDbcProp3EnchantId(Integer fkDbcProp3EnchantId) {
        this.fkDbcProp3EnchantId = fkDbcProp3EnchantId;
    }
    public Integer getProp3EnchantDuration() {
        return this.prop3EnchantDuration;
    }
    
    public void setProp3EnchantDuration(Integer prop3EnchantDuration) {
        this.prop3EnchantDuration = prop3EnchantDuration;
    }
    public Byte getProp3EnchantCharges() {
        return this.prop3EnchantCharges;
    }
    
    public void setProp3EnchantCharges(Byte prop3EnchantCharges) {
        this.prop3EnchantCharges = prop3EnchantCharges;
    }
    public Integer getFkDbcProp4EnchantId() {
        return this.fkDbcProp4EnchantId;
    }
    
    public void setFkDbcProp4EnchantId(Integer fkDbcProp4EnchantId) {
        this.fkDbcProp4EnchantId = fkDbcProp4EnchantId;
    }
    public Integer getProp4EnchantDuration() {
        return this.prop4EnchantDuration;
    }
    
    public void setProp4EnchantDuration(Integer prop4EnchantDuration) {
        this.prop4EnchantDuration = prop4EnchantDuration;
    }
    public Byte getProp4EnchantCharges() {
        return this.prop4EnchantCharges;
    }
    
    public void setProp4EnchantCharges(Byte prop4EnchantCharges) {
        this.prop4EnchantCharges = prop4EnchantCharges;
    }
    public Integer getPropertySeed() {
        return this.propertySeed;
    }
    
    public void setPropertySeed(Integer propertySeed) {
        this.propertySeed = propertySeed;
    }
    public Integer getFkDbcRandomPropertyId() {
        return this.fkDbcRandomPropertyId;
    }
    
    public void setFkDbcRandomPropertyId(Integer fkDbcRandomPropertyId) {
        this.fkDbcRandomPropertyId = fkDbcRandomPropertyId;
    }
    public Integer getFkItemTextId() {
        return this.fkItemTextId;
    }
    
    public void setFkItemTextId(Integer fkItemTextId) {
        this.fkItemTextId = fkItemTextId;
    }
    public Integer getDurability() {
        return this.durability;
    }
    
    public void setDurability(Integer durability) {
        this.durability = durability;
    }
    public Byte getSlot() {
        return this.slot;
    }
    
    public void setSlot(Byte slot) {
        this.slot = slot;
    }
    public short getStackCount() {
        return this.stackCount;
    }
    
    public void setStackCount(short stackCount) {
        this.stackCount = stackCount;
    }
    public String getGuildPetitionName() {
        return this.guildPetitionName;
    }
    
    public void setGuildPetitionName(String guildPetitionName) {
        this.guildPetitionName = guildPetitionName;
    }
    public Set getEquipments() {
        return this.equipments;
    }
    
    public void setEquipments(Set equipments) {
        this.equipments = equipments;
    }
    public Set getItemInstancesForFkWrappedIn() {
        return this.itemInstancesForFkWrappedIn;
    }
    
    public void setItemInstancesForFkWrappedIn(Set itemInstancesForFkWrappedIn) {
        this.itemInstancesForFkWrappedIn = itemInstancesForFkWrappedIn;
    }
    public Set getItemInstancesForFkStorageBag() {
        return this.itemInstancesForFkStorageBag;
    }
    
    public void setItemInstancesForFkStorageBag(Set itemInstancesForFkStorageBag) {
        this.itemInstancesForFkStorageBag = itemInstancesForFkStorageBag;
    }
    public Set getCharacterses() {
        return this.characterses;
    }
    
    public void setCharacterses(Set characterses) {
        this.characterses = characterses;
    }




}


