package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItemStorageType generated by hbm2java
 */
@Entity
@Table(name="item_storage_type"
    ,catalog="jangoscharacters"
)
public class ItemStorageType  implements java.io.Serializable {


     private byte id;
     private String type;
     private Set<ItemInstance> itemInstances = new HashSet<ItemInstance>(0);

    public ItemStorageType() {
    }

	
    public ItemStorageType(byte id) {
        this.id = id;
    }
    public ItemStorageType(byte id, String type, Set<ItemInstance> itemInstances) {
       this.id = id;
       this.type = type;
       this.itemInstances = itemInstances;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemStorageType")
    public Set<ItemInstance> getItemInstances() {
        return this.itemInstances;
    }
    
    public void setItemInstances(Set<ItemInstance> itemInstances) {
        this.itemInstances = itemInstances;
    }




}


