package eu.jangos.realm.model.characters;
// Generated 19-févr.-2016 21:17:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ItemStorageType generated by hbm2java
 */
public class ItemStorageType  implements java.io.Serializable {


     private byte id;
     private String type;
     private Set itemInstances = new HashSet(0);

    public ItemStorageType() {
    }

	
    public ItemStorageType(byte id) {
        this.id = id;
    }
    public ItemStorageType(byte id, String type, Set itemInstances) {
       this.id = id;
       this.type = type;
       this.itemInstances = itemInstances;
    }
   
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getItemInstances() {
        return this.itemInstances;
    }
    
    public void setItemInstances(Set itemInstances) {
        this.itemInstances = itemInstances;
    }




}


