package eu.jangos.realm.model.characters;



import java.util.Date;

/**
 * Mail generated by hbm2java
 */
public class Mail  implements java.io.Serializable {


     private int id;
     private Characters charactersByFkFrom;
     private Characters charactersByFkTo;
     private byte fkType;
     private byte fkDbcStationery;
     private int fkDbcMailTemplateId;
     private String subject;
     private String body;
     private Date expire;
     private Date deliver;
     private int money;
     private int cod;
     private byte isRead;
     private byte isReturned;
     private byte isCopied;

    public Mail() {
    }

	
    public Mail(int id, Characters charactersByFkFrom, Characters charactersByFkTo, byte fkType, byte fkDbcStationery, int fkDbcMailTemplateId, String body, Date expire, Date deliver, int money, int cod, byte isRead, byte isReturned, byte isCopied) {
        this.id = id;
        this.charactersByFkFrom = charactersByFkFrom;
        this.charactersByFkTo = charactersByFkTo;
        this.fkType = fkType;
        this.fkDbcStationery = fkDbcStationery;
        this.fkDbcMailTemplateId = fkDbcMailTemplateId;
        this.body = body;
        this.expire = expire;
        this.deliver = deliver;
        this.money = money;
        this.cod = cod;
        this.isRead = isRead;
        this.isReturned = isReturned;
        this.isCopied = isCopied;
    }
    public Mail(int id, Characters charactersByFkFrom, Characters charactersByFkTo, byte fkType, byte fkDbcStationery, int fkDbcMailTemplateId, String subject, String body, Date expire, Date deliver, int money, int cod, byte isRead, byte isReturned, byte isCopied) {
       this.id = id;
       this.charactersByFkFrom = charactersByFkFrom;
       this.charactersByFkTo = charactersByFkTo;
       this.fkType = fkType;
       this.fkDbcStationery = fkDbcStationery;
       this.fkDbcMailTemplateId = fkDbcMailTemplateId;
       this.subject = subject;
       this.body = body;
       this.expire = expire;
       this.deliver = deliver;
       this.money = money;
       this.cod = cod;
       this.isRead = isRead;
       this.isReturned = isReturned;
       this.isCopied = isCopied;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Characters getCharactersByFkFrom() {
        return this.charactersByFkFrom;
    }
    
    public void setCharactersByFkFrom(Characters charactersByFkFrom) {
        this.charactersByFkFrom = charactersByFkFrom;
    }
    public Characters getCharactersByFkTo() {
        return this.charactersByFkTo;
    }
    
    public void setCharactersByFkTo(Characters charactersByFkTo) {
        this.charactersByFkTo = charactersByFkTo;
    }
    public byte getFkType() {
        return this.fkType;
    }
    
    public void setFkType(byte fkType) {
        this.fkType = fkType;
    }
    public byte getFkDbcStationery() {
        return this.fkDbcStationery;
    }
    
    public void setFkDbcStationery(byte fkDbcStationery) {
        this.fkDbcStationery = fkDbcStationery;
    }
    public int getFkDbcMailTemplateId() {
        return this.fkDbcMailTemplateId;
    }
    
    public void setFkDbcMailTemplateId(int fkDbcMailTemplateId) {
        this.fkDbcMailTemplateId = fkDbcMailTemplateId;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Date getExpire() {
        return this.expire;
    }
    
    public void setExpire(Date expire) {
        this.expire = expire;
    }
    public Date getDeliver() {
        return this.deliver;
    }
    
    public void setDeliver(Date deliver) {
        this.deliver = deliver;
    }
    public int getMoney() {
        return this.money;
    }
    
    public void setMoney(int money) {
        this.money = money;
    }
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }
    public byte getIsRead() {
        return this.isRead;
    }
    
    public void setIsRead(byte isRead) {
        this.isRead = isRead;
    }
    public byte getIsReturned() {
        return this.isReturned;
    }
    
    public void setIsReturned(byte isReturned) {
        this.isReturned = isReturned;
    }
    public byte getIsCopied() {
        return this.isCopied;
    }
    
    public void setIsCopied(byte isCopied) {
        this.isCopied = isCopied;
    }




}


