package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReputationId generated by hbm2java
 */
@Embeddable
public class ReputationId  implements java.io.Serializable {


     private long fkGuid;
     private int fkDbcFaction;

    public ReputationId() {
    }

    public ReputationId(long fkGuid, int fkDbcFaction) {
       this.fkGuid = fkGuid;
       this.fkDbcFaction = fkDbcFaction;
    }
   


    @Column(name="fk_guid", nullable=false)
    public long getFkGuid() {
        return this.fkGuid;
    }
    
    public void setFkGuid(long fkGuid) {
        this.fkGuid = fkGuid;
    }


    @Column(name="fk_dbc_faction", nullable=false)
    public int getFkDbcFaction() {
        return this.fkDbcFaction;
    }
    
    public void setFkDbcFaction(int fkDbcFaction) {
        this.fkDbcFaction = fkDbcFaction;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReputationId) ) return false;
		 ReputationId castOther = ( ReputationId ) other; 
         
		 return (this.getFkGuid()==castOther.getFkGuid())
 && (this.getFkDbcFaction()==castOther.getFkDbcFaction());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getFkGuid();
         result = 37 * result + this.getFkDbcFaction();
         return result;
   }   


}


