package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reputation generated by hbm2java
 */
@Entity
@Table(name="reputation"
    ,catalog="jangoscharacters"
)
public class Reputation  implements java.io.Serializable {


     private ReputationId id;
     private Characters characters;
     private int standing;
     private byte visible;
     private byte war;
     private byte hidden;
     private byte invisible;
     private byte peace;
     private byte inactive;
     private byte rival;

    public Reputation() {
    }

    public Reputation(ReputationId id, Characters characters, int standing, byte visible, byte war, byte hidden, byte invisible, byte peace, byte inactive, byte rival) {
       this.id = id;
       this.characters = characters;
       this.standing = standing;
       this.visible = visible;
       this.war = war;
       this.hidden = hidden;
       this.invisible = invisible;
       this.peace = peace;
       this.inactive = inactive;
       this.rival = rival;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkGuid", column=@Column(name="fk_guid", nullable=false) ), 
        @AttributeOverride(name="fkDbcFaction", column=@Column(name="fk_dbc_faction", nullable=false) ) } )
    public ReputationId getId() {
        return this.id;
    }
    
    public void setId(ReputationId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_guid", nullable=false, insertable=false, updatable=false)
    public Characters getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Characters characters) {
        this.characters = characters;
    }

    
    @Column(name="standing", nullable=false)
    public int getStanding() {
        return this.standing;
    }
    
    public void setStanding(int standing) {
        this.standing = standing;
    }

    
    @Column(name="visible", nullable=false)
    public byte getVisible() {
        return this.visible;
    }
    
    public void setVisible(byte visible) {
        this.visible = visible;
    }

    
    @Column(name="war", nullable=false)
    public byte getWar() {
        return this.war;
    }
    
    public void setWar(byte war) {
        this.war = war;
    }

    
    @Column(name="hidden", nullable=false)
    public byte getHidden() {
        return this.hidden;
    }
    
    public void setHidden(byte hidden) {
        this.hidden = hidden;
    }

    
    @Column(name="invisible", nullable=false)
    public byte getInvisible() {
        return this.invisible;
    }
    
    public void setInvisible(byte invisible) {
        this.invisible = invisible;
    }

    
    @Column(name="peace", nullable=false)
    public byte getPeace() {
        return this.peace;
    }
    
    public void setPeace(byte peace) {
        this.peace = peace;
    }

    
    @Column(name="inactive", nullable=false)
    public byte getInactive() {
        return this.inactive;
    }
    
    public void setInactive(byte inactive) {
        this.inactive = inactive;
    }

    
    @Column(name="rival", nullable=false)
    public byte getRival() {
        return this.rival;
    }
    
    public void setRival(byte rival) {
        this.rival = rival;
    }




}


