package eu.jangos.realm.model.characters;




/**
 * Reputation generated by hbm2java
 */
public class Reputation  implements java.io.Serializable {


     private ReputationId id;
     private Characters characters;
     private int standing;
     private byte visible;
     private byte war;
     private byte hidden;
     private byte invisible;
     private byte peace;
     private byte inactive;
     private byte rival;

    public Reputation() {
    }

    public Reputation(ReputationId id, Characters characters, int standing, byte visible, byte war, byte hidden, byte invisible, byte peace, byte inactive, byte rival) {
       this.id = id;
       this.characters = characters;
       this.standing = standing;
       this.visible = visible;
       this.war = war;
       this.hidden = hidden;
       this.invisible = invisible;
       this.peace = peace;
       this.inactive = inactive;
       this.rival = rival;
    }
   
    public ReputationId getId() {
        return this.id;
    }
    
    public void setId(ReputationId id) {
        this.id = id;
    }
    public Characters getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Characters characters) {
        this.characters = characters;
    }
    public int getStanding() {
        return this.standing;
    }
    
    public void setStanding(int standing) {
        this.standing = standing;
    }
    public byte getVisible() {
        return this.visible;
    }
    
    public void setVisible(byte visible) {
        this.visible = visible;
    }
    public byte getWar() {
        return this.war;
    }
    
    public void setWar(byte war) {
        this.war = war;
    }
    public byte getHidden() {
        return this.hidden;
    }
    
    public void setHidden(byte hidden) {
        this.hidden = hidden;
    }
    public byte getInvisible() {
        return this.invisible;
    }
    
    public void setInvisible(byte invisible) {
        this.invisible = invisible;
    }
    public byte getPeace() {
        return this.peace;
    }
    
    public void setPeace(byte peace) {
        this.peace = peace;
    }
    public byte getInactive() {
        return this.inactive;
    }
    
    public void setInactive(byte inactive) {
        this.inactive = inactive;
    }
    public byte getRival() {
        return this.rival;
    }
    
    public void setRival(byte rival) {
        this.rival = rival;
    }




}


