package eu.jangos.realm.model.characters;




/**
 * ReputationId generated by hbm2java
 */
public class ReputationId  implements java.io.Serializable {


     private int fkGuid;
     private int fkDbcFaction;

    public ReputationId() {
    }

    public ReputationId(int fkGuid, int fkDbcFaction) {
       this.fkGuid = fkGuid;
       this.fkDbcFaction = fkDbcFaction;
    }
   
    public int getFkGuid() {
        return this.fkGuid;
    }
    
    public void setFkGuid(int fkGuid) {
        this.fkGuid = fkGuid;
    }
    public int getFkDbcFaction() {
        return this.fkDbcFaction;
    }
    
    public void setFkDbcFaction(int fkDbcFaction) {
        this.fkDbcFaction = fkDbcFaction;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReputationId) ) return false;
		 ReputationId castOther = ( ReputationId ) other; 
         
		 return (this.getFkGuid()==castOther.getFkGuid())
 && (this.getFkDbcFaction()==castOther.getFkDbcFaction());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkGuid();
         result = 37 * result + this.getFkDbcFaction();
         return result;
   }   


}


