package eu.jangos.realm.model.characters;



/**
 * SkillsId generated by hbm2java
 */
public class SkillsId  implements java.io.Serializable {


     private int fkGuid;
     private int fkDbcSkill;

    public SkillsId() {
    }

    public SkillsId(int fkGuid, int fkDbcSkill) {
       this.fkGuid = fkGuid;
       this.fkDbcSkill = fkDbcSkill;
    }
   
    public int getFkGuid() {
        return this.fkGuid;
    }
    
    public void setFkGuid(int fkGuid) {
        this.fkGuid = fkGuid;
    }
    public int getFkDbcSkill() {
        return this.fkDbcSkill;
    }
    
    public void setFkDbcSkill(int fkDbcSkill) {
        this.fkDbcSkill = fkDbcSkill;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SkillsId) ) return false;
		 SkillsId castOther = ( SkillsId ) other; 
         
		 return (this.getFkGuid()==castOther.getFkGuid())
 && (this.getFkDbcSkill()==castOther.getFkDbcSkill());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkGuid();
         result = 37 * result + this.getFkDbcSkill();
         return result;
   }   


}


