package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SkillsId generated by hbm2java
 */
@Embeddable
public class SkillsId  implements java.io.Serializable {


     private long fkGuid;
     private int fkDbcSkill;

    public SkillsId() {
    }

    public SkillsId(long fkGuid, int fkDbcSkill) {
       this.fkGuid = fkGuid;
       this.fkDbcSkill = fkDbcSkill;
    }
   


    @Column(name="fk_guid", nullable=false)
    public long getFkGuid() {
        return this.fkGuid;
    }
    
    public void setFkGuid(long fkGuid) {
        this.fkGuid = fkGuid;
    }


    @Column(name="fk_dbc_skill", nullable=false)
    public int getFkDbcSkill() {
        return this.fkDbcSkill;
    }
    
    public void setFkDbcSkill(int fkDbcSkill) {
        this.fkDbcSkill = fkDbcSkill;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SkillsId) ) return false;
		 SkillsId castOther = ( SkillsId ) other; 
         
		 return (this.getFkGuid()==castOther.getFkGuid())
 && (this.getFkDbcSkill()==castOther.getFkDbcSkill());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getFkGuid();
         result = 37 * result + this.getFkDbcSkill();
         return result;
   }   


}


