package eu.jangos.realm.model.characters;




/**
 * Skills generated by hbm2java
 */
public class Skills  implements java.io.Serializable {


     private SkillsId id;
     private Characters characters;
     private int value;
     private int max;

    public Skills() {
    }

    public Skills(SkillsId id, Characters characters, int value, int max) {
       this.id = id;
       this.characters = characters;
       this.value = value;
       this.max = max;
    }
   
    public SkillsId getId() {
        return this.id;
    }
    
    public void setId(SkillsId id) {
        this.id = id;
    }
    public Characters getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Characters characters) {
        this.characters = characters;
    }
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }
    public int getMax() {
        return this.max;
    }
    
    public void setMax(int max) {
        this.max = max;
    }




}


