package eu.jangos.realm.model.characters;
// Generated 19-févr.-2016 21:17:55 by Hibernate Tools 4.3.1



/**
 * Social generated by hbm2java
 */
public class Social  implements java.io.Serializable {


     private SocialId id;
     private Characters charactersByFkOwner;
     private Characters charactersByFkRelation;

    public Social() {
    }

    public Social(SocialId id, Characters charactersByFkOwner, Characters charactersByFkRelation) {
       this.id = id;
       this.charactersByFkOwner = charactersByFkOwner;
       this.charactersByFkRelation = charactersByFkRelation;
    }
   
    public SocialId getId() {
        return this.id;
    }
    
    public void setId(SocialId id) {
        this.id = id;
    }
    public Characters getCharactersByFkOwner() {
        return this.charactersByFkOwner;
    }
    
    public void setCharactersByFkOwner(Characters charactersByFkOwner) {
        this.charactersByFkOwner = charactersByFkOwner;
    }
    public Characters getCharactersByFkRelation() {
        return this.charactersByFkRelation;
    }
    
    public void setCharactersByFkRelation(Characters charactersByFkRelation) {
        this.charactersByFkRelation = charactersByFkRelation;
    }




}


