package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Social generated by hbm2java
 */
@Entity
@Table(name="social"
    ,catalog="jangoscharacters"
)
public class Social  implements java.io.Serializable {


     private SocialId id;
     private Characters charactersByFkOwner;
     private Characters charactersByFkRelation;

    public Social() {
    }

    public Social(SocialId id, Characters charactersByFkOwner, Characters charactersByFkRelation) {
       this.id = id;
       this.charactersByFkOwner = charactersByFkOwner;
       this.charactersByFkRelation = charactersByFkRelation;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkOwner", column=@Column(name="fk_owner", nullable=false) ), 
        @AttributeOverride(name="fkRelation", column=@Column(name="fk_relation", nullable=false) ), 
        @AttributeOverride(name="ignored", column=@Column(name="ignored", nullable=false) ) } )
    public SocialId getId() {
        return this.id;
    }
    
    public void setId(SocialId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_owner", nullable=false, insertable=false, updatable=false)
    public Characters getCharactersByFkOwner() {
        return this.charactersByFkOwner;
    }
    
    public void setCharactersByFkOwner(Characters charactersByFkOwner) {
        this.charactersByFkOwner = charactersByFkOwner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_relation", nullable=false, insertable=false, updatable=false)
    public Characters getCharactersByFkRelation() {
        return this.charactersByFkRelation;
    }
    
    public void setCharactersByFkRelation(Characters charactersByFkRelation) {
        this.charactersByFkRelation = charactersByFkRelation;
    }




}


