package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SocialId generated by hbm2java
 */
@Embeddable
public class SocialId  implements java.io.Serializable {


     private long fkOwner;
     private long fkRelation;
     private boolean ignored;

    public SocialId() {
    }

    public SocialId(long fkOwner, long fkRelation, boolean ignored) {
       this.fkOwner = fkOwner;
       this.fkRelation = fkRelation;
       this.ignored = ignored;
    }
   


    @Column(name="fk_owner", nullable=false)
    public long getFkOwner() {
        return this.fkOwner;
    }
    
    public void setFkOwner(long fkOwner) {
        this.fkOwner = fkOwner;
    }


    @Column(name="fk_relation", nullable=false)
    public long getFkRelation() {
        return this.fkRelation;
    }
    
    public void setFkRelation(long fkRelation) {
        this.fkRelation = fkRelation;
    }


    @Column(name="ignored", nullable=false)
    public boolean isIgnored() {
        return this.ignored;
    }
    
    public void setIgnored(boolean ignored) {
        this.ignored = ignored;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SocialId) ) return false;
		 SocialId castOther = ( SocialId ) other; 
         
		 return (this.getFkOwner()==castOther.getFkOwner())
 && (this.getFkRelation()==castOther.getFkRelation())
 && (this.isIgnored()==castOther.isIgnored());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getFkOwner();
         result = 37 * result + (int) this.getFkRelation();
         result = 37 * result + (this.isIgnored()?1:0);
         return result;
   }   


}


