package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Spell generated by hbm2java
 */
@Entity
@Table(name="spell"
    ,catalog="jangoscharacters"
)
public class Spell  implements java.io.Serializable {


     private SpellId id;
     private Characters characters;
     private ItemInstance itemInstance;
     private boolean active;
     private Date cooldown;

    public Spell() {
    }

	
    public Spell(SpellId id, Characters characters, boolean active, Date cooldown) {
        this.id = id;
        this.characters = characters;
        this.active = active;
        this.cooldown = cooldown;
    }
    public Spell(SpellId id, Characters characters, ItemInstance itemInstance, boolean active, Date cooldown) {
       this.id = id;
       this.characters = characters;
       this.itemInstance = itemInstance;
       this.active = active;
       this.cooldown = cooldown;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkOwner", column=@Column(name="fk_owner", nullable=false) ), 
        @AttributeOverride(name="fkDbcSpell", column=@Column(name="fk_dbc_spell", nullable=false) ) } )
    public SpellId getId() {
        return this.id;
    }
    
    public void setId(SpellId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_owner", nullable=false, insertable=false, updatable=false)
    public Characters getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Characters characters) {
        this.characters = characters;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_item")
    public ItemInstance getItemInstance() {
        return this.itemInstance;
    }
    
    public void setItemInstance(ItemInstance itemInstance) {
        this.itemInstance = itemInstance;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cooldown", nullable=false, length=19)
    public Date getCooldown() {
        return this.cooldown;
    }
    
    public void setCooldown(Date cooldown) {
        this.cooldown = cooldown;
    }




}


