package eu.jangos.realm.model.characters;



import java.util.Date;

/**
 * Spell generated by hbm2java
 */
public class Spell  implements java.io.Serializable {


     private SpellId id;
     private ItemInstance itemInstance;
     private boolean active;
     private Date cooldown;

    public Spell() {
    }

    public Spell(SpellId id, ItemInstance itemInstance, boolean active, Date cooldown) {
       this.id = id;
       this.itemInstance = itemInstance;
       this.active = active;
       this.cooldown = cooldown;
    }
   
    public SpellId getId() {
        return this.id;
    }
    
    public void setId(SpellId id) {
        this.id = id;
    }

    public ItemInstance getItemInstance() {
        return itemInstance;
    }

    public void setItemInstance(ItemInstance itemInstance) {
        this.itemInstance = itemInstance;
    }   

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
    
    public Date getCooldown() {
        return this.cooldown;
    }
    
    public void setCooldown(Date cooldown) {
        this.cooldown = cooldown;
    }




}


