package eu.jangos.realm.model.characters;
// Generated 19-févr.-2016 21:17:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Spell generated by hbm2java
 */
public class Spell  implements java.io.Serializable {


     private SpellId id;
     private Characters characters;
     private int fkItem;
     private byte active;
     private Date cooldown;

    public Spell() {
    }

    public Spell(SpellId id, Characters characters, int fkItem, byte active, Date cooldown) {
       this.id = id;
       this.characters = characters;
       this.fkItem = fkItem;
       this.active = active;
       this.cooldown = cooldown;
    }
   
    public SpellId getId() {
        return this.id;
    }
    
    public void setId(SpellId id) {
        this.id = id;
    }
    public Characters getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Characters characters) {
        this.characters = characters;
    }
    public int getFkItem() {
        return this.fkItem;
    }
    
    public void setFkItem(int fkItem) {
        this.fkItem = fkItem;
    }
    public byte getActive() {
        return this.active;
    }
    
    public void setActive(byte active) {
        this.active = active;
    }
    public Date getCooldown() {
        return this.cooldown;
    }
    
    public void setCooldown(Date cooldown) {
        this.cooldown = cooldown;
    }




}


