package eu.jangos.realm.model.characters;
// Generated 06-mai-2016 23:00:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name="ticket"
    ,catalog="jangoscharacters"
)
public class Ticket  implements java.io.Serializable {


     private int id;
     private Characters characters;
     private String body;
     private String response;
     private Date lastupdate;
     private Boolean solved;
     private Set<Whispers> whisperses = new HashSet<Whispers>(0);

    public Ticket() {
    }

	
    public Ticket(int id, Characters characters, Date lastupdate) {
        this.id = id;
        this.characters = characters;
        this.lastupdate = lastupdate;
    }
    public Ticket(int id, Characters characters, String body, String response, Date lastupdate, Boolean solved, Set<Whispers> whisperses) {
       this.id = id;
       this.characters = characters;
       this.body = body;
       this.response = response;
       this.lastupdate = lastupdate;
       this.solved = solved;
       this.whisperses = whisperses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_character", nullable=false)
    public Characters getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Characters characters) {
        this.characters = characters;
    }

    
    @Column(name="body", length=65535)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    
    @Column(name="response", length=65535)
    public String getResponse() {
        return this.response;
    }
    
    public void setResponse(String response) {
        this.response = response;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastupdate", nullable=false, length=19)
    public Date getLastupdate() {
        return this.lastupdate;
    }
    
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    
    @Column(name="solved")
    public Boolean getSolved() {
        return this.solved;
    }
    
    public void setSolved(Boolean solved) {
        this.solved = solved;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticket")
    public Set<Whispers> getWhisperses() {
        return this.whisperses;
    }
    
    public void setWhisperses(Set<Whispers> whisperses) {
        this.whisperses = whisperses;
    }




}


