package eu.jangos.realm.model.characters;



import java.util.Date;

/**
 * Whispers generated by hbm2java
 */
public class Whispers  implements java.io.Serializable {


     private Integer id;
     private Characters charactersByFkFrom;
     private Characters charactersByFkTo;
     private Ticket ticket;
     private String message;
     private Date sent;

    public Whispers() {
    }

	
    public Whispers(Characters charactersByFkFrom, Characters charactersByFkTo, String message, Date sent) {
        this.charactersByFkFrom = charactersByFkFrom;
        this.charactersByFkTo = charactersByFkTo;
        this.message = message;
        this.sent = sent;
    }
    public Whispers(Characters charactersByFkFrom, Characters charactersByFkTo, Ticket ticket, String message, Date sent) {
       this.charactersByFkFrom = charactersByFkFrom;
       this.charactersByFkTo = charactersByFkTo;
       this.ticket = ticket;
       this.message = message;
       this.sent = sent;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Characters getCharactersByFkFrom() {
        return this.charactersByFkFrom;
    }
    
    public void setCharactersByFkFrom(Characters charactersByFkFrom) {
        this.charactersByFkFrom = charactersByFkFrom;
    }
    public Characters getCharactersByFkTo() {
        return this.charactersByFkTo;
    }
    
    public void setCharactersByFkTo(Characters charactersByFkTo) {
        this.charactersByFkTo = charactersByFkTo;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getSent() {
        return this.sent;
    }
    
    public void setSent(Date sent) {
        this.sent = sent;
    }




}


